[pytest]
mock_use_standalone_module = true
mock_traceback_monkeypatch = false
norecursedirs =
    .git
    .github
    dist
    build
    docs
    python/docs
testpaths = python/tests
addopts =
    --strict-markers
    --color=yes
    --disable-pytest-warnings
    --ignore=legacy/checkpoints
markers =
    project_permission_test: marker for project permission tests
filterwarnings =
    error::FutureWarning
    error::pytest.PytestUnhandledThreadExceptionWarning
xfail_strict = true
junit_duration_report = call
