# coding: utf-8
# This file is vendored.
# Do not edit it directly; changes will be overwritten.
# Make changes in the internal upstream repository instead.


"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class AssistantsServiceUpdateModelServingBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'api_key': 'str',
        'api_type': 'str',
        'base_url': 'str'
    }

    attribute_map = {
        'api_key': 'apiKey',
        'api_type': 'apiType',
        'base_url': 'baseUrl'
    }

    def __init__(self, api_key: 'str' =None, api_type: 'str' =None, base_url: 'str' =None):  # noqa: E501
        """AssistantsServiceUpdateModelServingBody - a model defined in Swagger"""  # noqa: E501
        self._api_key = None
        self._api_type = None
        self._base_url = None
        self.discriminator = None
        if api_key is not None:
            self.api_key = api_key
        if api_type is not None:
            self.api_type = api_type
        if base_url is not None:
            self.base_url = base_url

    @property
    def api_key(self) -> 'str':
        """Gets the api_key of this AssistantsServiceUpdateModelServingBody.  # noqa: E501

        Key sent upstream. When unset, a Lightning deployment or Studio URL uses that endpoint's own token, and the same host keeps the stored key; any other host requires one.  # noqa: E501

        :return: The api_key of this AssistantsServiceUpdateModelServingBody.  # noqa: E501
        :rtype: str
        """
        return self._api_key

    @api_key.setter
    def api_key(self, api_key: 'str'):
        """Sets the api_key of this AssistantsServiceUpdateModelServingBody.

        Key sent upstream. When unset, a Lightning deployment or Studio URL uses that endpoint's own token, and the same host keeps the stored key; any other host requires one.  # noqa: E501

        :param api_key: The api_key of this AssistantsServiceUpdateModelServingBody.  # noqa: E501
        :type: str
        """

        self._api_key = api_key

    @property
    def api_type(self) -> 'str':
        """Gets the api_type of this AssistantsServiceUpdateModelServingBody.  # noqa: E501


        :return: The api_type of this AssistantsServiceUpdateModelServingBody.  # noqa: E501
        :rtype: str
        """
        return self._api_type

    @api_type.setter
    def api_type(self, api_type: 'str'):
        """Sets the api_type of this AssistantsServiceUpdateModelServingBody.


        :param api_type: The api_type of this AssistantsServiceUpdateModelServingBody.  # noqa: E501
        :type: str
        """

        self._api_type = api_type

    @property
    def base_url(self) -> 'str':
        """Gets the base_url of this AssistantsServiceUpdateModelServingBody.  # noqa: E501


        :return: The base_url of this AssistantsServiceUpdateModelServingBody.  # noqa: E501
        :rtype: str
        """
        return self._base_url

    @base_url.setter
    def base_url(self, base_url: 'str'):
        """Sets the base_url of this AssistantsServiceUpdateModelServingBody.


        :param base_url: The base_url of this AssistantsServiceUpdateModelServingBody.  # noqa: E501
        :type: str
        """

        self._base_url = base_url

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssistantsServiceUpdateModelServingBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'AssistantsServiceUpdateModelServingBody') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, AssistantsServiceUpdateModelServingBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'AssistantsServiceUpdateModelServingBody') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
