# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class CloudSpaceServiceSuggestCloudSpaceNameBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'purpose': 'V1CloudSpaceNamePurpose',
        'source_cloudspace_id': 'str'
    }

    attribute_map = {
        'purpose': 'purpose',
        'source_cloudspace_id': 'sourceCloudspaceId'
    }

    def __init__(self, purpose: 'V1CloudSpaceNamePurpose' =None, source_cloudspace_id: 'str' =None):  # noqa: E501
        """CloudSpaceServiceSuggestCloudSpaceNameBody - a model defined in Swagger"""  # noqa: E501
        self._purpose = None
        self._source_cloudspace_id = None
        self.discriminator = None
        if purpose is not None:
            self.purpose = purpose
        if source_cloudspace_id is not None:
            self.source_cloudspace_id = source_cloudspace_id

    @property
    def purpose(self) -> 'V1CloudSpaceNamePurpose':
        """Gets the purpose of this CloudSpaceServiceSuggestCloudSpaceNameBody.  # noqa: E501


        :return: The purpose of this CloudSpaceServiceSuggestCloudSpaceNameBody.  # noqa: E501
        :rtype: V1CloudSpaceNamePurpose
        """
        return self._purpose

    @purpose.setter
    def purpose(self, purpose: 'V1CloudSpaceNamePurpose'):
        """Sets the purpose of this CloudSpaceServiceSuggestCloudSpaceNameBody.


        :param purpose: The purpose of this CloudSpaceServiceSuggestCloudSpaceNameBody.  # noqa: E501
        :type: V1CloudSpaceNamePurpose
        """

        self._purpose = purpose

    @property
    def source_cloudspace_id(self) -> 'str':
        """Gets the source_cloudspace_id of this CloudSpaceServiceSuggestCloudSpaceNameBody.  # noqa: E501


        :return: The source_cloudspace_id of this CloudSpaceServiceSuggestCloudSpaceNameBody.  # noqa: E501
        :rtype: str
        """
        return self._source_cloudspace_id

    @source_cloudspace_id.setter
    def source_cloudspace_id(self, source_cloudspace_id: 'str'):
        """Sets the source_cloudspace_id of this CloudSpaceServiceSuggestCloudSpaceNameBody.


        :param source_cloudspace_id: The source_cloudspace_id of this CloudSpaceServiceSuggestCloudSpaceNameBody.  # noqa: E501
        :type: str
        """

        self._source_cloudspace_id = source_cloudspace_id

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CloudSpaceServiceSuggestCloudSpaceNameBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'CloudSpaceServiceSuggestCloudSpaceNameBody') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, CloudSpaceServiceSuggestCloudSpaceNameBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'CloudSpaceServiceSuggestCloudSpaceNameBody') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
