# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class OrganizationsServiceSetOrgModelAPIDailyLimitDefaultBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'daily_limit_credits': 'float'
    }

    attribute_map = {
        'daily_limit_credits': 'dailyLimitCredits'
    }

    def __init__(self, daily_limit_credits: 'float' =None):  # noqa: E501
        """OrganizationsServiceSetOrgModelAPIDailyLimitDefaultBody - a model defined in Swagger"""  # noqa: E501
        self._daily_limit_credits = None
        self.discriminator = None
        if daily_limit_credits is not None:
            self.daily_limit_credits = daily_limit_credits

    @property
    def daily_limit_credits(self) -> 'float':
        """Gets the daily_limit_credits of this OrganizationsServiceSetOrgModelAPIDailyLimitDefaultBody.  # noqa: E501

        Unset clears the org default; a value sets the per-member default in credits.  # noqa: E501

        :return: The daily_limit_credits of this OrganizationsServiceSetOrgModelAPIDailyLimitDefaultBody.  # noqa: E501
        :rtype: float
        """
        return self._daily_limit_credits

    @daily_limit_credits.setter
    def daily_limit_credits(self, daily_limit_credits: 'float'):
        """Sets the daily_limit_credits of this OrganizationsServiceSetOrgModelAPIDailyLimitDefaultBody.

        Unset clears the org default; a value sets the per-member default in credits.  # noqa: E501

        :param daily_limit_credits: The daily_limit_credits of this OrganizationsServiceSetOrgModelAPIDailyLimitDefaultBody.  # noqa: E501
        :type: float
        """

        self._daily_limit_credits = daily_limit_credits

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrganizationsServiceSetOrgModelAPIDailyLimitDefaultBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'OrganizationsServiceSetOrgModelAPIDailyLimitDefaultBody') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganizationsServiceSetOrgModelAPIDailyLimitDefaultBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'OrganizationsServiceSetOrgModelAPIDailyLimitDefaultBody') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
