# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class SandboxesServiceExtendSandboxTimeoutBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'organization_id': 'str',
        'timeout': 'str'
    }

    attribute_map = {
        'organization_id': 'organizationId',
        'timeout': 'timeout'
    }

    def __init__(self, organization_id: 'str' =None, timeout: 'str' =None):  # noqa: E501
        """SandboxesServiceExtendSandboxTimeoutBody - a model defined in Swagger"""  # noqa: E501
        self._organization_id = None
        self._timeout = None
        self.discriminator = None
        if organization_id is not None:
            self.organization_id = organization_id
        if timeout is not None:
            self.timeout = timeout

    @property
    def organization_id(self) -> 'str':
        """Gets the organization_id of this SandboxesServiceExtendSandboxTimeoutBody.  # noqa: E501


        :return: The organization_id of this SandboxesServiceExtendSandboxTimeoutBody.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id: 'str'):
        """Sets the organization_id of this SandboxesServiceExtendSandboxTimeoutBody.


        :param organization_id: The organization_id of this SandboxesServiceExtendSandboxTimeoutBody.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def timeout(self) -> 'str':
        """Gets the timeout of this SandboxesServiceExtendSandboxTimeoutBody.  # noqa: E501

        The amount of time in milliseconds to add to the current timeout. Must be at least 1000ms (1 second).  # noqa: E501

        :return: The timeout of this SandboxesServiceExtendSandboxTimeoutBody.  # noqa: E501
        :rtype: str
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout: 'str'):
        """Sets the timeout of this SandboxesServiceExtendSandboxTimeoutBody.

        The amount of time in milliseconds to add to the current timeout. Must be at least 1000ms (1 second).  # noqa: E501

        :param timeout: The timeout of this SandboxesServiceExtendSandboxTimeoutBody.  # noqa: E501
        :type: str
        """

        self._timeout = timeout

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SandboxesServiceExtendSandboxTimeoutBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'SandboxesServiceExtendSandboxTimeoutBody') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, SandboxesServiceExtendSandboxTimeoutBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'SandboxesServiceExtendSandboxTimeoutBody') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
