# coding: utf-8
# This file is vendored.
# Do not edit it directly; changes will be overwritten.
# Make changes in the internal upstream repository instead.


"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class TimeFilterPivot(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pivot': 'datetime',
        'pivot_direction': 'TimeFilterPivotDirection'
    }

    attribute_map = {
        'pivot': 'pivot',
        'pivot_direction': 'pivotDirection'
    }

    def __init__(self, pivot: 'datetime' =None, pivot_direction: 'TimeFilterPivotDirection' =None):  # noqa: E501
        """TimeFilterPivot - a model defined in Swagger"""  # noqa: E501
        self._pivot = None
        self._pivot_direction = None
        self.discriminator = None
        if pivot is not None:
            self.pivot = pivot
        if pivot_direction is not None:
            self.pivot_direction = pivot_direction

    @property
    def pivot(self) -> 'datetime':
        """Gets the pivot of this TimeFilterPivot.  # noqa: E501


        :return: The pivot of this TimeFilterPivot.  # noqa: E501
        :rtype: datetime
        """
        return self._pivot

    @pivot.setter
    def pivot(self, pivot: 'datetime'):
        """Sets the pivot of this TimeFilterPivot.


        :param pivot: The pivot of this TimeFilterPivot.  # noqa: E501
        :type: datetime
        """

        self._pivot = pivot

    @property
    def pivot_direction(self) -> 'TimeFilterPivotDirection':
        """Gets the pivot_direction of this TimeFilterPivot.  # noqa: E501


        :return: The pivot_direction of this TimeFilterPivot.  # noqa: E501
        :rtype: TimeFilterPivotDirection
        """
        return self._pivot_direction

    @pivot_direction.setter
    def pivot_direction(self, pivot_direction: 'TimeFilterPivotDirection'):
        """Sets the pivot_direction of this TimeFilterPivot.


        :param pivot_direction: The pivot_direction of this TimeFilterPivot.  # noqa: E501
        :type: TimeFilterPivotDirection
        """

        self._pivot_direction = pivot_direction

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimeFilterPivot, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'TimeFilterPivot') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, TimeFilterPivot):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'TimeFilterPivot') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
