# coding: utf-8
# This file is vendored.
# Do not edit it directly; changes will be overwritten.
# Make changes in the internal upstream repository instead.


"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1ActivitySubfilterValues(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assistant_message': 'V1AssistantMessageSubfilterValues',
        'deployment': 'V1WorkloadSubfilterValues',
        'job': 'V1WorkloadSubfilterValues',
        'multi_machine_job': 'V1WorkloadSubfilterValues'
    }

    attribute_map = {
        'assistant_message': 'assistantMessage',
        'deployment': 'deployment',
        'job': 'job',
        'multi_machine_job': 'multiMachineJob'
    }

    def __init__(self, assistant_message: 'V1AssistantMessageSubfilterValues' =None, deployment: 'V1WorkloadSubfilterValues' =None, job: 'V1WorkloadSubfilterValues' =None, multi_machine_job: 'V1WorkloadSubfilterValues' =None):  # noqa: E501
        """V1ActivitySubfilterValues - a model defined in Swagger"""  # noqa: E501
        self._assistant_message = None
        self._deployment = None
        self._job = None
        self._multi_machine_job = None
        self.discriminator = None
        if assistant_message is not None:
            self.assistant_message = assistant_message
        if deployment is not None:
            self.deployment = deployment
        if job is not None:
            self.job = job
        if multi_machine_job is not None:
            self.multi_machine_job = multi_machine_job

    @property
    def assistant_message(self) -> 'V1AssistantMessageSubfilterValues':
        """Gets the assistant_message of this V1ActivitySubfilterValues.  # noqa: E501


        :return: The assistant_message of this V1ActivitySubfilterValues.  # noqa: E501
        :rtype: V1AssistantMessageSubfilterValues
        """
        return self._assistant_message

    @assistant_message.setter
    def assistant_message(self, assistant_message: 'V1AssistantMessageSubfilterValues'):
        """Sets the assistant_message of this V1ActivitySubfilterValues.


        :param assistant_message: The assistant_message of this V1ActivitySubfilterValues.  # noqa: E501
        :type: V1AssistantMessageSubfilterValues
        """

        self._assistant_message = assistant_message

    @property
    def deployment(self) -> 'V1WorkloadSubfilterValues':
        """Gets the deployment of this V1ActivitySubfilterValues.  # noqa: E501


        :return: The deployment of this V1ActivitySubfilterValues.  # noqa: E501
        :rtype: V1WorkloadSubfilterValues
        """
        return self._deployment

    @deployment.setter
    def deployment(self, deployment: 'V1WorkloadSubfilterValues'):
        """Sets the deployment of this V1ActivitySubfilterValues.


        :param deployment: The deployment of this V1ActivitySubfilterValues.  # noqa: E501
        :type: V1WorkloadSubfilterValues
        """

        self._deployment = deployment

    @property
    def job(self) -> 'V1WorkloadSubfilterValues':
        """Gets the job of this V1ActivitySubfilterValues.  # noqa: E501


        :return: The job of this V1ActivitySubfilterValues.  # noqa: E501
        :rtype: V1WorkloadSubfilterValues
        """
        return self._job

    @job.setter
    def job(self, job: 'V1WorkloadSubfilterValues'):
        """Sets the job of this V1ActivitySubfilterValues.


        :param job: The job of this V1ActivitySubfilterValues.  # noqa: E501
        :type: V1WorkloadSubfilterValues
        """

        self._job = job

    @property
    def multi_machine_job(self) -> 'V1WorkloadSubfilterValues':
        """Gets the multi_machine_job of this V1ActivitySubfilterValues.  # noqa: E501


        :return: The multi_machine_job of this V1ActivitySubfilterValues.  # noqa: E501
        :rtype: V1WorkloadSubfilterValues
        """
        return self._multi_machine_job

    @multi_machine_job.setter
    def multi_machine_job(self, multi_machine_job: 'V1WorkloadSubfilterValues'):
        """Sets the multi_machine_job of this V1ActivitySubfilterValues.


        :param multi_machine_job: The multi_machine_job of this V1ActivitySubfilterValues.  # noqa: E501
        :type: V1WorkloadSubfilterValues
        """

        self._multi_machine_job = multi_machine_job

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1ActivitySubfilterValues, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1ActivitySubfilterValues') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1ActivitySubfilterValues):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1ActivitySubfilterValues') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
