# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1AERCounter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bdf': 'str',
        'correctable': 'str',
        'fatal': 'str',
        'non_fatal': 'str'
    }

    attribute_map = {
        'bdf': 'bdf',
        'correctable': 'correctable',
        'fatal': 'fatal',
        'non_fatal': 'nonFatal'
    }

    def __init__(self, bdf: 'str' =None, correctable: 'str' =None, fatal: 'str' =None, non_fatal: 'str' =None):  # noqa: E501
        """V1AERCounter - a model defined in Swagger"""  # noqa: E501
        self._bdf = None
        self._correctable = None
        self._fatal = None
        self._non_fatal = None
        self.discriminator = None
        if bdf is not None:
            self.bdf = bdf
        if correctable is not None:
            self.correctable = correctable
        if fatal is not None:
            self.fatal = fatal
        if non_fatal is not None:
            self.non_fatal = non_fatal

    @property
    def bdf(self) -> 'str':
        """Gets the bdf of this V1AERCounter.  # noqa: E501


        :return: The bdf of this V1AERCounter.  # noqa: E501
        :rtype: str
        """
        return self._bdf

    @bdf.setter
    def bdf(self, bdf: 'str'):
        """Sets the bdf of this V1AERCounter.


        :param bdf: The bdf of this V1AERCounter.  # noqa: E501
        :type: str
        """

        self._bdf = bdf

    @property
    def correctable(self) -> 'str':
        """Gets the correctable of this V1AERCounter.  # noqa: E501


        :return: The correctable of this V1AERCounter.  # noqa: E501
        :rtype: str
        """
        return self._correctable

    @correctable.setter
    def correctable(self, correctable: 'str'):
        """Sets the correctable of this V1AERCounter.


        :param correctable: The correctable of this V1AERCounter.  # noqa: E501
        :type: str
        """

        self._correctable = correctable

    @property
    def fatal(self) -> 'str':
        """Gets the fatal of this V1AERCounter.  # noqa: E501


        :return: The fatal of this V1AERCounter.  # noqa: E501
        :rtype: str
        """
        return self._fatal

    @fatal.setter
    def fatal(self, fatal: 'str'):
        """Sets the fatal of this V1AERCounter.


        :param fatal: The fatal of this V1AERCounter.  # noqa: E501
        :type: str
        """

        self._fatal = fatal

    @property
    def non_fatal(self) -> 'str':
        """Gets the non_fatal of this V1AERCounter.  # noqa: E501


        :return: The non_fatal of this V1AERCounter.  # noqa: E501
        :rtype: str
        """
        return self._non_fatal

    @non_fatal.setter
    def non_fatal(self, non_fatal: 'str'):
        """Sets the non_fatal of this V1AERCounter.


        :param non_fatal: The non_fatal of this V1AERCounter.  # noqa: E501
        :type: str
        """

        self._non_fatal = non_fatal

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1AERCounter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1AERCounter') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1AERCounter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1AERCounter') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
