# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1CreateAPIKeyRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'name': 'str',
        'org_id': 'str',
        'project_id': 'str',
        'resource_id': 'str',
        'resource_type': 'str',
        'role': 'str'
    }

    attribute_map = {
        'description': 'description',
        'name': 'name',
        'org_id': 'orgId',
        'project_id': 'projectId',
        'resource_id': 'resourceId',
        'resource_type': 'resourceType',
        'role': 'role'
    }

    def __init__(self, description: 'str' =None, name: 'str' =None, org_id: 'str' =None, project_id: 'str' =None, resource_id: 'str' =None, resource_type: 'str' =None, role: 'str' =None):  # noqa: E501
        """V1CreateAPIKeyRequest - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._name = None
        self._org_id = None
        self._project_id = None
        self._resource_id = None
        self._resource_type = None
        self._role = None
        self.discriminator = None
        if description is not None:
            self.description = description
        if name is not None:
            self.name = name
        if org_id is not None:
            self.org_id = org_id
        if project_id is not None:
            self.project_id = project_id
        if resource_id is not None:
            self.resource_id = resource_id
        if resource_type is not None:
            self.resource_type = resource_type
        if role is not None:
            self.role = role

    @property
    def description(self) -> 'str':
        """Gets the description of this V1CreateAPIKeyRequest.  # noqa: E501


        :return: The description of this V1CreateAPIKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: 'str'):
        """Sets the description of this V1CreateAPIKeyRequest.


        :param description: The description of this V1CreateAPIKeyRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def name(self) -> 'str':
        """Gets the name of this V1CreateAPIKeyRequest.  # noqa: E501


        :return: The name of this V1CreateAPIKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: 'str'):
        """Sets the name of this V1CreateAPIKeyRequest.


        :param name: The name of this V1CreateAPIKeyRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def org_id(self) -> 'str':
        """Gets the org_id of this V1CreateAPIKeyRequest.  # noqa: E501


        :return: The org_id of this V1CreateAPIKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id: 'str'):
        """Sets the org_id of this V1CreateAPIKeyRequest.


        :param org_id: The org_id of this V1CreateAPIKeyRequest.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def project_id(self) -> 'str':
        """Gets the project_id of this V1CreateAPIKeyRequest.  # noqa: E501


        :return: The project_id of this V1CreateAPIKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id: 'str'):
        """Sets the project_id of this V1CreateAPIKeyRequest.


        :param project_id: The project_id of this V1CreateAPIKeyRequest.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def resource_id(self) -> 'str':
        """Gets the resource_id of this V1CreateAPIKeyRequest.  # noqa: E501


        :return: The resource_id of this V1CreateAPIKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id: 'str'):
        """Sets the resource_id of this V1CreateAPIKeyRequest.


        :param resource_id: The resource_id of this V1CreateAPIKeyRequest.  # noqa: E501
        :type: str
        """

        self._resource_id = resource_id

    @property
    def resource_type(self) -> 'str':
        """Gets the resource_type of this V1CreateAPIKeyRequest.  # noqa: E501


        :return: The resource_type of this V1CreateAPIKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type: 'str'):
        """Sets the resource_type of this V1CreateAPIKeyRequest.


        :param resource_type: The resource_type of this V1CreateAPIKeyRequest.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def role(self) -> 'str':
        """Gets the role of this V1CreateAPIKeyRequest.  # noqa: E501


        :return: The role of this V1CreateAPIKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: 'str'):
        """Sets the role of this V1CreateAPIKeyRequest.


        :param role: The role of this V1CreateAPIKeyRequest.  # noqa: E501
        :type: str
        """

        self._role = role

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1CreateAPIKeyRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1CreateAPIKeyRequest') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1CreateAPIKeyRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1CreateAPIKeyRequest') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
