# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1ComputeApp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gpu_uuid': 'str',
        'memory_mb': 'str',
        'pid': 'int',
        'process_name': 'str'
    }

    attribute_map = {
        'gpu_uuid': 'gpuUuid',
        'memory_mb': 'memoryMb',
        'pid': 'pid',
        'process_name': 'processName'
    }

    def __init__(self, gpu_uuid: 'str' =None, memory_mb: 'str' =None, pid: 'int' =None, process_name: 'str' =None):  # noqa: E501
        """V1ComputeApp - a model defined in Swagger"""  # noqa: E501
        self._gpu_uuid = None
        self._memory_mb = None
        self._pid = None
        self._process_name = None
        self.discriminator = None
        if gpu_uuid is not None:
            self.gpu_uuid = gpu_uuid
        if memory_mb is not None:
            self.memory_mb = memory_mb
        if pid is not None:
            self.pid = pid
        if process_name is not None:
            self.process_name = process_name

    @property
    def gpu_uuid(self) -> 'str':
        """Gets the gpu_uuid of this V1ComputeApp.  # noqa: E501


        :return: The gpu_uuid of this V1ComputeApp.  # noqa: E501
        :rtype: str
        """
        return self._gpu_uuid

    @gpu_uuid.setter
    def gpu_uuid(self, gpu_uuid: 'str'):
        """Sets the gpu_uuid of this V1ComputeApp.


        :param gpu_uuid: The gpu_uuid of this V1ComputeApp.  # noqa: E501
        :type: str
        """

        self._gpu_uuid = gpu_uuid

    @property
    def memory_mb(self) -> 'str':
        """Gets the memory_mb of this V1ComputeApp.  # noqa: E501


        :return: The memory_mb of this V1ComputeApp.  # noqa: E501
        :rtype: str
        """
        return self._memory_mb

    @memory_mb.setter
    def memory_mb(self, memory_mb: 'str'):
        """Sets the memory_mb of this V1ComputeApp.


        :param memory_mb: The memory_mb of this V1ComputeApp.  # noqa: E501
        :type: str
        """

        self._memory_mb = memory_mb

    @property
    def pid(self) -> 'int':
        """Gets the pid of this V1ComputeApp.  # noqa: E501


        :return: The pid of this V1ComputeApp.  # noqa: E501
        :rtype: int
        """
        return self._pid

    @pid.setter
    def pid(self, pid: 'int'):
        """Sets the pid of this V1ComputeApp.


        :param pid: The pid of this V1ComputeApp.  # noqa: E501
        :type: int
        """

        self._pid = pid

    @property
    def process_name(self) -> 'str':
        """Gets the process_name of this V1ComputeApp.  # noqa: E501


        :return: The process_name of this V1ComputeApp.  # noqa: E501
        :rtype: str
        """
        return self._process_name

    @process_name.setter
    def process_name(self, process_name: 'str'):
        """Sets the process_name of this V1ComputeApp.


        :param process_name: The process_name of this V1ComputeApp.  # noqa: E501
        :type: str
        """

        self._process_name = process_name

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1ComputeApp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1ComputeApp') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1ComputeApp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1ComputeApp') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
