# coding: utf-8
# This file is vendored.
# Do not edit it directly; changes will be overwritten.
# Make changes in the internal upstream repository instead.


"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1CodingPlanVerdict(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'blocked_until': 'datetime',
        'covered': 'bool',
        'included': 'bool',
        'max_concurrent_requests': 'int',
        'org_id': 'str',
        'usage_credits_enabled': 'bool',
        'user_id': 'str',
        'windows': 'list[V1CodingUsageWindow]'
    }

    attribute_map = {
        'blocked_until': 'blockedUntil',
        'covered': 'covered',
        'included': 'included',
        'max_concurrent_requests': 'maxConcurrentRequests',
        'org_id': 'orgId',
        'usage_credits_enabled': 'usageCreditsEnabled',
        'user_id': 'userId',
        'windows': 'windows'
    }

    def __init__(self, blocked_until: 'datetime' =None, covered: 'bool' =None, included: 'bool' =None, max_concurrent_requests: 'int' =None, org_id: 'str' =None, usage_credits_enabled: 'bool' =None, user_id: 'str' =None, windows: 'list[V1CodingUsageWindow]' =None):  # noqa: E501
        """V1CodingPlanVerdict - a model defined in Swagger"""  # noqa: E501
        self._blocked_until = None
        self._covered = None
        self._included = None
        self._max_concurrent_requests = None
        self._org_id = None
        self._usage_credits_enabled = None
        self._user_id = None
        self._windows = None
        self.discriminator = None
        if blocked_until is not None:
            self.blocked_until = blocked_until
        if covered is not None:
            self.covered = covered
        if included is not None:
            self.included = included
        if max_concurrent_requests is not None:
            self.max_concurrent_requests = max_concurrent_requests
        if org_id is not None:
            self.org_id = org_id
        if usage_credits_enabled is not None:
            self.usage_credits_enabled = usage_credits_enabled
        if user_id is not None:
            self.user_id = user_id
        if windows is not None:
            self.windows = windows

    @property
    def blocked_until(self) -> 'datetime':
        """Gets the blocked_until of this V1CodingPlanVerdict.  # noqa: E501

        When a window is spent, the time every spent window has reset. Unset while covered.  # noqa: E501

        :return: The blocked_until of this V1CodingPlanVerdict.  # noqa: E501
        :rtype: datetime
        """
        return self._blocked_until

    @blocked_until.setter
    def blocked_until(self, blocked_until: 'datetime'):
        """Sets the blocked_until of this V1CodingPlanVerdict.

        When a window is spent, the time every spent window has reset. Unset while covered.  # noqa: E501

        :param blocked_until: The blocked_until of this V1CodingPlanVerdict.  # noqa: E501
        :type: datetime
        """

        self._blocked_until = blocked_until

    @property
    def covered(self) -> 'bool':
        """Gets the covered of this V1CodingPlanVerdict.  # noqa: E501

        Every window has room, so the next request is free whatever the balance.  # noqa: E501

        :return: The covered of this V1CodingPlanVerdict.  # noqa: E501
        :rtype: bool
        """
        return self._covered

    @covered.setter
    def covered(self, covered: 'bool'):
        """Sets the covered of this V1CodingPlanVerdict.

        Every window has room, so the next request is free whatever the balance.  # noqa: E501

        :param covered: The covered of this V1CodingPlanVerdict.  # noqa: E501
        :type: bool
        """

        self._covered = covered

    @property
    def included(self) -> 'bool':
        """Gets the included of this V1CodingPlanVerdict.  # noqa: E501

        The plan includes coding usage. When false, requests are paid from credits as before.  # noqa: E501

        :return: The included of this V1CodingPlanVerdict.  # noqa: E501
        :rtype: bool
        """
        return self._included

    @included.setter
    def included(self, included: 'bool'):
        """Sets the included of this V1CodingPlanVerdict.

        The plan includes coding usage. When false, requests are paid from credits as before.  # noqa: E501

        :param included: The included of this V1CodingPlanVerdict.  # noqa: E501
        :type: bool
        """

        self._included = included

    @property
    def max_concurrent_requests(self) -> 'int':
        """Gets the max_concurrent_requests of this V1CodingPlanVerdict.  # noqa: E501

        Requests the caller may have in flight in this org, whether the plan covers them or credits pay. Zero means no cap.  # noqa: E501

        :return: The max_concurrent_requests of this V1CodingPlanVerdict.  # noqa: E501
        :rtype: int
        """
        return self._max_concurrent_requests

    @max_concurrent_requests.setter
    def max_concurrent_requests(self, max_concurrent_requests: 'int'):
        """Sets the max_concurrent_requests of this V1CodingPlanVerdict.

        Requests the caller may have in flight in this org, whether the plan covers them or credits pay. Zero means no cap.  # noqa: E501

        :param max_concurrent_requests: The max_concurrent_requests of this V1CodingPlanVerdict.  # noqa: E501
        :type: int
        """

        self._max_concurrent_requests = max_concurrent_requests

    @property
    def org_id(self) -> 'str':
        """Gets the org_id of this V1CodingPlanVerdict.  # noqa: E501


        :return: The org_id of this V1CodingPlanVerdict.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id: 'str'):
        """Sets the org_id of this V1CodingPlanVerdict.


        :param org_id: The org_id of this V1CodingPlanVerdict.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def usage_credits_enabled(self) -> 'bool':
        """Gets the usage_credits_enabled of this V1CodingPlanVerdict.  # noqa: E501

        With a window spent, requests go on and are paid from credits.  # noqa: E501

        :return: The usage_credits_enabled of this V1CodingPlanVerdict.  # noqa: E501
        :rtype: bool
        """
        return self._usage_credits_enabled

    @usage_credits_enabled.setter
    def usage_credits_enabled(self, usage_credits_enabled: 'bool'):
        """Sets the usage_credits_enabled of this V1CodingPlanVerdict.

        With a window spent, requests go on and are paid from credits.  # noqa: E501

        :param usage_credits_enabled: The usage_credits_enabled of this V1CodingPlanVerdict.  # noqa: E501
        :type: bool
        """

        self._usage_credits_enabled = usage_credits_enabled

    @property
    def user_id(self) -> 'str':
        """Gets the user_id of this V1CodingPlanVerdict.  # noqa: E501

        The caller and the org whose windows count the request: the worker's in-flight requests are capped per user per org.  # noqa: E501

        :return: The user_id of this V1CodingPlanVerdict.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: 'str'):
        """Sets the user_id of this V1CodingPlanVerdict.

        The caller and the org whose windows count the request: the worker's in-flight requests are capped per user per org.  # noqa: E501

        :param user_id: The user_id of this V1CodingPlanVerdict.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def windows(self) -> 'list[V1CodingUsageWindow]':
        """Gets the windows of this V1CodingPlanVerdict.  # noqa: E501


        :return: The windows of this V1CodingPlanVerdict.  # noqa: E501
        :rtype: list[V1CodingUsageWindow]
        """
        return self._windows

    @windows.setter
    def windows(self, windows: 'list[V1CodingUsageWindow]'):
        """Sets the windows of this V1CodingPlanVerdict.


        :param windows: The windows of this V1CodingPlanVerdict.  # noqa: E501
        :type: list[V1CodingUsageWindow]
        """

        self._windows = windows

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1CodingPlanVerdict, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1CodingPlanVerdict') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1CodingPlanVerdict):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1CodingPlanVerdict') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
