# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1ChartMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'chart_type': 'V1ChartType',
        'id': 'str',
        'series': 'list[V1SeriesConfig]',
        'stream_id': 'str',
        'subtitle': 'str',
        'title': 'str',
        'x_axis': 'V1AxisConfig',
        'y_axis': 'V1AxisConfig'
    }

    attribute_map = {
        'chart_type': 'chartType',
        'id': 'id',
        'series': 'series',
        'stream_id': 'streamId',
        'subtitle': 'subtitle',
        'title': 'title',
        'x_axis': 'xAxis',
        'y_axis': 'yAxis'
    }

    def __init__(self, chart_type: 'V1ChartType' =None, id: 'str' =None, series: 'list[V1SeriesConfig]' =None, stream_id: 'str' =None, subtitle: 'str' =None, title: 'str' =None, x_axis: 'V1AxisConfig' =None, y_axis: 'V1AxisConfig' =None):  # noqa: E501
        """V1ChartMetadata - a model defined in Swagger"""  # noqa: E501
        self._chart_type = None
        self._id = None
        self._series = None
        self._stream_id = None
        self._subtitle = None
        self._title = None
        self._x_axis = None
        self._y_axis = None
        self.discriminator = None
        if chart_type is not None:
            self.chart_type = chart_type
        if id is not None:
            self.id = id
        if series is not None:
            self.series = series
        if stream_id is not None:
            self.stream_id = stream_id
        if subtitle is not None:
            self.subtitle = subtitle
        if title is not None:
            self.title = title
        if x_axis is not None:
            self.x_axis = x_axis
        if y_axis is not None:
            self.y_axis = y_axis

    @property
    def chart_type(self) -> 'V1ChartType':
        """Gets the chart_type of this V1ChartMetadata.  # noqa: E501


        :return: The chart_type of this V1ChartMetadata.  # noqa: E501
        :rtype: V1ChartType
        """
        return self._chart_type

    @chart_type.setter
    def chart_type(self, chart_type: 'V1ChartType'):
        """Sets the chart_type of this V1ChartMetadata.


        :param chart_type: The chart_type of this V1ChartMetadata.  # noqa: E501
        :type: V1ChartType
        """

        self._chart_type = chart_type

    @property
    def id(self) -> 'str':
        """Gets the id of this V1ChartMetadata.  # noqa: E501


        :return: The id of this V1ChartMetadata.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: 'str'):
        """Sets the id of this V1ChartMetadata.


        :param id: The id of this V1ChartMetadata.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def series(self) -> 'list[V1SeriesConfig]':
        """Gets the series of this V1ChartMetadata.  # noqa: E501


        :return: The series of this V1ChartMetadata.  # noqa: E501
        :rtype: list[V1SeriesConfig]
        """
        return self._series

    @series.setter
    def series(self, series: 'list[V1SeriesConfig]'):
        """Sets the series of this V1ChartMetadata.


        :param series: The series of this V1ChartMetadata.  # noqa: E501
        :type: list[V1SeriesConfig]
        """

        self._series = series

    @property
    def stream_id(self) -> 'str':
        """Gets the stream_id of this V1ChartMetadata.  # noqa: E501


        :return: The stream_id of this V1ChartMetadata.  # noqa: E501
        :rtype: str
        """
        return self._stream_id

    @stream_id.setter
    def stream_id(self, stream_id: 'str'):
        """Sets the stream_id of this V1ChartMetadata.


        :param stream_id: The stream_id of this V1ChartMetadata.  # noqa: E501
        :type: str
        """

        self._stream_id = stream_id

    @property
    def subtitle(self) -> 'str':
        """Gets the subtitle of this V1ChartMetadata.  # noqa: E501


        :return: The subtitle of this V1ChartMetadata.  # noqa: E501
        :rtype: str
        """
        return self._subtitle

    @subtitle.setter
    def subtitle(self, subtitle: 'str'):
        """Sets the subtitle of this V1ChartMetadata.


        :param subtitle: The subtitle of this V1ChartMetadata.  # noqa: E501
        :type: str
        """

        self._subtitle = subtitle

    @property
    def title(self) -> 'str':
        """Gets the title of this V1ChartMetadata.  # noqa: E501


        :return: The title of this V1ChartMetadata.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: 'str'):
        """Sets the title of this V1ChartMetadata.


        :param title: The title of this V1ChartMetadata.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def x_axis(self) -> 'V1AxisConfig':
        """Gets the x_axis of this V1ChartMetadata.  # noqa: E501


        :return: The x_axis of this V1ChartMetadata.  # noqa: E501
        :rtype: V1AxisConfig
        """
        return self._x_axis

    @x_axis.setter
    def x_axis(self, x_axis: 'V1AxisConfig'):
        """Sets the x_axis of this V1ChartMetadata.


        :param x_axis: The x_axis of this V1ChartMetadata.  # noqa: E501
        :type: V1AxisConfig
        """

        self._x_axis = x_axis

    @property
    def y_axis(self) -> 'V1AxisConfig':
        """Gets the y_axis of this V1ChartMetadata.  # noqa: E501


        :return: The y_axis of this V1ChartMetadata.  # noqa: E501
        :rtype: V1AxisConfig
        """
        return self._y_axis

    @y_axis.setter
    def y_axis(self, y_axis: 'V1AxisConfig'):
        """Sets the y_axis of this V1ChartMetadata.


        :param y_axis: The y_axis of this V1ChartMetadata.  # noqa: E501
        :type: V1AxisConfig
        """

        self._y_axis = y_axis

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1ChartMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1ChartMetadata') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1ChartMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1ChartMetadata') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
