# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1DeviceIsolationFitness(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bdf': 'str',
        'collection_state': 'str',
        'foreign_devices': 'list[str]',
        'group_devices': 'int',
        'iommu_group': 'str',
        'isolated': 'bool'
    }

    attribute_map = {
        'bdf': 'bdf',
        'collection_state': 'collectionState',
        'foreign_devices': 'foreignDevices',
        'group_devices': 'groupDevices',
        'iommu_group': 'iommuGroup',
        'isolated': 'isolated'
    }

    def __init__(self, bdf: 'str' =None, collection_state: 'str' =None, foreign_devices: 'list[str]' =None, group_devices: 'int' =None, iommu_group: 'str' =None, isolated: 'bool' =None):  # noqa: E501
        """V1DeviceIsolationFitness - a model defined in Swagger"""  # noqa: E501
        self._bdf = None
        self._collection_state = None
        self._foreign_devices = None
        self._group_devices = None
        self._iommu_group = None
        self._isolated = None
        self.discriminator = None
        if bdf is not None:
            self.bdf = bdf
        if collection_state is not None:
            self.collection_state = collection_state
        if foreign_devices is not None:
            self.foreign_devices = foreign_devices
        if group_devices is not None:
            self.group_devices = group_devices
        if iommu_group is not None:
            self.iommu_group = iommu_group
        if isolated is not None:
            self.isolated = isolated

    @property
    def bdf(self) -> 'str':
        """Gets the bdf of this V1DeviceIsolationFitness.  # noqa: E501


        :return: The bdf of this V1DeviceIsolationFitness.  # noqa: E501
        :rtype: str
        """
        return self._bdf

    @bdf.setter
    def bdf(self, bdf: 'str'):
        """Sets the bdf of this V1DeviceIsolationFitness.


        :param bdf: The bdf of this V1DeviceIsolationFitness.  # noqa: E501
        :type: str
        """

        self._bdf = bdf

    @property
    def collection_state(self) -> 'str':
        """Gets the collection_state of this V1DeviceIsolationFitness.  # noqa: E501


        :return: The collection_state of this V1DeviceIsolationFitness.  # noqa: E501
        :rtype: str
        """
        return self._collection_state

    @collection_state.setter
    def collection_state(self, collection_state: 'str'):
        """Sets the collection_state of this V1DeviceIsolationFitness.


        :param collection_state: The collection_state of this V1DeviceIsolationFitness.  # noqa: E501
        :type: str
        """

        self._collection_state = collection_state

    @property
    def foreign_devices(self) -> 'list[str]':
        """Gets the foreign_devices of this V1DeviceIsolationFitness.  # noqa: E501


        :return: The foreign_devices of this V1DeviceIsolationFitness.  # noqa: E501
        :rtype: list[str]
        """
        return self._foreign_devices

    @foreign_devices.setter
    def foreign_devices(self, foreign_devices: 'list[str]'):
        """Sets the foreign_devices of this V1DeviceIsolationFitness.


        :param foreign_devices: The foreign_devices of this V1DeviceIsolationFitness.  # noqa: E501
        :type: list[str]
        """

        self._foreign_devices = foreign_devices

    @property
    def group_devices(self) -> 'int':
        """Gets the group_devices of this V1DeviceIsolationFitness.  # noqa: E501


        :return: The group_devices of this V1DeviceIsolationFitness.  # noqa: E501
        :rtype: int
        """
        return self._group_devices

    @group_devices.setter
    def group_devices(self, group_devices: 'int'):
        """Sets the group_devices of this V1DeviceIsolationFitness.


        :param group_devices: The group_devices of this V1DeviceIsolationFitness.  # noqa: E501
        :type: int
        """

        self._group_devices = group_devices

    @property
    def iommu_group(self) -> 'str':
        """Gets the iommu_group of this V1DeviceIsolationFitness.  # noqa: E501


        :return: The iommu_group of this V1DeviceIsolationFitness.  # noqa: E501
        :rtype: str
        """
        return self._iommu_group

    @iommu_group.setter
    def iommu_group(self, iommu_group: 'str'):
        """Sets the iommu_group of this V1DeviceIsolationFitness.


        :param iommu_group: The iommu_group of this V1DeviceIsolationFitness.  # noqa: E501
        :type: str
        """

        self._iommu_group = iommu_group

    @property
    def isolated(self) -> 'bool':
        """Gets the isolated of this V1DeviceIsolationFitness.  # noqa: E501


        :return: The isolated of this V1DeviceIsolationFitness.  # noqa: E501
        :rtype: bool
        """
        return self._isolated

    @isolated.setter
    def isolated(self, isolated: 'bool'):
        """Sets the isolated of this V1DeviceIsolationFitness.


        :param isolated: The isolated of this V1DeviceIsolationFitness.  # noqa: E501
        :type: bool
        """

        self._isolated = isolated

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1DeviceIsolationFitness, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1DeviceIsolationFitness') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1DeviceIsolationFitness):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1DeviceIsolationFitness') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
