# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1DMAEntryLimit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'present': 'bool',
        'value': 'str'
    }

    attribute_map = {
        'present': 'present',
        'value': 'value'
    }

    def __init__(self, present: 'bool' =None, value: 'str' =None):  # noqa: E501
        """V1DMAEntryLimit - a model defined in Swagger"""  # noqa: E501
        self._present = None
        self._value = None
        self.discriminator = None
        if present is not None:
            self.present = present
        if value is not None:
            self.value = value

    @property
    def present(self) -> 'bool':
        """Gets the present of this V1DMAEntryLimit.  # noqa: E501


        :return: The present of this V1DMAEntryLimit.  # noqa: E501
        :rtype: bool
        """
        return self._present

    @present.setter
    def present(self, present: 'bool'):
        """Sets the present of this V1DMAEntryLimit.


        :param present: The present of this V1DMAEntryLimit.  # noqa: E501
        :type: bool
        """

        self._present = present

    @property
    def value(self) -> 'str':
        """Gets the value of this V1DMAEntryLimit.  # noqa: E501


        :return: The value of this V1DMAEntryLimit.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: 'str'):
        """Sets the value of this V1DMAEntryLimit.


        :param value: The value of this V1DMAEntryLimit.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1DMAEntryLimit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1DMAEntryLimit') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1DMAEntryLimit):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1DMAEntryLimit') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
