# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1GpuSlaTerm(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'end_date': 'datetime',
        'gpus': 'int',
        'start_date': 'datetime'
    }

    attribute_map = {
        'end_date': 'endDate',
        'gpus': 'gpus',
        'start_date': 'startDate'
    }

    def __init__(self, end_date: 'datetime' =None, gpus: 'int' =None, start_date: 'datetime' =None):  # noqa: E501
        """V1GpuSlaTerm - a model defined in Swagger"""  # noqa: E501
        self._end_date = None
        self._gpus = None
        self._start_date = None
        self.discriminator = None
        if end_date is not None:
            self.end_date = end_date
        if gpus is not None:
            self.gpus = gpus
        if start_date is not None:
            self.start_date = start_date

    @property
    def end_date(self) -> 'datetime':
        """Gets the end_date of this V1GpuSlaTerm.  # noqa: E501


        :return: The end_date of this V1GpuSlaTerm.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: 'datetime'):
        """Sets the end_date of this V1GpuSlaTerm.


        :param end_date: The end_date of this V1GpuSlaTerm.  # noqa: E501
        :type: datetime
        """

        self._end_date = end_date

    @property
    def gpus(self) -> 'int':
        """Gets the gpus of this V1GpuSlaTerm.  # noqa: E501


        :return: The gpus of this V1GpuSlaTerm.  # noqa: E501
        :rtype: int
        """
        return self._gpus

    @gpus.setter
    def gpus(self, gpus: 'int'):
        """Sets the gpus of this V1GpuSlaTerm.


        :param gpus: The gpus of this V1GpuSlaTerm.  # noqa: E501
        :type: int
        """

        self._gpus = gpus

    @property
    def start_date(self) -> 'datetime':
        """Gets the start_date of this V1GpuSlaTerm.  # noqa: E501


        :return: The start_date of this V1GpuSlaTerm.  # noqa: E501
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: 'datetime'):
        """Sets the start_date of this V1GpuSlaTerm.


        :param start_date: The start_date of this V1GpuSlaTerm.  # noqa: E501
        :type: datetime
        """

        self._start_date = start_date

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1GpuSlaTerm, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1GpuSlaTerm') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1GpuSlaTerm):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1GpuSlaTerm') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
