# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set

    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1GpuTelemetryVm(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'ssh_port': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'ssh_port': 'sshPort'
    }

    def __init__(self, id: 'str' =None, name: 'str' =None, ssh_port: 'int' =None):  # noqa: E501
        """V1GpuTelemetryVm - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._ssh_port = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if ssh_port is not None:
            self.ssh_port = ssh_port

    @property
    def id(self) -> 'str':
        """Gets the id of this V1GpuTelemetryVm.  # noqa: E501


        :return: The id of this V1GpuTelemetryVm.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: 'str'):
        """Sets the id of this V1GpuTelemetryVm.


        :param id: The id of this V1GpuTelemetryVm.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self) -> 'str':
        """Gets the name of this V1GpuTelemetryVm.  # noqa: E501


        :return: The name of this V1GpuTelemetryVm.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: 'str'):
        """Sets the name of this V1GpuTelemetryVm.


        :param name: The name of this V1GpuTelemetryVm.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def ssh_port(self) -> 'int':
        """Gets the ssh_port of this V1GpuTelemetryVm.  # noqa: E501


        :return: The ssh_port of this V1GpuTelemetryVm.  # noqa: E501
        :rtype: int
        """
        return self._ssh_port

    @ssh_port.setter
    def ssh_port(self, ssh_port: 'int'):
        """Sets the ssh_port of this V1GpuTelemetryVm.


        :param ssh_port: The ssh_port of this V1GpuTelemetryVm.  # noqa: E501
        :type: int
        """

        self._ssh_port = ssh_port

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1GpuTelemetryVm, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1GpuTelemetryVm') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1GpuTelemetryVm):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1GpuTelemetryVm') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
