# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1GlobalSearchResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'apps': 'list[V1SearchResourceHit]',
        'cloudspaces': 'list[V1SearchResourceHit]',
        'datasets': 'list[V1SearchResourceHit]',
        'deployments': 'list[V1SearchResourceHit]',
        'jobs': 'list[V1SearchResourceHit]',
        'projects': 'list[V1SearchResourceHit]'
    }

    attribute_map = {
        'apps': 'apps',
        'cloudspaces': 'cloudspaces',
        'datasets': 'datasets',
        'deployments': 'deployments',
        'jobs': 'jobs',
        'projects': 'projects'
    }

    def __init__(self, apps: 'list[V1SearchResourceHit]' =None, cloudspaces: 'list[V1SearchResourceHit]' =None, datasets: 'list[V1SearchResourceHit]' =None, deployments: 'list[V1SearchResourceHit]' =None, jobs: 'list[V1SearchResourceHit]' =None, projects: 'list[V1SearchResourceHit]' =None):  # noqa: E501
        """V1GlobalSearchResponse - a model defined in Swagger"""  # noqa: E501
        self._apps = None
        self._cloudspaces = None
        self._datasets = None
        self._deployments = None
        self._jobs = None
        self._projects = None
        self.discriminator = None
        if apps is not None:
            self.apps = apps
        if cloudspaces is not None:
            self.cloudspaces = cloudspaces
        if datasets is not None:
            self.datasets = datasets
        if deployments is not None:
            self.deployments = deployments
        if jobs is not None:
            self.jobs = jobs
        if projects is not None:
            self.projects = projects

    @property
    def apps(self) -> 'list[V1SearchResourceHit]':
        """Gets the apps of this V1GlobalSearchResponse.  # noqa: E501


        :return: The apps of this V1GlobalSearchResponse.  # noqa: E501
        :rtype: list[V1SearchResourceHit]
        """
        return self._apps

    @apps.setter
    def apps(self, apps: 'list[V1SearchResourceHit]'):
        """Sets the apps of this V1GlobalSearchResponse.


        :param apps: The apps of this V1GlobalSearchResponse.  # noqa: E501
        :type: list[V1SearchResourceHit]
        """

        self._apps = apps

    @property
    def cloudspaces(self) -> 'list[V1SearchResourceHit]':
        """Gets the cloudspaces of this V1GlobalSearchResponse.  # noqa: E501


        :return: The cloudspaces of this V1GlobalSearchResponse.  # noqa: E501
        :rtype: list[V1SearchResourceHit]
        """
        return self._cloudspaces

    @cloudspaces.setter
    def cloudspaces(self, cloudspaces: 'list[V1SearchResourceHit]'):
        """Sets the cloudspaces of this V1GlobalSearchResponse.


        :param cloudspaces: The cloudspaces of this V1GlobalSearchResponse.  # noqa: E501
        :type: list[V1SearchResourceHit]
        """

        self._cloudspaces = cloudspaces

    @property
    def datasets(self) -> 'list[V1SearchResourceHit]':
        """Gets the datasets of this V1GlobalSearchResponse.  # noqa: E501


        :return: The datasets of this V1GlobalSearchResponse.  # noqa: E501
        :rtype: list[V1SearchResourceHit]
        """
        return self._datasets

    @datasets.setter
    def datasets(self, datasets: 'list[V1SearchResourceHit]'):
        """Sets the datasets of this V1GlobalSearchResponse.


        :param datasets: The datasets of this V1GlobalSearchResponse.  # noqa: E501
        :type: list[V1SearchResourceHit]
        """

        self._datasets = datasets

    @property
    def deployments(self) -> 'list[V1SearchResourceHit]':
        """Gets the deployments of this V1GlobalSearchResponse.  # noqa: E501


        :return: The deployments of this V1GlobalSearchResponse.  # noqa: E501
        :rtype: list[V1SearchResourceHit]
        """
        return self._deployments

    @deployments.setter
    def deployments(self, deployments: 'list[V1SearchResourceHit]'):
        """Sets the deployments of this V1GlobalSearchResponse.


        :param deployments: The deployments of this V1GlobalSearchResponse.  # noqa: E501
        :type: list[V1SearchResourceHit]
        """

        self._deployments = deployments

    @property
    def jobs(self) -> 'list[V1SearchResourceHit]':
        """Gets the jobs of this V1GlobalSearchResponse.  # noqa: E501


        :return: The jobs of this V1GlobalSearchResponse.  # noqa: E501
        :rtype: list[V1SearchResourceHit]
        """
        return self._jobs

    @jobs.setter
    def jobs(self, jobs: 'list[V1SearchResourceHit]'):
        """Sets the jobs of this V1GlobalSearchResponse.


        :param jobs: The jobs of this V1GlobalSearchResponse.  # noqa: E501
        :type: list[V1SearchResourceHit]
        """

        self._jobs = jobs

    @property
    def projects(self) -> 'list[V1SearchResourceHit]':
        """Gets the projects of this V1GlobalSearchResponse.  # noqa: E501


        :return: The projects of this V1GlobalSearchResponse.  # noqa: E501
        :rtype: list[V1SearchResourceHit]
        """
        return self._projects

    @projects.setter
    def projects(self, projects: 'list[V1SearchResourceHit]'):
        """Sets the projects of this V1GlobalSearchResponse.


        :param projects: The projects of this V1GlobalSearchResponse.  # noqa: E501
        :type: list[V1SearchResourceHit]
        """

        self._projects = projects

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1GlobalSearchResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1GlobalSearchResponse') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1GlobalSearchResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1GlobalSearchResponse') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
