# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1GpuFitness(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bdf': 'str',
        'fabric_collection_state': 'str',
        'fabric_state': 'str',
        'fabric_status': 'str',
        'vbios': 'str',
        'vbios_state': 'str'
    }

    attribute_map = {
        'bdf': 'bdf',
        'fabric_collection_state': 'fabricCollectionState',
        'fabric_state': 'fabricState',
        'fabric_status': 'fabricStatus',
        'vbios': 'vbios',
        'vbios_state': 'vbiosState'
    }

    def __init__(self, bdf: 'str' =None, fabric_collection_state: 'str' =None, fabric_state: 'str' =None, fabric_status: 'str' =None, vbios: 'str' =None, vbios_state: 'str' =None):  # noqa: E501
        """V1GpuFitness - a model defined in Swagger"""  # noqa: E501
        self._bdf = None
        self._fabric_collection_state = None
        self._fabric_state = None
        self._fabric_status = None
        self._vbios = None
        self._vbios_state = None
        self.discriminator = None
        if bdf is not None:
            self.bdf = bdf
        if fabric_collection_state is not None:
            self.fabric_collection_state = fabric_collection_state
        if fabric_state is not None:
            self.fabric_state = fabric_state
        if fabric_status is not None:
            self.fabric_status = fabric_status
        if vbios is not None:
            self.vbios = vbios
        if vbios_state is not None:
            self.vbios_state = vbios_state

    @property
    def bdf(self) -> 'str':
        """Gets the bdf of this V1GpuFitness.  # noqa: E501


        :return: The bdf of this V1GpuFitness.  # noqa: E501
        :rtype: str
        """
        return self._bdf

    @bdf.setter
    def bdf(self, bdf: 'str'):
        """Sets the bdf of this V1GpuFitness.


        :param bdf: The bdf of this V1GpuFitness.  # noqa: E501
        :type: str
        """

        self._bdf = bdf

    @property
    def fabric_collection_state(self) -> 'str':
        """Gets the fabric_collection_state of this V1GpuFitness.  # noqa: E501


        :return: The fabric_collection_state of this V1GpuFitness.  # noqa: E501
        :rtype: str
        """
        return self._fabric_collection_state

    @fabric_collection_state.setter
    def fabric_collection_state(self, fabric_collection_state: 'str'):
        """Sets the fabric_collection_state of this V1GpuFitness.


        :param fabric_collection_state: The fabric_collection_state of this V1GpuFitness.  # noqa: E501
        :type: str
        """

        self._fabric_collection_state = fabric_collection_state

    @property
    def fabric_state(self) -> 'str':
        """Gets the fabric_state of this V1GpuFitness.  # noqa: E501

        Raw nvidia-smi Fabric block values, e.g. \"Completed\" / \"Success\".  # noqa: E501

        :return: The fabric_state of this V1GpuFitness.  # noqa: E501
        :rtype: str
        """
        return self._fabric_state

    @fabric_state.setter
    def fabric_state(self, fabric_state: 'str'):
        """Sets the fabric_state of this V1GpuFitness.

        Raw nvidia-smi Fabric block values, e.g. \"Completed\" / \"Success\".  # noqa: E501

        :param fabric_state: The fabric_state of this V1GpuFitness.  # noqa: E501
        :type: str
        """

        self._fabric_state = fabric_state

    @property
    def fabric_status(self) -> 'str':
        """Gets the fabric_status of this V1GpuFitness.  # noqa: E501


        :return: The fabric_status of this V1GpuFitness.  # noqa: E501
        :rtype: str
        """
        return self._fabric_status

    @fabric_status.setter
    def fabric_status(self, fabric_status: 'str'):
        """Sets the fabric_status of this V1GpuFitness.


        :param fabric_status: The fabric_status of this V1GpuFitness.  # noqa: E501
        :type: str
        """

        self._fabric_status = fabric_status

    @property
    def vbios(self) -> 'str':
        """Gets the vbios of this V1GpuFitness.  # noqa: E501


        :return: The vbios of this V1GpuFitness.  # noqa: E501
        :rtype: str
        """
        return self._vbios

    @vbios.setter
    def vbios(self, vbios: 'str'):
        """Sets the vbios of this V1GpuFitness.


        :param vbios: The vbios of this V1GpuFitness.  # noqa: E501
        :type: str
        """

        self._vbios = vbios

    @property
    def vbios_state(self) -> 'str':
        """Gets the vbios_state of this V1GpuFitness.  # noqa: E501


        :return: The vbios_state of this V1GpuFitness.  # noqa: E501
        :rtype: str
        """
        return self._vbios_state

    @vbios_state.setter
    def vbios_state(self, vbios_state: 'str'):
        """Sets the vbios_state of this V1GpuFitness.


        :param vbios_state: The vbios_state of this V1GpuFitness.  # noqa: E501
        :type: str
        """

        self._vbios_state = vbios_state

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1GpuFitness, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1GpuFitness') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1GpuFitness):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1GpuFitness') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
