# coding: utf-8
# This file is vendored.
# Do not edit it directly; changes will be overwritten.
# Make changes in the internal upstream repository instead.


"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1GPUCreateHostCrash(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'blocked': 'bool',
        'consecutive': 'int',
        'fingerprint': 'str',
        'kind': 'str',
        'pci_device': 'str',
        'probe': 'bool',
        'reason': 'str'
    }

    attribute_map = {
        'blocked': 'blocked',
        'consecutive': 'consecutive',
        'fingerprint': 'fingerprint',
        'kind': 'kind',
        'pci_device': 'pciDevice',
        'probe': 'probe',
        'reason': 'reason'
    }

    def __init__(self, blocked: 'bool' =None, consecutive: 'int' =None, fingerprint: 'str' =None, kind: 'str' =None, pci_device: 'str' =None, probe: 'bool' =None, reason: 'str' =None):  # noqa: E501
        """V1GPUCreateHostCrash - a model defined in Swagger"""  # noqa: E501
        self._blocked = None
        self._consecutive = None
        self._fingerprint = None
        self._kind = None
        self._pci_device = None
        self._probe = None
        self._reason = None
        self.discriminator = None
        if blocked is not None:
            self.blocked = blocked
        if consecutive is not None:
            self.consecutive = consecutive
        if fingerprint is not None:
            self.fingerprint = fingerprint
        if kind is not None:
            self.kind = kind
        if pci_device is not None:
            self.pci_device = pci_device
        if probe is not None:
            self.probe = probe
        if reason is not None:
            self.reason = reason

    @property
    def blocked(self) -> 'bool':
        """Gets the blocked of this V1GPUCreateHostCrash.  # noqa: E501


        :return: The blocked of this V1GPUCreateHostCrash.  # noqa: E501
        :rtype: bool
        """
        return self._blocked

    @blocked.setter
    def blocked(self, blocked: 'bool'):
        """Sets the blocked of this V1GPUCreateHostCrash.


        :param blocked: The blocked of this V1GPUCreateHostCrash.  # noqa: E501
        :type: bool
        """

        self._blocked = blocked

    @property
    def consecutive(self) -> 'int':
        """Gets the consecutive of this V1GPUCreateHostCrash.  # noqa: E501


        :return: The consecutive of this V1GPUCreateHostCrash.  # noqa: E501
        :rtype: int
        """
        return self._consecutive

    @consecutive.setter
    def consecutive(self, consecutive: 'int'):
        """Sets the consecutive of this V1GPUCreateHostCrash.


        :param consecutive: The consecutive of this V1GPUCreateHostCrash.  # noqa: E501
        :type: int
        """

        self._consecutive = consecutive

    @property
    def fingerprint(self) -> 'str':
        """Gets the fingerprint of this V1GPUCreateHostCrash.  # noqa: E501


        :return: The fingerprint of this V1GPUCreateHostCrash.  # noqa: E501
        :rtype: str
        """
        return self._fingerprint

    @fingerprint.setter
    def fingerprint(self, fingerprint: 'str'):
        """Sets the fingerprint of this V1GPUCreateHostCrash.


        :param fingerprint: The fingerprint of this V1GPUCreateHostCrash.  # noqa: E501
        :type: str
        """

        self._fingerprint = fingerprint

    @property
    def kind(self) -> 'str':
        """Gets the kind of this V1GPUCreateHostCrash.  # noqa: E501

        ghes-pcie or vfio-hda.  # noqa: E501

        :return: The kind of this V1GPUCreateHostCrash.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: 'str'):
        """Sets the kind of this V1GPUCreateHostCrash.

        ghes-pcie or vfio-hda.  # noqa: E501

        :param kind: The kind of this V1GPUCreateHostCrash.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def pci_device(self) -> 'str':
        """Gets the pci_device of this V1GPUCreateHostCrash.  # noqa: E501


        :return: The pci_device of this V1GPUCreateHostCrash.  # noqa: E501
        :rtype: str
        """
        return self._pci_device

    @pci_device.setter
    def pci_device(self, pci_device: 'str'):
        """Sets the pci_device of this V1GPUCreateHostCrash.


        :param pci_device: The pci_device of this V1GPUCreateHostCrash.  # noqa: E501
        :type: str
        """

        self._pci_device = pci_device

    @property
    def probe(self) -> 'bool':
        """Gets the probe of this V1GPUCreateHostCrash.  # noqa: E501


        :return: The probe of this V1GPUCreateHostCrash.  # noqa: E501
        :rtype: bool
        """
        return self._probe

    @probe.setter
    def probe(self, probe: 'bool'):
        """Sets the probe of this V1GPUCreateHostCrash.


        :param probe: The probe of this V1GPUCreateHostCrash.  # noqa: E501
        :type: bool
        """

        self._probe = probe

    @property
    def reason(self) -> 'str':
        """Gets the reason of this V1GPUCreateHostCrash.  # noqa: E501


        :return: The reason of this V1GPUCreateHostCrash.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: 'str'):
        """Sets the reason of this V1GPUCreateHostCrash.


        :param reason: The reason of this V1GPUCreateHostCrash.  # noqa: E501
        :type: str
        """

        self._reason = reason

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1GPUCreateHostCrash, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1GPUCreateHostCrash') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1GPUCreateHostCrash):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1GPUCreateHostCrash') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
