# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1GetSandboxSnapshotBlobUploadUrlsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'existing_digests': 'list[str]',
        'upload_urls': 'list[V1SandboxSnapshotBlobUploadUrl]'
    }

    attribute_map = {
        'existing_digests': 'existingDigests',
        'upload_urls': 'uploadUrls'
    }

    def __init__(self, existing_digests: 'list[str]' =None, upload_urls: 'list[V1SandboxSnapshotBlobUploadUrl]' =None):  # noqa: E501
        """V1GetSandboxSnapshotBlobUploadUrlsResponse - a model defined in Swagger"""  # noqa: E501
        self._existing_digests = None
        self._upload_urls = None
        self.discriminator = None
        if existing_digests is not None:
            self.existing_digests = existing_digests
        if upload_urls is not None:
            self.upload_urls = upload_urls

    @property
    def existing_digests(self) -> 'list[str]':
        """Gets the existing_digests of this V1GetSandboxSnapshotBlobUploadUrlsResponse.  # noqa: E501

        sha256 digests already present in the cluster bucket. Caller skips upload for these.  # noqa: E501

        :return: The existing_digests of this V1GetSandboxSnapshotBlobUploadUrlsResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._existing_digests

    @existing_digests.setter
    def existing_digests(self, existing_digests: 'list[str]'):
        """Sets the existing_digests of this V1GetSandboxSnapshotBlobUploadUrlsResponse.

        sha256 digests already present in the cluster bucket. Caller skips upload for these.  # noqa: E501

        :param existing_digests: The existing_digests of this V1GetSandboxSnapshotBlobUploadUrlsResponse.  # noqa: E501
        :type: list[str]
        """

        self._existing_digests = existing_digests

    @property
    def upload_urls(self) -> 'list[V1SandboxSnapshotBlobUploadUrl]':
        """Gets the upload_urls of this V1GetSandboxSnapshotBlobUploadUrlsResponse.  # noqa: E501

        Presigned PUT URL per blob the caller still needs to upload.  # noqa: E501

        :return: The upload_urls of this V1GetSandboxSnapshotBlobUploadUrlsResponse.  # noqa: E501
        :rtype: list[V1SandboxSnapshotBlobUploadUrl]
        """
        return self._upload_urls

    @upload_urls.setter
    def upload_urls(self, upload_urls: 'list[V1SandboxSnapshotBlobUploadUrl]'):
        """Sets the upload_urls of this V1GetSandboxSnapshotBlobUploadUrlsResponse.

        Presigned PUT URL per blob the caller still needs to upload.  # noqa: E501

        :param upload_urls: The upload_urls of this V1GetSandboxSnapshotBlobUploadUrlsResponse.  # noqa: E501
        :type: list[V1SandboxSnapshotBlobUploadUrl]
        """

        self._upload_urls = upload_urls

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1GetSandboxSnapshotBlobUploadUrlsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1GetSandboxSnapshotBlobUploadUrlsResponse') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1GetSandboxSnapshotBlobUploadUrlsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1GetSandboxSnapshotBlobUploadUrlsResponse') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
