# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1HugepagePool(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'free': 'str',
        'free_bytes': 'str',
        'in_use': 'str',
        'per_node': 'list[V1NUMAHugepages]',
        'reserved_bytes': 'str',
        'size_bytes': 'str',
        'total': 'str'
    }

    attribute_map = {
        'free': 'free',
        'free_bytes': 'freeBytes',
        'in_use': 'inUse',
        'per_node': 'perNode',
        'reserved_bytes': 'reservedBytes',
        'size_bytes': 'sizeBytes',
        'total': 'total'
    }

    def __init__(self, free: 'str' =None, free_bytes: 'str' =None, in_use: 'str' =None, per_node: 'list[V1NUMAHugepages]' =None, reserved_bytes: 'str' =None, size_bytes: 'str' =None, total: 'str' =None):  # noqa: E501
        """V1HugepagePool - a model defined in Swagger"""  # noqa: E501
        self._free = None
        self._free_bytes = None
        self._in_use = None
        self._per_node = None
        self._reserved_bytes = None
        self._size_bytes = None
        self._total = None
        self.discriminator = None
        if free is not None:
            self.free = free
        if free_bytes is not None:
            self.free_bytes = free_bytes
        if in_use is not None:
            self.in_use = in_use
        if per_node is not None:
            self.per_node = per_node
        if reserved_bytes is not None:
            self.reserved_bytes = reserved_bytes
        if size_bytes is not None:
            self.size_bytes = size_bytes
        if total is not None:
            self.total = total

    @property
    def free(self) -> 'str':
        """Gets the free of this V1HugepagePool.  # noqa: E501


        :return: The free of this V1HugepagePool.  # noqa: E501
        :rtype: str
        """
        return self._free

    @free.setter
    def free(self, free: 'str'):
        """Sets the free of this V1HugepagePool.


        :param free: The free of this V1HugepagePool.  # noqa: E501
        :type: str
        """

        self._free = free

    @property
    def free_bytes(self) -> 'str':
        """Gets the free_bytes of this V1HugepagePool.  # noqa: E501


        :return: The free_bytes of this V1HugepagePool.  # noqa: E501
        :rtype: str
        """
        return self._free_bytes

    @free_bytes.setter
    def free_bytes(self, free_bytes: 'str'):
        """Sets the free_bytes of this V1HugepagePool.


        :param free_bytes: The free_bytes of this V1HugepagePool.  # noqa: E501
        :type: str
        """

        self._free_bytes = free_bytes

    @property
    def in_use(self) -> 'str':
        """Gets the in_use of this V1HugepagePool.  # noqa: E501


        :return: The in_use of this V1HugepagePool.  # noqa: E501
        :rtype: str
        """
        return self._in_use

    @in_use.setter
    def in_use(self, in_use: 'str'):
        """Sets the in_use of this V1HugepagePool.


        :param in_use: The in_use of this V1HugepagePool.  # noqa: E501
        :type: str
        """

        self._in_use = in_use

    @property
    def per_node(self) -> 'list[V1NUMAHugepages]':
        """Gets the per_node of this V1HugepagePool.  # noqa: E501


        :return: The per_node of this V1HugepagePool.  # noqa: E501
        :rtype: list[V1NUMAHugepages]
        """
        return self._per_node

    @per_node.setter
    def per_node(self, per_node: 'list[V1NUMAHugepages]'):
        """Sets the per_node of this V1HugepagePool.


        :param per_node: The per_node of this V1HugepagePool.  # noqa: E501
        :type: list[V1NUMAHugepages]
        """

        self._per_node = per_node

    @property
    def reserved_bytes(self) -> 'str':
        """Gets the reserved_bytes of this V1HugepagePool.  # noqa: E501


        :return: The reserved_bytes of this V1HugepagePool.  # noqa: E501
        :rtype: str
        """
        return self._reserved_bytes

    @reserved_bytes.setter
    def reserved_bytes(self, reserved_bytes: 'str'):
        """Sets the reserved_bytes of this V1HugepagePool.


        :param reserved_bytes: The reserved_bytes of this V1HugepagePool.  # noqa: E501
        :type: str
        """

        self._reserved_bytes = reserved_bytes

    @property
    def size_bytes(self) -> 'str':
        """Gets the size_bytes of this V1HugepagePool.  # noqa: E501


        :return: The size_bytes of this V1HugepagePool.  # noqa: E501
        :rtype: str
        """
        return self._size_bytes

    @size_bytes.setter
    def size_bytes(self, size_bytes: 'str'):
        """Sets the size_bytes of this V1HugepagePool.


        :param size_bytes: The size_bytes of this V1HugepagePool.  # noqa: E501
        :type: str
        """

        self._size_bytes = size_bytes

    @property
    def total(self) -> 'str':
        """Gets the total of this V1HugepagePool.  # noqa: E501


        :return: The total of this V1HugepagePool.  # noqa: E501
        :rtype: str
        """
        return self._total

    @total.setter
    def total(self, total: 'str'):
        """Sets the total of this V1HugepagePool.


        :param total: The total of this V1HugepagePool.  # noqa: E501
        :type: str
        """

        self._total = total

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1HugepagePool, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1HugepagePool') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1HugepagePool):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1HugepagePool') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
