# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1KaiSchedulerConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'priority_class_name': 'str',
        'queue': 'str',
        'scheduler_name': 'str'
    }

    attribute_map = {
        'priority_class_name': 'priorityClassName',
        'queue': 'queue',
        'scheduler_name': 'schedulerName'
    }

    def __init__(self, priority_class_name: 'str' =None, queue: 'str' =None, scheduler_name: 'str' =None):  # noqa: E501
        """V1KaiSchedulerConfig - a model defined in Swagger"""  # noqa: E501
        self._priority_class_name = None
        self._queue = None
        self._scheduler_name = None
        self.discriminator = None
        if priority_class_name is not None:
            self.priority_class_name = priority_class_name
        if queue is not None:
            self.queue = queue
        if scheduler_name is not None:
            self.scheduler_name = scheduler_name

    @property
    def priority_class_name(self) -> 'str':
        """Gets the priority_class_name of this V1KaiSchedulerConfig.  # noqa: E501


        :return: The priority_class_name of this V1KaiSchedulerConfig.  # noqa: E501
        :rtype: str
        """
        return self._priority_class_name

    @priority_class_name.setter
    def priority_class_name(self, priority_class_name: 'str'):
        """Sets the priority_class_name of this V1KaiSchedulerConfig.


        :param priority_class_name: The priority_class_name of this V1KaiSchedulerConfig.  # noqa: E501
        :type: str
        """

        self._priority_class_name = priority_class_name

    @property
    def queue(self) -> 'str':
        """Gets the queue of this V1KaiSchedulerConfig.  # noqa: E501


        :return: The queue of this V1KaiSchedulerConfig.  # noqa: E501
        :rtype: str
        """
        return self._queue

    @queue.setter
    def queue(self, queue: 'str'):
        """Sets the queue of this V1KaiSchedulerConfig.


        :param queue: The queue of this V1KaiSchedulerConfig.  # noqa: E501
        :type: str
        """

        self._queue = queue

    @property
    def scheduler_name(self) -> 'str':
        """Gets the scheduler_name of this V1KaiSchedulerConfig.  # noqa: E501


        :return: The scheduler_name of this V1KaiSchedulerConfig.  # noqa: E501
        :rtype: str
        """
        return self._scheduler_name

    @scheduler_name.setter
    def scheduler_name(self, scheduler_name: 'str'):
        """Sets the scheduler_name of this V1KaiSchedulerConfig.


        :param scheduler_name: The scheduler_name of this V1KaiSchedulerConfig.  # noqa: E501
        :type: str
        """

        self._scheduler_name = scheduler_name

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1KaiSchedulerConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1KaiSchedulerConfig') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1KaiSchedulerConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1KaiSchedulerConfig') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
