# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1MachineV1Status(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cordoned': 'MachineV1StatusResourceGroup',
        'total': 'MachineV1StatusResourceGroup',
        'unreachable': 'MachineV1StatusResourceGroup',
        'used': 'MachineV1StatusResourceGroup'
    }

    attribute_map = {
        'cordoned': 'cordoned',
        'total': 'total',
        'unreachable': 'unreachable',
        'used': 'used'
    }

    def __init__(self, cordoned: 'MachineV1StatusResourceGroup' =None, total: 'MachineV1StatusResourceGroup' =None, unreachable: 'MachineV1StatusResourceGroup' =None, used: 'MachineV1StatusResourceGroup' =None):  # noqa: E501
        """V1MachineV1Status - a model defined in Swagger"""  # noqa: E501
        self._cordoned = None
        self._total = None
        self._unreachable = None
        self._used = None
        self.discriminator = None
        if cordoned is not None:
            self.cordoned = cordoned
        if total is not None:
            self.total = total
        if unreachable is not None:
            self.unreachable = unreachable
        if used is not None:
            self.used = used

    @property
    def cordoned(self) -> 'MachineV1StatusResourceGroup':
        """Gets the cordoned of this V1MachineV1Status.  # noqa: E501


        :return: The cordoned of this V1MachineV1Status.  # noqa: E501
        :rtype: MachineV1StatusResourceGroup
        """
        return self._cordoned

    @cordoned.setter
    def cordoned(self, cordoned: 'MachineV1StatusResourceGroup'):
        """Sets the cordoned of this V1MachineV1Status.


        :param cordoned: The cordoned of this V1MachineV1Status.  # noqa: E501
        :type: MachineV1StatusResourceGroup
        """

        self._cordoned = cordoned

    @property
    def total(self) -> 'MachineV1StatusResourceGroup':
        """Gets the total of this V1MachineV1Status.  # noqa: E501


        :return: The total of this V1MachineV1Status.  # noqa: E501
        :rtype: MachineV1StatusResourceGroup
        """
        return self._total

    @total.setter
    def total(self, total: 'MachineV1StatusResourceGroup'):
        """Sets the total of this V1MachineV1Status.


        :param total: The total of this V1MachineV1Status.  # noqa: E501
        :type: MachineV1StatusResourceGroup
        """

        self._total = total

    @property
    def unreachable(self) -> 'MachineV1StatusResourceGroup':
        """Gets the unreachable of this V1MachineV1Status.  # noqa: E501


        :return: The unreachable of this V1MachineV1Status.  # noqa: E501
        :rtype: MachineV1StatusResourceGroup
        """
        return self._unreachable

    @unreachable.setter
    def unreachable(self, unreachable: 'MachineV1StatusResourceGroup'):
        """Sets the unreachable of this V1MachineV1Status.


        :param unreachable: The unreachable of this V1MachineV1Status.  # noqa: E501
        :type: MachineV1StatusResourceGroup
        """

        self._unreachable = unreachable

    @property
    def used(self) -> 'MachineV1StatusResourceGroup':
        """Gets the used of this V1MachineV1Status.  # noqa: E501


        :return: The used of this V1MachineV1Status.  # noqa: E501
        :rtype: MachineV1StatusResourceGroup
        """
        return self._used

    @used.setter
    def used(self, used: 'MachineV1StatusResourceGroup'):
        """Sets the used of this V1MachineV1Status.


        :param used: The used of this V1MachineV1Status.  # noqa: E501
        :type: MachineV1StatusResourceGroup
        """

        self._used = used

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1MachineV1Status, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1MachineV1Status') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1MachineV1Status):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1MachineV1Status') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
