# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1MachineHealth(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'checked_at': 'datetime',
        'errors': 'list[str]',
        'host': 'V1HostHealth',
        'sweep_duration': 'str',
        'vms': 'list[V1VMHealth]'
    }

    attribute_map = {
        'checked_at': 'checkedAt',
        'errors': 'errors',
        'host': 'host',
        'sweep_duration': 'sweepDuration',
        'vms': 'vms'
    }

    def __init__(self, checked_at: 'datetime' =None, errors: 'list[str]' =None, host: 'V1HostHealth' =None, sweep_duration: 'str' =None, vms: 'list[V1VMHealth]' =None):  # noqa: E501
        """V1MachineHealth - a model defined in Swagger"""  # noqa: E501
        self._checked_at = None
        self._errors = None
        self._host = None
        self._sweep_duration = None
        self._vms = None
        self.discriminator = None
        if checked_at is not None:
            self.checked_at = checked_at
        if errors is not None:
            self.errors = errors
        if host is not None:
            self.host = host
        if sweep_duration is not None:
            self.sweep_duration = sweep_duration
        if vms is not None:
            self.vms = vms

    @property
    def checked_at(self) -> 'datetime':
        """Gets the checked_at of this V1MachineHealth.  # noqa: E501

        When this snapshot was collected on the agent side.  # noqa: E501

        :return: The checked_at of this V1MachineHealth.  # noqa: E501
        :rtype: datetime
        """
        return self._checked_at

    @checked_at.setter
    def checked_at(self, checked_at: 'datetime'):
        """Sets the checked_at of this V1MachineHealth.

        When this snapshot was collected on the agent side.  # noqa: E501

        :param checked_at: The checked_at of this V1MachineHealth.  # noqa: E501
        :type: datetime
        """

        self._checked_at = checked_at

    @property
    def errors(self) -> 'list[str]':
        """Gets the errors of this V1MachineHealth.  # noqa: E501

        Errors encountered during the sweep itself (e.g. \"list instances failed\"). These are sweep-level, not host- or VM-level.  # noqa: E501

        :return: The errors of this V1MachineHealth.  # noqa: E501
        :rtype: list[str]
        """
        return self._errors

    @errors.setter
    def errors(self, errors: 'list[str]'):
        """Sets the errors of this V1MachineHealth.

        Errors encountered during the sweep itself (e.g. \"list instances failed\"). These are sweep-level, not host- or VM-level.  # noqa: E501

        :param errors: The errors of this V1MachineHealth.  # noqa: E501
        :type: list[str]
        """

        self._errors = errors

    @property
    def host(self) -> 'V1HostHealth':
        """Gets the host of this V1MachineHealth.  # noqa: E501


        :return: The host of this V1MachineHealth.  # noqa: E501
        :rtype: V1HostHealth
        """
        return self._host

    @host.setter
    def host(self, host: 'V1HostHealth'):
        """Sets the host of this V1MachineHealth.


        :param host: The host of this V1MachineHealth.  # noqa: E501
        :type: V1HostHealth
        """

        self._host = host

    @property
    def sweep_duration(self) -> 'str':
        """Gets the sweep_duration of this V1MachineHealth.  # noqa: E501

        How long the sweep took. String form (e.g. \"1.23s\") to match the Go health state field.  # noqa: E501

        :return: The sweep_duration of this V1MachineHealth.  # noqa: E501
        :rtype: str
        """
        return self._sweep_duration

    @sweep_duration.setter
    def sweep_duration(self, sweep_duration: 'str'):
        """Sets the sweep_duration of this V1MachineHealth.

        How long the sweep took. String form (e.g. \"1.23s\") to match the Go health state field.  # noqa: E501

        :param sweep_duration: The sweep_duration of this V1MachineHealth.  # noqa: E501
        :type: str
        """

        self._sweep_duration = sweep_duration

    @property
    def vms(self) -> 'list[V1VMHealth]':
        """Gets the vms of this V1MachineHealth.  # noqa: E501


        :return: The vms of this V1MachineHealth.  # noqa: E501
        :rtype: list[V1VMHealth]
        """
        return self._vms

    @vms.setter
    def vms(self, vms: 'list[V1VMHealth]'):
        """Sets the vms of this V1MachineHealth.


        :param vms: The vms of this V1MachineHealth.  # noqa: E501
        :type: list[V1VMHealth]
        """

        self._vms = vms

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1MachineHealth, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1MachineHealth') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1MachineHealth):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1MachineHealth') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
