# coding: utf-8
# This file is vendored.
# Do not edit it directly; changes will be overwritten.
# Make changes in the internal upstream repository instead.


"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1MachineVPNServicesStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'running': 'bool',
        'units': 'list[V1MachineVPNServiceUnit]'
    }

    attribute_map = {
        'running': 'running',
        'units': 'units'
    }

    def __init__(self, running: 'bool' =None, units: 'list[V1MachineVPNServiceUnit]' =None):  # noqa: E501
        """V1MachineVPNServicesStatus - a model defined in Swagger"""  # noqa: E501
        self._running = None
        self._units = None
        self.discriminator = None
        if running is not None:
            self.running = running
        if units is not None:
            self.units = units

    @property
    def running(self) -> 'bool':
        """Gets the running of this V1MachineVPNServicesStatus.  # noqa: E501

        True only when every unit is active.  # noqa: E501

        :return: The running of this V1MachineVPNServicesStatus.  # noqa: E501
        :rtype: bool
        """
        return self._running

    @running.setter
    def running(self, running: 'bool'):
        """Sets the running of this V1MachineVPNServicesStatus.

        True only when every unit is active.  # noqa: E501

        :param running: The running of this V1MachineVPNServicesStatus.  # noqa: E501
        :type: bool
        """

        self._running = running

    @property
    def units(self) -> 'list[V1MachineVPNServiceUnit]':
        """Gets the units of this V1MachineVPNServicesStatus.  # noqa: E501


        :return: The units of this V1MachineVPNServicesStatus.  # noqa: E501
        :rtype: list[V1MachineVPNServiceUnit]
        """
        return self._units

    @units.setter
    def units(self, units: 'list[V1MachineVPNServiceUnit]'):
        """Sets the units of this V1MachineVPNServicesStatus.


        :param units: The units of this V1MachineVPNServicesStatus.  # noqa: E501
        :type: list[V1MachineVPNServiceUnit]
        """

        self._units = units

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1MachineVPNServicesStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1MachineVPNServicesStatus') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1MachineVPNServicesStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1MachineVPNServicesStatus') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
