# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1MachineBootstrap(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cloud_init': 'str',
        'machine_image': 'str',
        'ssh_pub_keys': 'list[str]'
    }

    attribute_map = {
        'cloud_init': 'cloudInit',
        'machine_image': 'machineImage',
        'ssh_pub_keys': 'sshPubKeys'
    }

    def __init__(self, cloud_init: 'str' =None, machine_image: 'str' =None, ssh_pub_keys: 'list[str]' =None):  # noqa: E501
        """V1MachineBootstrap - a model defined in Swagger"""  # noqa: E501
        self._cloud_init = None
        self._machine_image = None
        self._ssh_pub_keys = None
        self.discriminator = None
        if cloud_init is not None:
            self.cloud_init = cloud_init
        if machine_image is not None:
            self.machine_image = machine_image
        if ssh_pub_keys is not None:
            self.ssh_pub_keys = ssh_pub_keys

    @property
    def cloud_init(self) -> 'str':
        """Gets the cloud_init of this V1MachineBootstrap.  # noqa: E501


        :return: The cloud_init of this V1MachineBootstrap.  # noqa: E501
        :rtype: str
        """
        return self._cloud_init

    @cloud_init.setter
    def cloud_init(self, cloud_init: 'str'):
        """Sets the cloud_init of this V1MachineBootstrap.


        :param cloud_init: The cloud_init of this V1MachineBootstrap.  # noqa: E501
        :type: str
        """

        self._cloud_init = cloud_init

    @property
    def machine_image(self) -> 'str':
        """Gets the machine_image of this V1MachineBootstrap.  # noqa: E501


        :return: The machine_image of this V1MachineBootstrap.  # noqa: E501
        :rtype: str
        """
        return self._machine_image

    @machine_image.setter
    def machine_image(self, machine_image: 'str'):
        """Sets the machine_image of this V1MachineBootstrap.


        :param machine_image: The machine_image of this V1MachineBootstrap.  # noqa: E501
        :type: str
        """

        self._machine_image = machine_image

    @property
    def ssh_pub_keys(self) -> 'list[str]':
        """Gets the ssh_pub_keys of this V1MachineBootstrap.  # noqa: E501


        :return: The ssh_pub_keys of this V1MachineBootstrap.  # noqa: E501
        :rtype: list[str]
        """
        return self._ssh_pub_keys

    @ssh_pub_keys.setter
    def ssh_pub_keys(self, ssh_pub_keys: 'list[str]'):
        """Sets the ssh_pub_keys of this V1MachineBootstrap.


        :param ssh_pub_keys: The ssh_pub_keys of this V1MachineBootstrap.  # noqa: E501
        :type: list[str]
        """

        self._ssh_pub_keys = ssh_pub_keys

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1MachineBootstrap, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1MachineBootstrap') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1MachineBootstrap):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1MachineBootstrap') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
