# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1NVLinkInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'crc_errors': 'str',
        'link_num': 'int',
        'recovery_errors': 'str',
        'replay_errors': 'str',
        'speed_gbps': 'float',
        'state': 'str'
    }

    attribute_map = {
        'crc_errors': 'crcErrors',
        'link_num': 'linkNum',
        'recovery_errors': 'recoveryErrors',
        'replay_errors': 'replayErrors',
        'speed_gbps': 'speedGbps',
        'state': 'state'
    }

    def __init__(self, crc_errors: 'str' =None, link_num: 'int' =None, recovery_errors: 'str' =None, replay_errors: 'str' =None, speed_gbps: 'float' =None, state: 'str' =None):  # noqa: E501
        """V1NVLinkInfo - a model defined in Swagger"""  # noqa: E501
        self._crc_errors = None
        self._link_num = None
        self._recovery_errors = None
        self._replay_errors = None
        self._speed_gbps = None
        self._state = None
        self.discriminator = None
        if crc_errors is not None:
            self.crc_errors = crc_errors
        if link_num is not None:
            self.link_num = link_num
        if recovery_errors is not None:
            self.recovery_errors = recovery_errors
        if replay_errors is not None:
            self.replay_errors = replay_errors
        if speed_gbps is not None:
            self.speed_gbps = speed_gbps
        if state is not None:
            self.state = state

    @property
    def crc_errors(self) -> 'str':
        """Gets the crc_errors of this V1NVLinkInfo.  # noqa: E501


        :return: The crc_errors of this V1NVLinkInfo.  # noqa: E501
        :rtype: str
        """
        return self._crc_errors

    @crc_errors.setter
    def crc_errors(self, crc_errors: 'str'):
        """Sets the crc_errors of this V1NVLinkInfo.


        :param crc_errors: The crc_errors of this V1NVLinkInfo.  # noqa: E501
        :type: str
        """

        self._crc_errors = crc_errors

    @property
    def link_num(self) -> 'int':
        """Gets the link_num of this V1NVLinkInfo.  # noqa: E501


        :return: The link_num of this V1NVLinkInfo.  # noqa: E501
        :rtype: int
        """
        return self._link_num

    @link_num.setter
    def link_num(self, link_num: 'int'):
        """Sets the link_num of this V1NVLinkInfo.


        :param link_num: The link_num of this V1NVLinkInfo.  # noqa: E501
        :type: int
        """

        self._link_num = link_num

    @property
    def recovery_errors(self) -> 'str':
        """Gets the recovery_errors of this V1NVLinkInfo.  # noqa: E501


        :return: The recovery_errors of this V1NVLinkInfo.  # noqa: E501
        :rtype: str
        """
        return self._recovery_errors

    @recovery_errors.setter
    def recovery_errors(self, recovery_errors: 'str'):
        """Sets the recovery_errors of this V1NVLinkInfo.


        :param recovery_errors: The recovery_errors of this V1NVLinkInfo.  # noqa: E501
        :type: str
        """

        self._recovery_errors = recovery_errors

    @property
    def replay_errors(self) -> 'str':
        """Gets the replay_errors of this V1NVLinkInfo.  # noqa: E501


        :return: The replay_errors of this V1NVLinkInfo.  # noqa: E501
        :rtype: str
        """
        return self._replay_errors

    @replay_errors.setter
    def replay_errors(self, replay_errors: 'str'):
        """Sets the replay_errors of this V1NVLinkInfo.


        :param replay_errors: The replay_errors of this V1NVLinkInfo.  # noqa: E501
        :type: str
        """

        self._replay_errors = replay_errors

    @property
    def speed_gbps(self) -> 'float':
        """Gets the speed_gbps of this V1NVLinkInfo.  # noqa: E501


        :return: The speed_gbps of this V1NVLinkInfo.  # noqa: E501
        :rtype: float
        """
        return self._speed_gbps

    @speed_gbps.setter
    def speed_gbps(self, speed_gbps: 'float'):
        """Sets the speed_gbps of this V1NVLinkInfo.


        :param speed_gbps: The speed_gbps of this V1NVLinkInfo.  # noqa: E501
        :type: float
        """

        self._speed_gbps = speed_gbps

    @property
    def state(self) -> 'str':
        """Gets the state of this V1NVLinkInfo.  # noqa: E501


        :return: The state of this V1NVLinkInfo.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: 'str'):
        """Sets the state of this V1NVLinkInfo.


        :param state: The state of this V1NVLinkInfo.  # noqa: E501
        :type: str
        """

        self._state = state

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1NVLinkInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1NVLinkInfo') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1NVLinkInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1NVLinkInfo') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
