# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1NICFitness(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ats_ctl': 'str',
        'ats_enabled': 'bool',
        'bdf': 'str',
        'collection_state': 'str',
        'device_name': 'str',
        'role': 'str'
    }

    attribute_map = {
        'ats_ctl': 'atsCtl',
        'ats_enabled': 'atsEnabled',
        'bdf': 'bdf',
        'collection_state': 'collectionState',
        'device_name': 'deviceName',
        'role': 'role'
    }

    def __init__(self, ats_ctl: 'str' =None, ats_enabled: 'bool' =None, bdf: 'str' =None, collection_state: 'str' =None, device_name: 'str' =None, role: 'str' =None):  # noqa: E501
        """V1NICFitness - a model defined in Swagger"""  # noqa: E501
        self._ats_ctl = None
        self._ats_enabled = None
        self._bdf = None
        self._collection_state = None
        self._device_name = None
        self._role = None
        self.discriminator = None
        if ats_ctl is not None:
            self.ats_ctl = ats_ctl
        if ats_enabled is not None:
            self.ats_enabled = ats_enabled
        if bdf is not None:
            self.bdf = bdf
        if collection_state is not None:
            self.collection_state = collection_state
        if device_name is not None:
            self.device_name = device_name
        if role is not None:
            self.role = role

    @property
    def ats_ctl(self) -> 'str':
        """Gets the ats_ctl of this V1NICFitness.  # noqa: E501


        :return: The ats_ctl of this V1NICFitness.  # noqa: E501
        :rtype: str
        """
        return self._ats_ctl

    @ats_ctl.setter
    def ats_ctl(self, ats_ctl: 'str'):
        """Sets the ats_ctl of this V1NICFitness.


        :param ats_ctl: The ats_ctl of this V1NICFitness.  # noqa: E501
        :type: str
        """

        self._ats_ctl = ats_ctl

    @property
    def ats_enabled(self) -> 'bool':
        """Gets the ats_enabled of this V1NICFitness.  # noqa: E501


        :return: The ats_enabled of this V1NICFitness.  # noqa: E501
        :rtype: bool
        """
        return self._ats_enabled

    @ats_enabled.setter
    def ats_enabled(self, ats_enabled: 'bool'):
        """Sets the ats_enabled of this V1NICFitness.


        :param ats_enabled: The ats_enabled of this V1NICFitness.  # noqa: E501
        :type: bool
        """

        self._ats_enabled = ats_enabled

    @property
    def bdf(self) -> 'str':
        """Gets the bdf of this V1NICFitness.  # noqa: E501


        :return: The bdf of this V1NICFitness.  # noqa: E501
        :rtype: str
        """
        return self._bdf

    @bdf.setter
    def bdf(self, bdf: 'str'):
        """Sets the bdf of this V1NICFitness.


        :param bdf: The bdf of this V1NICFitness.  # noqa: E501
        :type: str
        """

        self._bdf = bdf

    @property
    def collection_state(self) -> 'str':
        """Gets the collection_state of this V1NICFitness.  # noqa: E501


        :return: The collection_state of this V1NICFitness.  # noqa: E501
        :rtype: str
        """
        return self._collection_state

    @collection_state.setter
    def collection_state(self, collection_state: 'str'):
        """Sets the collection_state of this V1NICFitness.


        :param collection_state: The collection_state of this V1NICFitness.  # noqa: E501
        :type: str
        """

        self._collection_state = collection_state

    @property
    def device_name(self) -> 'str':
        """Gets the device_name of this V1NICFitness.  # noqa: E501


        :return: The device_name of this V1NICFitness.  # noqa: E501
        :rtype: str
        """
        return self._device_name

    @device_name.setter
    def device_name(self, device_name: 'str'):
        """Sets the device_name of this V1NICFitness.


        :param device_name: The device_name of this V1NICFitness.  # noqa: E501
        :type: str
        """

        self._device_name = device_name

    @property
    def role(self) -> 'str':
        """Gets the role of this V1NICFitness.  # noqa: E501


        :return: The role of this V1NICFitness.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: 'str'):
        """Sets the role of this V1NICFitness.


        :param role: The role of this V1NICFitness.  # noqa: E501
        :type: str
        """

        self._role = role

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1NICFitness, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1NICFitness') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1NICFitness):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1NICFitness') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
