# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1NVLinkStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gpu_index': 'int',
        'gpu_uuid': 'str',
        'host_pci_addr': 'str',
        'links': 'list[V1NVLinkInfo]',
        'links_active': 'int',
        'links_inactive': 'int',
        'links_total': 'int',
        'total_crc_errors': 'str',
        'total_recovery_errors': 'str',
        'total_replay_errors': 'str'
    }

    attribute_map = {
        'gpu_index': 'gpuIndex',
        'gpu_uuid': 'gpuUuid',
        'host_pci_addr': 'hostPciAddr',
        'links': 'links',
        'links_active': 'linksActive',
        'links_inactive': 'linksInactive',
        'links_total': 'linksTotal',
        'total_crc_errors': 'totalCrcErrors',
        'total_recovery_errors': 'totalRecoveryErrors',
        'total_replay_errors': 'totalReplayErrors'
    }

    def __init__(self, gpu_index: 'int' =None, gpu_uuid: 'str' =None, host_pci_addr: 'str' =None, links: 'list[V1NVLinkInfo]' =None, links_active: 'int' =None, links_inactive: 'int' =None, links_total: 'int' =None, total_crc_errors: 'str' =None, total_recovery_errors: 'str' =None, total_replay_errors: 'str' =None):  # noqa: E501
        """V1NVLinkStatus - a model defined in Swagger"""  # noqa: E501
        self._gpu_index = None
        self._gpu_uuid = None
        self._host_pci_addr = None
        self._links = None
        self._links_active = None
        self._links_inactive = None
        self._links_total = None
        self._total_crc_errors = None
        self._total_recovery_errors = None
        self._total_replay_errors = None
        self.discriminator = None
        if gpu_index is not None:
            self.gpu_index = gpu_index
        if gpu_uuid is not None:
            self.gpu_uuid = gpu_uuid
        if host_pci_addr is not None:
            self.host_pci_addr = host_pci_addr
        if links is not None:
            self.links = links
        if links_active is not None:
            self.links_active = links_active
        if links_inactive is not None:
            self.links_inactive = links_inactive
        if links_total is not None:
            self.links_total = links_total
        if total_crc_errors is not None:
            self.total_crc_errors = total_crc_errors
        if total_recovery_errors is not None:
            self.total_recovery_errors = total_recovery_errors
        if total_replay_errors is not None:
            self.total_replay_errors = total_replay_errors

    @property
    def gpu_index(self) -> 'int':
        """Gets the gpu_index of this V1NVLinkStatus.  # noqa: E501


        :return: The gpu_index of this V1NVLinkStatus.  # noqa: E501
        :rtype: int
        """
        return self._gpu_index

    @gpu_index.setter
    def gpu_index(self, gpu_index: 'int'):
        """Sets the gpu_index of this V1NVLinkStatus.


        :param gpu_index: The gpu_index of this V1NVLinkStatus.  # noqa: E501
        :type: int
        """

        self._gpu_index = gpu_index

    @property
    def gpu_uuid(self) -> 'str':
        """Gets the gpu_uuid of this V1NVLinkStatus.  # noqa: E501


        :return: The gpu_uuid of this V1NVLinkStatus.  # noqa: E501
        :rtype: str
        """
        return self._gpu_uuid

    @gpu_uuid.setter
    def gpu_uuid(self, gpu_uuid: 'str'):
        """Sets the gpu_uuid of this V1NVLinkStatus.


        :param gpu_uuid: The gpu_uuid of this V1NVLinkStatus.  # noqa: E501
        :type: str
        """

        self._gpu_uuid = gpu_uuid

    @property
    def host_pci_addr(self) -> 'str':
        """Gets the host_pci_addr of this V1NVLinkStatus.  # noqa: E501

        Host-side PCI BDF of the physical GPU these NVLinks belong to. See GPUStatus.host_pci_addr.  # noqa: E501

        :return: The host_pci_addr of this V1NVLinkStatus.  # noqa: E501
        :rtype: str
        """
        return self._host_pci_addr

    @host_pci_addr.setter
    def host_pci_addr(self, host_pci_addr: 'str'):
        """Sets the host_pci_addr of this V1NVLinkStatus.

        Host-side PCI BDF of the physical GPU these NVLinks belong to. See GPUStatus.host_pci_addr.  # noqa: E501

        :param host_pci_addr: The host_pci_addr of this V1NVLinkStatus.  # noqa: E501
        :type: str
        """

        self._host_pci_addr = host_pci_addr

    @property
    def links(self) -> 'list[V1NVLinkInfo]':
        """Gets the links of this V1NVLinkStatus.  # noqa: E501


        :return: The links of this V1NVLinkStatus.  # noqa: E501
        :rtype: list[V1NVLinkInfo]
        """
        return self._links

    @links.setter
    def links(self, links: 'list[V1NVLinkInfo]'):
        """Sets the links of this V1NVLinkStatus.


        :param links: The links of this V1NVLinkStatus.  # noqa: E501
        :type: list[V1NVLinkInfo]
        """

        self._links = links

    @property
    def links_active(self) -> 'int':
        """Gets the links_active of this V1NVLinkStatus.  # noqa: E501


        :return: The links_active of this V1NVLinkStatus.  # noqa: E501
        :rtype: int
        """
        return self._links_active

    @links_active.setter
    def links_active(self, links_active: 'int'):
        """Sets the links_active of this V1NVLinkStatus.


        :param links_active: The links_active of this V1NVLinkStatus.  # noqa: E501
        :type: int
        """

        self._links_active = links_active

    @property
    def links_inactive(self) -> 'int':
        """Gets the links_inactive of this V1NVLinkStatus.  # noqa: E501


        :return: The links_inactive of this V1NVLinkStatus.  # noqa: E501
        :rtype: int
        """
        return self._links_inactive

    @links_inactive.setter
    def links_inactive(self, links_inactive: 'int'):
        """Sets the links_inactive of this V1NVLinkStatus.


        :param links_inactive: The links_inactive of this V1NVLinkStatus.  # noqa: E501
        :type: int
        """

        self._links_inactive = links_inactive

    @property
    def links_total(self) -> 'int':
        """Gets the links_total of this V1NVLinkStatus.  # noqa: E501


        :return: The links_total of this V1NVLinkStatus.  # noqa: E501
        :rtype: int
        """
        return self._links_total

    @links_total.setter
    def links_total(self, links_total: 'int'):
        """Sets the links_total of this V1NVLinkStatus.


        :param links_total: The links_total of this V1NVLinkStatus.  # noqa: E501
        :type: int
        """

        self._links_total = links_total

    @property
    def total_crc_errors(self) -> 'str':
        """Gets the total_crc_errors of this V1NVLinkStatus.  # noqa: E501


        :return: The total_crc_errors of this V1NVLinkStatus.  # noqa: E501
        :rtype: str
        """
        return self._total_crc_errors

    @total_crc_errors.setter
    def total_crc_errors(self, total_crc_errors: 'str'):
        """Sets the total_crc_errors of this V1NVLinkStatus.


        :param total_crc_errors: The total_crc_errors of this V1NVLinkStatus.  # noqa: E501
        :type: str
        """

        self._total_crc_errors = total_crc_errors

    @property
    def total_recovery_errors(self) -> 'str':
        """Gets the total_recovery_errors of this V1NVLinkStatus.  # noqa: E501


        :return: The total_recovery_errors of this V1NVLinkStatus.  # noqa: E501
        :rtype: str
        """
        return self._total_recovery_errors

    @total_recovery_errors.setter
    def total_recovery_errors(self, total_recovery_errors: 'str'):
        """Sets the total_recovery_errors of this V1NVLinkStatus.


        :param total_recovery_errors: The total_recovery_errors of this V1NVLinkStatus.  # noqa: E501
        :type: str
        """

        self._total_recovery_errors = total_recovery_errors

    @property
    def total_replay_errors(self) -> 'str':
        """Gets the total_replay_errors of this V1NVLinkStatus.  # noqa: E501


        :return: The total_replay_errors of this V1NVLinkStatus.  # noqa: E501
        :rtype: str
        """
        return self._total_replay_errors

    @total_replay_errors.setter
    def total_replay_errors(self, total_replay_errors: 'str'):
        """Sets the total_replay_errors of this V1NVLinkStatus.


        :param total_replay_errors: The total_replay_errors of this V1NVLinkStatus.  # noqa: E501
        :type: str
        """

        self._total_replay_errors = total_replay_errors

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1NVLinkStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1NVLinkStatus') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1NVLinkStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1NVLinkStatus') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
