# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1PortOverrides(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'jupyterlab_port': 'int',
        'ssh_host_port': 'int',
        'ssh_vscode_port_external': 'int',
        'ssh_vscode_port_internal': 'int',
        'vscode_port': 'int'
    }

    attribute_map = {
        'jupyterlab_port': 'jupyterlabPort',
        'ssh_host_port': 'sshHostPort',
        'ssh_vscode_port_external': 'sshVscodePortExternal',
        'ssh_vscode_port_internal': 'sshVscodePortInternal',
        'vscode_port': 'vscodePort'
    }

    def __init__(self, jupyterlab_port: 'int' =None, ssh_host_port: 'int' =None, ssh_vscode_port_external: 'int' =None, ssh_vscode_port_internal: 'int' =None, vscode_port: 'int' =None):  # noqa: E501
        """V1PortOverrides - a model defined in Swagger"""  # noqa: E501
        self._jupyterlab_port = None
        self._ssh_host_port = None
        self._ssh_vscode_port_external = None
        self._ssh_vscode_port_internal = None
        self._vscode_port = None
        self.discriminator = None
        if jupyterlab_port is not None:
            self.jupyterlab_port = jupyterlab_port
        if ssh_host_port is not None:
            self.ssh_host_port = ssh_host_port
        if ssh_vscode_port_external is not None:
            self.ssh_vscode_port_external = ssh_vscode_port_external
        if ssh_vscode_port_internal is not None:
            self.ssh_vscode_port_internal = ssh_vscode_port_internal
        if vscode_port is not None:
            self.vscode_port = vscode_port

    @property
    def jupyterlab_port(self) -> 'int':
        """Gets the jupyterlab_port of this V1PortOverrides.  # noqa: E501


        :return: The jupyterlab_port of this V1PortOverrides.  # noqa: E501
        :rtype: int
        """
        return self._jupyterlab_port

    @jupyterlab_port.setter
    def jupyterlab_port(self, jupyterlab_port: 'int'):
        """Sets the jupyterlab_port of this V1PortOverrides.


        :param jupyterlab_port: The jupyterlab_port of this V1PortOverrides.  # noqa: E501
        :type: int
        """

        self._jupyterlab_port = jupyterlab_port

    @property
    def ssh_host_port(self) -> 'int':
        """Gets the ssh_host_port of this V1PortOverrides.  # noqa: E501


        :return: The ssh_host_port of this V1PortOverrides.  # noqa: E501
        :rtype: int
        """
        return self._ssh_host_port

    @ssh_host_port.setter
    def ssh_host_port(self, ssh_host_port: 'int'):
        """Sets the ssh_host_port of this V1PortOverrides.


        :param ssh_host_port: The ssh_host_port of this V1PortOverrides.  # noqa: E501
        :type: int
        """

        self._ssh_host_port = ssh_host_port

    @property
    def ssh_vscode_port_external(self) -> 'int':
        """Gets the ssh_vscode_port_external of this V1PortOverrides.  # noqa: E501


        :return: The ssh_vscode_port_external of this V1PortOverrides.  # noqa: E501
        :rtype: int
        """
        return self._ssh_vscode_port_external

    @ssh_vscode_port_external.setter
    def ssh_vscode_port_external(self, ssh_vscode_port_external: 'int'):
        """Sets the ssh_vscode_port_external of this V1PortOverrides.


        :param ssh_vscode_port_external: The ssh_vscode_port_external of this V1PortOverrides.  # noqa: E501
        :type: int
        """

        self._ssh_vscode_port_external = ssh_vscode_port_external

    @property
    def ssh_vscode_port_internal(self) -> 'int':
        """Gets the ssh_vscode_port_internal of this V1PortOverrides.  # noqa: E501


        :return: The ssh_vscode_port_internal of this V1PortOverrides.  # noqa: E501
        :rtype: int
        """
        return self._ssh_vscode_port_internal

    @ssh_vscode_port_internal.setter
    def ssh_vscode_port_internal(self, ssh_vscode_port_internal: 'int'):
        """Sets the ssh_vscode_port_internal of this V1PortOverrides.


        :param ssh_vscode_port_internal: The ssh_vscode_port_internal of this V1PortOverrides.  # noqa: E501
        :type: int
        """

        self._ssh_vscode_port_internal = ssh_vscode_port_internal

    @property
    def vscode_port(self) -> 'int':
        """Gets the vscode_port of this V1PortOverrides.  # noqa: E501


        :return: The vscode_port of this V1PortOverrides.  # noqa: E501
        :rtype: int
        """
        return self._vscode_port

    @vscode_port.setter
    def vscode_port(self, vscode_port: 'int'):
        """Sets the vscode_port of this V1PortOverrides.


        :param vscode_port: The vscode_port of this V1PortOverrides.  # noqa: E501
        :type: int
        """

        self._vscode_port = vscode_port

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1PortOverrides, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1PortOverrides') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1PortOverrides):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1PortOverrides') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
