# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1PCIDevice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bdf': 'str',
        'device_id': 'str',
        'device_name': 'str',
        'driver': 'str',
        'iommu_group': 'str',
        'link_speed': 'str',
        'link_width': 'str',
        'numa_node': 'str',
        'vendor_id': 'str',
        'vendor_name': 'str'
    }

    attribute_map = {
        'bdf': 'bdf',
        'device_id': 'deviceId',
        'device_name': 'deviceName',
        'driver': 'driver',
        'iommu_group': 'iommuGroup',
        'link_speed': 'linkSpeed',
        'link_width': 'linkWidth',
        'numa_node': 'numaNode',
        'vendor_id': 'vendorId',
        'vendor_name': 'vendorName'
    }

    def __init__(self, bdf: 'str' =None, device_id: 'str' =None, device_name: 'str' =None, driver: 'str' =None, iommu_group: 'str' =None, link_speed: 'str' =None, link_width: 'str' =None, numa_node: 'str' =None, vendor_id: 'str' =None, vendor_name: 'str' =None):  # noqa: E501
        """V1PCIDevice - a model defined in Swagger"""  # noqa: E501
        self._bdf = None
        self._device_id = None
        self._device_name = None
        self._driver = None
        self._iommu_group = None
        self._link_speed = None
        self._link_width = None
        self._numa_node = None
        self._vendor_id = None
        self._vendor_name = None
        self.discriminator = None
        if bdf is not None:
            self.bdf = bdf
        if device_id is not None:
            self.device_id = device_id
        if device_name is not None:
            self.device_name = device_name
        if driver is not None:
            self.driver = driver
        if iommu_group is not None:
            self.iommu_group = iommu_group
        if link_speed is not None:
            self.link_speed = link_speed
        if link_width is not None:
            self.link_width = link_width
        if numa_node is not None:
            self.numa_node = numa_node
        if vendor_id is not None:
            self.vendor_id = vendor_id
        if vendor_name is not None:
            self.vendor_name = vendor_name

    @property
    def bdf(self) -> 'str':
        """Gets the bdf of this V1PCIDevice.  # noqa: E501


        :return: The bdf of this V1PCIDevice.  # noqa: E501
        :rtype: str
        """
        return self._bdf

    @bdf.setter
    def bdf(self, bdf: 'str'):
        """Sets the bdf of this V1PCIDevice.


        :param bdf: The bdf of this V1PCIDevice.  # noqa: E501
        :type: str
        """

        self._bdf = bdf

    @property
    def device_id(self) -> 'str':
        """Gets the device_id of this V1PCIDevice.  # noqa: E501


        :return: The device_id of this V1PCIDevice.  # noqa: E501
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id: 'str'):
        """Sets the device_id of this V1PCIDevice.


        :param device_id: The device_id of this V1PCIDevice.  # noqa: E501
        :type: str
        """

        self._device_id = device_id

    @property
    def device_name(self) -> 'str':
        """Gets the device_name of this V1PCIDevice.  # noqa: E501


        :return: The device_name of this V1PCIDevice.  # noqa: E501
        :rtype: str
        """
        return self._device_name

    @device_name.setter
    def device_name(self, device_name: 'str'):
        """Sets the device_name of this V1PCIDevice.


        :param device_name: The device_name of this V1PCIDevice.  # noqa: E501
        :type: str
        """

        self._device_name = device_name

    @property
    def driver(self) -> 'str':
        """Gets the driver of this V1PCIDevice.  # noqa: E501


        :return: The driver of this V1PCIDevice.  # noqa: E501
        :rtype: str
        """
        return self._driver

    @driver.setter
    def driver(self, driver: 'str'):
        """Sets the driver of this V1PCIDevice.


        :param driver: The driver of this V1PCIDevice.  # noqa: E501
        :type: str
        """

        self._driver = driver

    @property
    def iommu_group(self) -> 'str':
        """Gets the iommu_group of this V1PCIDevice.  # noqa: E501


        :return: The iommu_group of this V1PCIDevice.  # noqa: E501
        :rtype: str
        """
        return self._iommu_group

    @iommu_group.setter
    def iommu_group(self, iommu_group: 'str'):
        """Sets the iommu_group of this V1PCIDevice.


        :param iommu_group: The iommu_group of this V1PCIDevice.  # noqa: E501
        :type: str
        """

        self._iommu_group = iommu_group

    @property
    def link_speed(self) -> 'str':
        """Gets the link_speed of this V1PCIDevice.  # noqa: E501


        :return: The link_speed of this V1PCIDevice.  # noqa: E501
        :rtype: str
        """
        return self._link_speed

    @link_speed.setter
    def link_speed(self, link_speed: 'str'):
        """Sets the link_speed of this V1PCIDevice.


        :param link_speed: The link_speed of this V1PCIDevice.  # noqa: E501
        :type: str
        """

        self._link_speed = link_speed

    @property
    def link_width(self) -> 'str':
        """Gets the link_width of this V1PCIDevice.  # noqa: E501


        :return: The link_width of this V1PCIDevice.  # noqa: E501
        :rtype: str
        """
        return self._link_width

    @link_width.setter
    def link_width(self, link_width: 'str'):
        """Sets the link_width of this V1PCIDevice.


        :param link_width: The link_width of this V1PCIDevice.  # noqa: E501
        :type: str
        """

        self._link_width = link_width

    @property
    def numa_node(self) -> 'str':
        """Gets the numa_node of this V1PCIDevice.  # noqa: E501


        :return: The numa_node of this V1PCIDevice.  # noqa: E501
        :rtype: str
        """
        return self._numa_node

    @numa_node.setter
    def numa_node(self, numa_node: 'str'):
        """Sets the numa_node of this V1PCIDevice.


        :param numa_node: The numa_node of this V1PCIDevice.  # noqa: E501
        :type: str
        """

        self._numa_node = numa_node

    @property
    def vendor_id(self) -> 'str':
        """Gets the vendor_id of this V1PCIDevice.  # noqa: E501


        :return: The vendor_id of this V1PCIDevice.  # noqa: E501
        :rtype: str
        """
        return self._vendor_id

    @vendor_id.setter
    def vendor_id(self, vendor_id: 'str'):
        """Sets the vendor_id of this V1PCIDevice.


        :param vendor_id: The vendor_id of this V1PCIDevice.  # noqa: E501
        :type: str
        """

        self._vendor_id = vendor_id

    @property
    def vendor_name(self) -> 'str':
        """Gets the vendor_name of this V1PCIDevice.  # noqa: E501


        :return: The vendor_name of this V1PCIDevice.  # noqa: E501
        :rtype: str
        """
        return self._vendor_name

    @vendor_name.setter
    def vendor_name(self, vendor_name: 'str'):
        """Sets the vendor_name of this V1PCIDevice.


        :param vendor_name: The vendor_name of this V1PCIDevice.  # noqa: E501
        :type: str
        """

        self._vendor_name = vendor_name

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1PCIDevice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1PCIDevice') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1PCIDevice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1PCIDevice') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
