# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1PublishCommunityModelRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aliases': 'list[str]',
        'api_base_url': 'str',
        'api_key': 'str',
        'completion_token_price': 'float',
        'context_length': 'str',
        'display_name': 'str',
        'max_completion_tokens': 'str',
        'model_id': 'str',
        'nvidia_usage_enabled': 'bool',
        'prompt_token_price': 'float',
        'provider': 'V1ModelAPIProvider'
    }

    attribute_map = {
        'aliases': 'aliases',
        'api_base_url': 'apiBaseUrl',
        'api_key': 'apiKey',
        'completion_token_price': 'completionTokenPrice',
        'context_length': 'contextLength',
        'display_name': 'displayName',
        'max_completion_tokens': 'maxCompletionTokens',
        'model_id': 'modelId',
        'nvidia_usage_enabled': 'nvidiaUsageEnabled',
        'prompt_token_price': 'promptTokenPrice',
        'provider': 'provider'
    }

    def __init__(self, aliases: 'list[str]' =None, api_base_url: 'str' =None, api_key: 'str' =None, completion_token_price: 'float' =None, context_length: 'str' =None, display_name: 'str' =None, max_completion_tokens: 'str' =None, model_id: 'str' =None, nvidia_usage_enabled: 'bool' =None, prompt_token_price: 'float' =None, provider: 'V1ModelAPIProvider' =None):  # noqa: E501
        """V1PublishCommunityModelRequest - a model defined in Swagger"""  # noqa: E501
        self._aliases = None
        self._api_base_url = None
        self._api_key = None
        self._completion_token_price = None
        self._context_length = None
        self._display_name = None
        self._max_completion_tokens = None
        self._model_id = None
        self._nvidia_usage_enabled = None
        self._prompt_token_price = None
        self._provider = None
        self.discriminator = None
        if aliases is not None:
            self.aliases = aliases
        if api_base_url is not None:
            self.api_base_url = api_base_url
        if api_key is not None:
            self.api_key = api_key
        if completion_token_price is not None:
            self.completion_token_price = completion_token_price
        if context_length is not None:
            self.context_length = context_length
        if display_name is not None:
            self.display_name = display_name
        if max_completion_tokens is not None:
            self.max_completion_tokens = max_completion_tokens
        if model_id is not None:
            self.model_id = model_id
        if nvidia_usage_enabled is not None:
            self.nvidia_usage_enabled = nvidia_usage_enabled
        if prompt_token_price is not None:
            self.prompt_token_price = prompt_token_price
        if provider is not None:
            self.provider = provider

    @property
    def aliases(self) -> 'list[str]':
        """Gets the aliases of this V1PublishCommunityModelRequest.  # noqa: E501


        :return: The aliases of this V1PublishCommunityModelRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases: 'list[str]'):
        """Sets the aliases of this V1PublishCommunityModelRequest.


        :param aliases: The aliases of this V1PublishCommunityModelRequest.  # noqa: E501
        :type: list[str]
        """

        self._aliases = aliases

    @property
    def api_base_url(self) -> 'str':
        """Gets the api_base_url of this V1PublishCommunityModelRequest.  # noqa: E501


        :return: The api_base_url of this V1PublishCommunityModelRequest.  # noqa: E501
        :rtype: str
        """
        return self._api_base_url

    @api_base_url.setter
    def api_base_url(self, api_base_url: 'str'):
        """Sets the api_base_url of this V1PublishCommunityModelRequest.


        :param api_base_url: The api_base_url of this V1PublishCommunityModelRequest.  # noqa: E501
        :type: str
        """

        self._api_base_url = api_base_url

    @property
    def api_key(self) -> 'str':
        """Gets the api_key of this V1PublishCommunityModelRequest.  # noqa: E501


        :return: The api_key of this V1PublishCommunityModelRequest.  # noqa: E501
        :rtype: str
        """
        return self._api_key

    @api_key.setter
    def api_key(self, api_key: 'str'):
        """Sets the api_key of this V1PublishCommunityModelRequest.


        :param api_key: The api_key of this V1PublishCommunityModelRequest.  # noqa: E501
        :type: str
        """

        self._api_key = api_key

    @property
    def completion_token_price(self) -> 'float':
        """Gets the completion_token_price of this V1PublishCommunityModelRequest.  # noqa: E501


        :return: The completion_token_price of this V1PublishCommunityModelRequest.  # noqa: E501
        :rtype: float
        """
        return self._completion_token_price

    @completion_token_price.setter
    def completion_token_price(self, completion_token_price: 'float'):
        """Sets the completion_token_price of this V1PublishCommunityModelRequest.


        :param completion_token_price: The completion_token_price of this V1PublishCommunityModelRequest.  # noqa: E501
        :type: float
        """

        self._completion_token_price = completion_token_price

    @property
    def context_length(self) -> 'str':
        """Gets the context_length of this V1PublishCommunityModelRequest.  # noqa: E501


        :return: The context_length of this V1PublishCommunityModelRequest.  # noqa: E501
        :rtype: str
        """
        return self._context_length

    @context_length.setter
    def context_length(self, context_length: 'str'):
        """Sets the context_length of this V1PublishCommunityModelRequest.


        :param context_length: The context_length of this V1PublishCommunityModelRequest.  # noqa: E501
        :type: str
        """

        self._context_length = context_length

    @property
    def display_name(self) -> 'str':
        """Gets the display_name of this V1PublishCommunityModelRequest.  # noqa: E501


        :return: The display_name of this V1PublishCommunityModelRequest.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: 'str'):
        """Sets the display_name of this V1PublishCommunityModelRequest.


        :param display_name: The display_name of this V1PublishCommunityModelRequest.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def max_completion_tokens(self) -> 'str':
        """Gets the max_completion_tokens of this V1PublishCommunityModelRequest.  # noqa: E501


        :return: The max_completion_tokens of this V1PublishCommunityModelRequest.  # noqa: E501
        :rtype: str
        """
        return self._max_completion_tokens

    @max_completion_tokens.setter
    def max_completion_tokens(self, max_completion_tokens: 'str'):
        """Sets the max_completion_tokens of this V1PublishCommunityModelRequest.


        :param max_completion_tokens: The max_completion_tokens of this V1PublishCommunityModelRequest.  # noqa: E501
        :type: str
        """

        self._max_completion_tokens = max_completion_tokens

    @property
    def model_id(self) -> 'str':
        """Gets the model_id of this V1PublishCommunityModelRequest.  # noqa: E501


        :return: The model_id of this V1PublishCommunityModelRequest.  # noqa: E501
        :rtype: str
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id: 'str'):
        """Sets the model_id of this V1PublishCommunityModelRequest.


        :param model_id: The model_id of this V1PublishCommunityModelRequest.  # noqa: E501
        :type: str
        """

        self._model_id = model_id

    @property
    def nvidia_usage_enabled(self) -> 'bool':
        """Gets the nvidia_usage_enabled of this V1PublishCommunityModelRequest.  # noqa: E501


        :return: The nvidia_usage_enabled of this V1PublishCommunityModelRequest.  # noqa: E501
        :rtype: bool
        """
        return self._nvidia_usage_enabled

    @nvidia_usage_enabled.setter
    def nvidia_usage_enabled(self, nvidia_usage_enabled: 'bool'):
        """Sets the nvidia_usage_enabled of this V1PublishCommunityModelRequest.


        :param nvidia_usage_enabled: The nvidia_usage_enabled of this V1PublishCommunityModelRequest.  # noqa: E501
        :type: bool
        """

        self._nvidia_usage_enabled = nvidia_usage_enabled

    @property
    def prompt_token_price(self) -> 'float':
        """Gets the prompt_token_price of this V1PublishCommunityModelRequest.  # noqa: E501


        :return: The prompt_token_price of this V1PublishCommunityModelRequest.  # noqa: E501
        :rtype: float
        """
        return self._prompt_token_price

    @prompt_token_price.setter
    def prompt_token_price(self, prompt_token_price: 'float'):
        """Sets the prompt_token_price of this V1PublishCommunityModelRequest.


        :param prompt_token_price: The prompt_token_price of this V1PublishCommunityModelRequest.  # noqa: E501
        :type: float
        """

        self._prompt_token_price = prompt_token_price

    @property
    def provider(self) -> 'V1ModelAPIProvider':
        """Gets the provider of this V1PublishCommunityModelRequest.  # noqa: E501


        :return: The provider of this V1PublishCommunityModelRequest.  # noqa: E501
        :rtype: V1ModelAPIProvider
        """
        return self._provider

    @provider.setter
    def provider(self, provider: 'V1ModelAPIProvider'):
        """Sets the provider of this V1PublishCommunityModelRequest.


        :param provider: The provider of this V1PublishCommunityModelRequest.  # noqa: E501
        :type: V1ModelAPIProvider
        """

        self._provider = provider

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1PublishCommunityModelRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1PublishCommunityModelRequest') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1PublishCommunityModelRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1PublishCommunityModelRequest') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
