# coding: utf-8
# This file is vendored.
# Do not edit it directly; changes will be overwritten.
# Make changes in the internal upstream repository instead.


"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1SandboxWarmSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'after_restore_cmd': 'str',
        'after_restore_timeout_ms': 'int',
        'after_start_cmd': 'list[str]',
        'envs': 'dict(str, str)',
        'ready_cmd': 'V1SandboxReadyCheck',
        'ready_timeout_ms': 'int',
        'rebind': 'list[V1SandboxRebindVar]',
        'require_warm': 'bool',
        'run_cmd': 'list[str]',
        'skip_cache': 'bool',
        'start_cmd': 'str'
    }

    attribute_map = {
        'after_restore_cmd': 'afterRestoreCmd',
        'after_restore_timeout_ms': 'afterRestoreTimeoutMs',
        'after_start_cmd': 'afterStartCmd',
        'envs': 'envs',
        'ready_cmd': 'readyCmd',
        'ready_timeout_ms': 'readyTimeoutMs',
        'rebind': 'rebind',
        'require_warm': 'requireWarm',
        'run_cmd': 'runCmd',
        'skip_cache': 'skipCache',
        'start_cmd': 'startCmd'
    }

    def __init__(self, after_restore_cmd: 'str' =None, after_restore_timeout_ms: 'int' =None, after_start_cmd: 'list[str]' =None, envs: 'dict(str, str)' =None, ready_cmd: 'V1SandboxReadyCheck' =None, ready_timeout_ms: 'int' =None, rebind: 'list[V1SandboxRebindVar]' =None, require_warm: 'bool' =None, run_cmd: 'list[str]' =None, skip_cache: 'bool' =None, start_cmd: 'str' =None):  # noqa: E501
        """V1SandboxWarmSpec - a model defined in Swagger"""  # noqa: E501
        self._after_restore_cmd = None
        self._after_restore_timeout_ms = None
        self._after_start_cmd = None
        self._envs = None
        self._ready_cmd = None
        self._ready_timeout_ms = None
        self._rebind = None
        self._require_warm = None
        self._run_cmd = None
        self._skip_cache = None
        self._start_cmd = None
        self.discriminator = None
        if after_restore_cmd is not None:
            self.after_restore_cmd = after_restore_cmd
        if after_restore_timeout_ms is not None:
            self.after_restore_timeout_ms = after_restore_timeout_ms
        if after_start_cmd is not None:
            self.after_start_cmd = after_start_cmd
        if envs is not None:
            self.envs = envs
        if ready_cmd is not None:
            self.ready_cmd = ready_cmd
        if ready_timeout_ms is not None:
            self.ready_timeout_ms = ready_timeout_ms
        if rebind is not None:
            self.rebind = rebind
        if require_warm is not None:
            self.require_warm = require_warm
        if run_cmd is not None:
            self.run_cmd = run_cmd
        if skip_cache is not None:
            self.skip_cache = skip_cache
        if start_cmd is not None:
            self.start_cmd = start_cmd

    @property
    def after_restore_cmd(self) -> 'str':
        """Gets the after_restore_cmd of this V1SandboxWarmSpec.  # noqa: E501

        Command run inside each restored sandbox, after `rebind` values are in place and before the sandbox is reported ready. This is where a process resumed from a shared checkpoint picks up its own identity — reload a config, re-issue a token, reseed a PRNG. Skipped on a cold boot, where the recipe already ran with the real values.  # noqa: E501

        :return: The after_restore_cmd of this V1SandboxWarmSpec.  # noqa: E501
        :rtype: str
        """
        return self._after_restore_cmd

    @after_restore_cmd.setter
    def after_restore_cmd(self, after_restore_cmd: 'str'):
        """Sets the after_restore_cmd of this V1SandboxWarmSpec.

        Command run inside each restored sandbox, after `rebind` values are in place and before the sandbox is reported ready. This is where a process resumed from a shared checkpoint picks up its own identity — reload a config, re-issue a token, reseed a PRNG. Skipped on a cold boot, where the recipe already ran with the real values.  # noqa: E501

        :param after_restore_cmd: The after_restore_cmd of this V1SandboxWarmSpec.  # noqa: E501
        :type: str
        """

        self._after_restore_cmd = after_restore_cmd

    @property
    def after_restore_timeout_ms(self) -> 'int':
        """Gets the after_restore_timeout_ms of this V1SandboxWarmSpec.  # noqa: E501

        How long `after_restore_cmd` may take before the restore is failed. Defaults to 10000 (10 seconds).  # noqa: E501

        :return: The after_restore_timeout_ms of this V1SandboxWarmSpec.  # noqa: E501
        :rtype: int
        """
        return self._after_restore_timeout_ms

    @after_restore_timeout_ms.setter
    def after_restore_timeout_ms(self, after_restore_timeout_ms: 'int'):
        """Sets the after_restore_timeout_ms of this V1SandboxWarmSpec.

        How long `after_restore_cmd` may take before the restore is failed. Defaults to 10000 (10 seconds).  # noqa: E501

        :param after_restore_timeout_ms: The after_restore_timeout_ms of this V1SandboxWarmSpec.  # noqa: E501
        :type: int
        """

        self._after_restore_timeout_ms = after_restore_timeout_ms

    @property
    def after_start_cmd(self) -> 'list[str]':
        """Gets the after_start_cmd of this V1SandboxWarmSpec.  # noqa: E501

        Commands run once the start command is up — after `ready_cmd` first passes, before the checkpoint is taken. This is where a recipe warms something that only exists once its server is running: creating a Jupyter kernel and importing into it, priming a cache, compiling a first request.  `run_cmd` cannot do this. Those run before `start_cmd`, so there is nothing listening for them to talk to.  Like `run_cmd`, these run at bake time only; a restored sandbox observes their effects without re-running them. A cold-served create runs them inline so both paths hand back the same sandbox.  # noqa: E501

        :return: The after_start_cmd of this V1SandboxWarmSpec.  # noqa: E501
        :rtype: list[str]
        """
        return self._after_start_cmd

    @after_start_cmd.setter
    def after_start_cmd(self, after_start_cmd: 'list[str]'):
        """Sets the after_start_cmd of this V1SandboxWarmSpec.

        Commands run once the start command is up — after `ready_cmd` first passes, before the checkpoint is taken. This is where a recipe warms something that only exists once its server is running: creating a Jupyter kernel and importing into it, priming a cache, compiling a first request.  `run_cmd` cannot do this. Those run before `start_cmd`, so there is nothing listening for them to talk to.  Like `run_cmd`, these run at bake time only; a restored sandbox observes their effects without re-running them. A cold-served create runs them inline so both paths hand back the same sandbox.  # noqa: E501

        :param after_start_cmd: The after_start_cmd of this V1SandboxWarmSpec.  # noqa: E501
        :type: list[str]
        """

        self._after_start_cmd = after_start_cmd

    @property
    def envs(self) -> 'dict(str, str)':
        """Gets the envs of this V1SandboxWarmSpec.  # noqa: E501

        Environment variables visible to `run_cmd` and `start_cmd` during the bake. They are captured in the checkpoint and therefore shared by every sandbox restored from it: put configuration here, never a credential. For per-sandbox credentials use `rebind`.  # noqa: E501

        :return: The envs of this V1SandboxWarmSpec.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._envs

    @envs.setter
    def envs(self, envs: 'dict(str, str)'):
        """Sets the envs of this V1SandboxWarmSpec.

        Environment variables visible to `run_cmd` and `start_cmd` during the bake. They are captured in the checkpoint and therefore shared by every sandbox restored from it: put configuration here, never a credential. For per-sandbox credentials use `rebind`.  # noqa: E501

        :param envs: The envs of this V1SandboxWarmSpec.  # noqa: E501
        :type: dict(str, str)
        """

        self._envs = envs

    @property
    def ready_cmd(self) -> 'V1SandboxReadyCheck':
        """Gets the ready_cmd of this V1SandboxWarmSpec.  # noqa: E501


        :return: The ready_cmd of this V1SandboxWarmSpec.  # noqa: E501
        :rtype: V1SandboxReadyCheck
        """
        return self._ready_cmd

    @ready_cmd.setter
    def ready_cmd(self, ready_cmd: 'V1SandboxReadyCheck'):
        """Sets the ready_cmd of this V1SandboxWarmSpec.


        :param ready_cmd: The ready_cmd of this V1SandboxWarmSpec.  # noqa: E501
        :type: V1SandboxReadyCheck
        """

        self._ready_cmd = ready_cmd

    @property
    def ready_timeout_ms(self) -> 'int':
        """Gets the ready_timeout_ms of this V1SandboxWarmSpec.  # noqa: E501

        How long to keep retrying `ready_cmd` before abandoning the bake. Defaults to 120000 (2 minutes).  # noqa: E501

        :return: The ready_timeout_ms of this V1SandboxWarmSpec.  # noqa: E501
        :rtype: int
        """
        return self._ready_timeout_ms

    @ready_timeout_ms.setter
    def ready_timeout_ms(self, ready_timeout_ms: 'int'):
        """Sets the ready_timeout_ms of this V1SandboxWarmSpec.

        How long to keep retrying `ready_cmd` before abandoning the bake. Defaults to 120000 (2 minutes).  # noqa: E501

        :param ready_timeout_ms: The ready_timeout_ms of this V1SandboxWarmSpec.  # noqa: E501
        :type: int
        """

        self._ready_timeout_ms = ready_timeout_ms

    @property
    def rebind(self) -> 'list[V1SandboxRebindVar]':
        """Gets the rebind of this V1SandboxWarmSpec.  # noqa: E501

        Values that must differ per sandbox even though the checkpoint is shared. Baked with a placeholder, replaced at restore. See SandboxRebindVar.  # noqa: E501

        :return: The rebind of this V1SandboxWarmSpec.  # noqa: E501
        :rtype: list[V1SandboxRebindVar]
        """
        return self._rebind

    @rebind.setter
    def rebind(self, rebind: 'list[V1SandboxRebindVar]'):
        """Sets the rebind of this V1SandboxWarmSpec.

        Values that must differ per sandbox even though the checkpoint is shared. Baked with a placeholder, replaced at restore. See SandboxRebindVar.  # noqa: E501

        :param rebind: The rebind of this V1SandboxWarmSpec.  # noqa: E501
        :type: list[V1SandboxRebindVar]
        """

        self._rebind = rebind

    @property
    def require_warm(self) -> 'bool':
        """Gets the require_warm of this V1SandboxWarmSpec.  # noqa: E501

        Fail the create instead of cold-booting when no checkpoint is available for this recipe. Use it to assert warm starts in tests and benchmarks; leave it unset in production so a bake miss degrades to a slow start rather than an error.  # noqa: E501

        :return: The require_warm of this V1SandboxWarmSpec.  # noqa: E501
        :rtype: bool
        """
        return self._require_warm

    @require_warm.setter
    def require_warm(self, require_warm: 'bool'):
        """Sets the require_warm of this V1SandboxWarmSpec.

        Fail the create instead of cold-booting when no checkpoint is available for this recipe. Use it to assert warm starts in tests and benchmarks; leave it unset in production so a bake miss degrades to a slow start rather than an error.  # noqa: E501

        :param require_warm: The require_warm of this V1SandboxWarmSpec.  # noqa: E501
        :type: bool
        """

        self._require_warm = require_warm

    @property
    def run_cmd(self) -> 'list[str]':
        """Gets the run_cmd of this V1SandboxWarmSpec.  # noqa: E501

        Setup commands, run in order, in a shell. These run at bake time only — a restored sandbox observes their effects but never re-runs them.  # noqa: E501

        :return: The run_cmd of this V1SandboxWarmSpec.  # noqa: E501
        :rtype: list[str]
        """
        return self._run_cmd

    @run_cmd.setter
    def run_cmd(self, run_cmd: 'list[str]'):
        """Sets the run_cmd of this V1SandboxWarmSpec.

        Setup commands, run in order, in a shell. These run at bake time only — a restored sandbox observes their effects but never re-runs them.  # noqa: E501

        :param run_cmd: The run_cmd of this V1SandboxWarmSpec.  # noqa: E501
        :type: list[str]
        """

        self._run_cmd = run_cmd

    @property
    def skip_cache(self) -> 'bool':
        """Gets the skip_cache of this V1SandboxWarmSpec.  # noqa: E501

        Ignore any existing checkpoint for this recipe and bake a fresh one. For rebuilding after a change the key cannot see, such as a mutable image tag or a package the recipe installs from a moving source.  # noqa: E501

        :return: The skip_cache of this V1SandboxWarmSpec.  # noqa: E501
        :rtype: bool
        """
        return self._skip_cache

    @skip_cache.setter
    def skip_cache(self, skip_cache: 'bool'):
        """Sets the skip_cache of this V1SandboxWarmSpec.

        Ignore any existing checkpoint for this recipe and bake a fresh one. For rebuilding after a change the key cannot see, such as a mutable image tag or a package the recipe installs from a moving source.  # noqa: E501

        :param skip_cache: The skip_cache of this V1SandboxWarmSpec.  # noqa: E501
        :type: bool
        """

        self._skip_cache = skip_cache

    @property
    def start_cmd(self) -> 'str':
        """Gets the start_cmd of this V1SandboxWarmSpec.  # noqa: E501

        Long-running process to leave running in the checkpoint, e.g. \"jupyter lab --port 8888\". Started after `run_cmd` and captured mid-flight, so restored sandboxes get a process that is already listening and warm. Optional: a recipe may be setup-only.  # noqa: E501

        :return: The start_cmd of this V1SandboxWarmSpec.  # noqa: E501
        :rtype: str
        """
        return self._start_cmd

    @start_cmd.setter
    def start_cmd(self, start_cmd: 'str'):
        """Sets the start_cmd of this V1SandboxWarmSpec.

        Long-running process to leave running in the checkpoint, e.g. \"jupyter lab --port 8888\". Started after `run_cmd` and captured mid-flight, so restored sandboxes get a process that is already listening and warm. Optional: a recipe may be setup-only.  # noqa: E501

        :param start_cmd: The start_cmd of this V1SandboxWarmSpec.  # noqa: E501
        :type: str
        """

        self._start_cmd = start_cmd

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1SandboxWarmSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1SandboxWarmSpec') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1SandboxWarmSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1SandboxWarmSpec') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
