# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1SandboxResourceMetricSample(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cpu_percentage': 'float',
        'memory_limit_bytes': 'str',
        'memory_percentage': 'float',
        'memory_used_bytes': 'str',
        'num_cpus': 'int',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'cpu_percentage': 'cpuPercentage',
        'memory_limit_bytes': 'memoryLimitBytes',
        'memory_percentage': 'memoryPercentage',
        'memory_used_bytes': 'memoryUsedBytes',
        'num_cpus': 'numCpus',
        'timestamp': 'timestamp'
    }

    def __init__(self, cpu_percentage: 'float' =None, memory_limit_bytes: 'str' =None, memory_percentage: 'float' =None, memory_used_bytes: 'str' =None, num_cpus: 'int' =None, timestamp: 'datetime' =None):  # noqa: E501
        """V1SandboxResourceMetricSample - a model defined in Swagger"""  # noqa: E501
        self._cpu_percentage = None
        self._memory_limit_bytes = None
        self._memory_percentage = None
        self._memory_used_bytes = None
        self._num_cpus = None
        self._timestamp = None
        self.discriminator = None
        if cpu_percentage is not None:
            self.cpu_percentage = cpu_percentage
        if memory_limit_bytes is not None:
            self.memory_limit_bytes = memory_limit_bytes
        if memory_percentage is not None:
            self.memory_percentage = memory_percentage
        if memory_used_bytes is not None:
            self.memory_used_bytes = memory_used_bytes
        if num_cpus is not None:
            self.num_cpus = num_cpus
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def cpu_percentage(self) -> 'float':
        """Gets the cpu_percentage of this V1SandboxResourceMetricSample.  # noqa: E501

        Average CPU utilization across the bucket, 0-100.  # noqa: E501

        :return: The cpu_percentage of this V1SandboxResourceMetricSample.  # noqa: E501
        :rtype: float
        """
        return self._cpu_percentage

    @cpu_percentage.setter
    def cpu_percentage(self, cpu_percentage: 'float'):
        """Sets the cpu_percentage of this V1SandboxResourceMetricSample.

        Average CPU utilization across the bucket, 0-100.  # noqa: E501

        :param cpu_percentage: The cpu_percentage of this V1SandboxResourceMetricSample.  # noqa: E501
        :type: float
        """

        self._cpu_percentage = cpu_percentage

    @property
    def memory_limit_bytes(self) -> 'str':
        """Gets the memory_limit_bytes of this V1SandboxResourceMetricSample.  # noqa: E501


        :return: The memory_limit_bytes of this V1SandboxResourceMetricSample.  # noqa: E501
        :rtype: str
        """
        return self._memory_limit_bytes

    @memory_limit_bytes.setter
    def memory_limit_bytes(self, memory_limit_bytes: 'str'):
        """Sets the memory_limit_bytes of this V1SandboxResourceMetricSample.


        :param memory_limit_bytes: The memory_limit_bytes of this V1SandboxResourceMetricSample.  # noqa: E501
        :type: str
        """

        self._memory_limit_bytes = memory_limit_bytes

    @property
    def memory_percentage(self) -> 'float':
        """Gets the memory_percentage of this V1SandboxResourceMetricSample.  # noqa: E501

        Average memory utilization across the bucket, 0-100.  # noqa: E501

        :return: The memory_percentage of this V1SandboxResourceMetricSample.  # noqa: E501
        :rtype: float
        """
        return self._memory_percentage

    @memory_percentage.setter
    def memory_percentage(self, memory_percentage: 'float'):
        """Sets the memory_percentage of this V1SandboxResourceMetricSample.

        Average memory utilization across the bucket, 0-100.  # noqa: E501

        :param memory_percentage: The memory_percentage of this V1SandboxResourceMetricSample.  # noqa: E501
        :type: float
        """

        self._memory_percentage = memory_percentage

    @property
    def memory_used_bytes(self) -> 'str':
        """Gets the memory_used_bytes of this V1SandboxResourceMetricSample.  # noqa: E501


        :return: The memory_used_bytes of this V1SandboxResourceMetricSample.  # noqa: E501
        :rtype: str
        """
        return self._memory_used_bytes

    @memory_used_bytes.setter
    def memory_used_bytes(self, memory_used_bytes: 'str'):
        """Sets the memory_used_bytes of this V1SandboxResourceMetricSample.


        :param memory_used_bytes: The memory_used_bytes of this V1SandboxResourceMetricSample.  # noqa: E501
        :type: str
        """

        self._memory_used_bytes = memory_used_bytes

    @property
    def num_cpus(self) -> 'int':
        """Gets the num_cpus of this V1SandboxResourceMetricSample.  # noqa: E501


        :return: The num_cpus of this V1SandboxResourceMetricSample.  # noqa: E501
        :rtype: int
        """
        return self._num_cpus

    @num_cpus.setter
    def num_cpus(self, num_cpus: 'int'):
        """Sets the num_cpus of this V1SandboxResourceMetricSample.


        :param num_cpus: The num_cpus of this V1SandboxResourceMetricSample.  # noqa: E501
        :type: int
        """

        self._num_cpus = num_cpus

    @property
    def timestamp(self) -> 'datetime':
        """Gets the timestamp of this V1SandboxResourceMetricSample.  # noqa: E501


        :return: The timestamp of this V1SandboxResourceMetricSample.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: 'datetime'):
        """Sets the timestamp of this V1SandboxResourceMetricSample.


        :param timestamp: The timestamp of this V1SandboxResourceMetricSample.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1SandboxResourceMetricSample, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1SandboxResourceMetricSample') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1SandboxResourceMetricSample):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1SandboxResourceMetricSample') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
