# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1StorageCategory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'item_count': 'int',
        'last_scanned': 'datetime',
        'path': 'str',
        'total_bytes': 'str'
    }

    attribute_map = {
        'item_count': 'itemCount',
        'last_scanned': 'lastScanned',
        'path': 'path',
        'total_bytes': 'totalBytes'
    }

    def __init__(self, item_count: 'int' =None, last_scanned: 'datetime' =None, path: 'str' =None, total_bytes: 'str' =None):  # noqa: E501
        """V1StorageCategory - a model defined in Swagger"""  # noqa: E501
        self._item_count = None
        self._last_scanned = None
        self._path = None
        self._total_bytes = None
        self.discriminator = None
        if item_count is not None:
            self.item_count = item_count
        if last_scanned is not None:
            self.last_scanned = last_scanned
        if path is not None:
            self.path = path
        if total_bytes is not None:
            self.total_bytes = total_bytes

    @property
    def item_count(self) -> 'int':
        """Gets the item_count of this V1StorageCategory.  # noqa: E501


        :return: The item_count of this V1StorageCategory.  # noqa: E501
        :rtype: int
        """
        return self._item_count

    @item_count.setter
    def item_count(self, item_count: 'int'):
        """Sets the item_count of this V1StorageCategory.


        :param item_count: The item_count of this V1StorageCategory.  # noqa: E501
        :type: int
        """

        self._item_count = item_count

    @property
    def last_scanned(self) -> 'datetime':
        """Gets the last_scanned of this V1StorageCategory.  # noqa: E501


        :return: The last_scanned of this V1StorageCategory.  # noqa: E501
        :rtype: datetime
        """
        return self._last_scanned

    @last_scanned.setter
    def last_scanned(self, last_scanned: 'datetime'):
        """Sets the last_scanned of this V1StorageCategory.


        :param last_scanned: The last_scanned of this V1StorageCategory.  # noqa: E501
        :type: datetime
        """

        self._last_scanned = last_scanned

    @property
    def path(self) -> 'str':
        """Gets the path of this V1StorageCategory.  # noqa: E501


        :return: The path of this V1StorageCategory.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: 'str'):
        """Sets the path of this V1StorageCategory.


        :param path: The path of this V1StorageCategory.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def total_bytes(self) -> 'str':
        """Gets the total_bytes of this V1StorageCategory.  # noqa: E501


        :return: The total_bytes of this V1StorageCategory.  # noqa: E501
        :rtype: str
        """
        return self._total_bytes

    @total_bytes.setter
    def total_bytes(self, total_bytes: 'str'):
        """Sets the total_bytes of this V1StorageCategory.


        :param total_bytes: The total_bytes of this V1StorageCategory.  # noqa: E501
        :type: str
        """

        self._total_bytes = total_bytes

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1StorageCategory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1StorageCategory') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1StorageCategory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1StorageCategory') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
