# coding: utf-8
# This file is vendored.
# Do not edit it directly; changes will be overwritten.
# Make changes in the internal upstream repository instead.


"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1SentinelOneState(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'anti_tamper': 'bool',
        'connectivity': 'bool',
        'connectivity_reached_at': 'float',
        'last_mitigation': 'V1SentinelOneMitigation',
        'mitigated': 'bool',
        'tagged': 'bool',
        'uuid': 'str'
    }

    attribute_map = {
        'anti_tamper': 'antiTamper',
        'connectivity': 'connectivity',
        'connectivity_reached_at': 'connectivityReachedAt',
        'last_mitigation': 'lastMitigation',
        'mitigated': 'mitigated',
        'tagged': 'tagged',
        'uuid': 'uuid'
    }

    def __init__(self, anti_tamper: 'bool' =None, connectivity: 'bool' =None, connectivity_reached_at: 'float' =None, last_mitigation: 'V1SentinelOneMitigation' =None, mitigated: 'bool' =None, tagged: 'bool' =None, uuid: 'str' =None):  # noqa: E501
        """V1SentinelOneState - a model defined in Swagger"""  # noqa: E501
        self._anti_tamper = None
        self._connectivity = None
        self._connectivity_reached_at = None
        self._last_mitigation = None
        self._mitigated = None
        self._tagged = None
        self._uuid = None
        self.discriminator = None
        if anti_tamper is not None:
            self.anti_tamper = anti_tamper
        if connectivity is not None:
            self.connectivity = connectivity
        if connectivity_reached_at is not None:
            self.connectivity_reached_at = connectivity_reached_at
        if last_mitigation is not None:
            self.last_mitigation = last_mitigation
        if mitigated is not None:
            self.mitigated = mitigated
        if tagged is not None:
            self.tagged = tagged
        if uuid is not None:
            self.uuid = uuid

    @property
    def anti_tamper(self) -> 'bool':
        """Gets the anti_tamper of this V1SentinelOneState.  # noqa: E501


        :return: The anti_tamper of this V1SentinelOneState.  # noqa: E501
        :rtype: bool
        """
        return self._anti_tamper

    @anti_tamper.setter
    def anti_tamper(self, anti_tamper: 'bool'):
        """Sets the anti_tamper of this V1SentinelOneState.


        :param anti_tamper: The anti_tamper of this V1SentinelOneState.  # noqa: E501
        :type: bool
        """

        self._anti_tamper = anti_tamper

    @property
    def connectivity(self) -> 'bool':
        """Gets the connectivity of this V1SentinelOneState.  # noqa: E501


        :return: The connectivity of this V1SentinelOneState.  # noqa: E501
        :rtype: bool
        """
        return self._connectivity

    @connectivity.setter
    def connectivity(self, connectivity: 'bool'):
        """Sets the connectivity of this V1SentinelOneState.


        :param connectivity: The connectivity of this V1SentinelOneState.  # noqa: E501
        :type: bool
        """

        self._connectivity = connectivity

    @property
    def connectivity_reached_at(self) -> 'float':
        """Gets the connectivity_reached_at of this V1SentinelOneState.  # noqa: E501

        VM uptime in seconds when Connectivity=On was first observed.  # noqa: E501

        :return: The connectivity_reached_at of this V1SentinelOneState.  # noqa: E501
        :rtype: float
        """
        return self._connectivity_reached_at

    @connectivity_reached_at.setter
    def connectivity_reached_at(self, connectivity_reached_at: 'float'):
        """Sets the connectivity_reached_at of this V1SentinelOneState.

        VM uptime in seconds when Connectivity=On was first observed.  # noqa: E501

        :param connectivity_reached_at: The connectivity_reached_at of this V1SentinelOneState.  # noqa: E501
        :type: float
        """

        self._connectivity_reached_at = connectivity_reached_at

    @property
    def last_mitigation(self) -> 'V1SentinelOneMitigation':
        """Gets the last_mitigation of this V1SentinelOneState.  # noqa: E501


        :return: The last_mitigation of this V1SentinelOneState.  # noqa: E501
        :rtype: V1SentinelOneMitigation
        """
        return self._last_mitigation

    @last_mitigation.setter
    def last_mitigation(self, last_mitigation: 'V1SentinelOneMitigation'):
        """Sets the last_mitigation of this V1SentinelOneState.


        :param last_mitigation: The last_mitigation of this V1SentinelOneState.  # noqa: E501
        :type: V1SentinelOneMitigation
        """

        self._last_mitigation = last_mitigation

    @property
    def mitigated(self) -> 'bool':
        """Gets the mitigated of this V1SentinelOneState.  # noqa: E501


        :return: The mitigated of this V1SentinelOneState.  # noqa: E501
        :rtype: bool
        """
        return self._mitigated

    @mitigated.setter
    def mitigated(self, mitigated: 'bool'):
        """Sets the mitigated of this V1SentinelOneState.


        :param mitigated: The mitigated of this V1SentinelOneState.  # noqa: E501
        :type: bool
        """

        self._mitigated = mitigated

    @property
    def tagged(self) -> 'bool':
        """Gets the tagged of this V1SentinelOneState.  # noqa: E501


        :return: The tagged of this V1SentinelOneState.  # noqa: E501
        :rtype: bool
        """
        return self._tagged

    @tagged.setter
    def tagged(self, tagged: 'bool'):
        """Sets the tagged of this V1SentinelOneState.


        :param tagged: The tagged of this V1SentinelOneState.  # noqa: E501
        :type: bool
        """

        self._tagged = tagged

    @property
    def uuid(self) -> 'str':
        """Gets the uuid of this V1SentinelOneState.  # noqa: E501


        :return: The uuid of this V1SentinelOneState.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: 'str'):
        """Sets the uuid of this V1SentinelOneState.


        :param uuid: The uuid of this V1SentinelOneState.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1SentinelOneState, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1SentinelOneState') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1SentinelOneState):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1SentinelOneState') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
