# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1VirtualMachineMetrics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cpu_usage_percent': 'float',
        'memory_available_bytes': 'float',
        'memory_resident_bytes': 'float',
        'network_rx_bytes_per_sec': 'float',
        'network_tx_bytes_per_sec': 'float',
        'storage_iops_read': 'list[V1DriveIOPS]',
        'storage_iops_write': 'list[V1DriveIOPS]'
    }

    attribute_map = {
        'cpu_usage_percent': 'cpuUsagePercent',
        'memory_available_bytes': 'memoryAvailableBytes',
        'memory_resident_bytes': 'memoryResidentBytes',
        'network_rx_bytes_per_sec': 'networkRxBytesPerSec',
        'network_tx_bytes_per_sec': 'networkTxBytesPerSec',
        'storage_iops_read': 'storageIopsRead',
        'storage_iops_write': 'storageIopsWrite'
    }

    def __init__(self, cpu_usage_percent: 'float' =None, memory_available_bytes: 'float' =None, memory_resident_bytes: 'float' =None, network_rx_bytes_per_sec: 'float' =None, network_tx_bytes_per_sec: 'float' =None, storage_iops_read: 'list[V1DriveIOPS]' =None, storage_iops_write: 'list[V1DriveIOPS]' =None):  # noqa: E501
        """V1VirtualMachineMetrics - a model defined in Swagger"""  # noqa: E501
        self._cpu_usage_percent = None
        self._memory_available_bytes = None
        self._memory_resident_bytes = None
        self._network_rx_bytes_per_sec = None
        self._network_tx_bytes_per_sec = None
        self._storage_iops_read = None
        self._storage_iops_write = None
        self.discriminator = None
        if cpu_usage_percent is not None:
            self.cpu_usage_percent = cpu_usage_percent
        if memory_available_bytes is not None:
            self.memory_available_bytes = memory_available_bytes
        if memory_resident_bytes is not None:
            self.memory_resident_bytes = memory_resident_bytes
        if network_rx_bytes_per_sec is not None:
            self.network_rx_bytes_per_sec = network_rx_bytes_per_sec
        if network_tx_bytes_per_sec is not None:
            self.network_tx_bytes_per_sec = network_tx_bytes_per_sec
        if storage_iops_read is not None:
            self.storage_iops_read = storage_iops_read
        if storage_iops_write is not None:
            self.storage_iops_write = storage_iops_write

    @property
    def cpu_usage_percent(self) -> 'float':
        """Gets the cpu_usage_percent of this V1VirtualMachineMetrics.  # noqa: E501


        :return: The cpu_usage_percent of this V1VirtualMachineMetrics.  # noqa: E501
        :rtype: float
        """
        return self._cpu_usage_percent

    @cpu_usage_percent.setter
    def cpu_usage_percent(self, cpu_usage_percent: 'float'):
        """Sets the cpu_usage_percent of this V1VirtualMachineMetrics.


        :param cpu_usage_percent: The cpu_usage_percent of this V1VirtualMachineMetrics.  # noqa: E501
        :type: float
        """

        self._cpu_usage_percent = cpu_usage_percent

    @property
    def memory_available_bytes(self) -> 'float':
        """Gets the memory_available_bytes of this V1VirtualMachineMetrics.  # noqa: E501


        :return: The memory_available_bytes of this V1VirtualMachineMetrics.  # noqa: E501
        :rtype: float
        """
        return self._memory_available_bytes

    @memory_available_bytes.setter
    def memory_available_bytes(self, memory_available_bytes: 'float'):
        """Sets the memory_available_bytes of this V1VirtualMachineMetrics.


        :param memory_available_bytes: The memory_available_bytes of this V1VirtualMachineMetrics.  # noqa: E501
        :type: float
        """

        self._memory_available_bytes = memory_available_bytes

    @property
    def memory_resident_bytes(self) -> 'float':
        """Gets the memory_resident_bytes of this V1VirtualMachineMetrics.  # noqa: E501


        :return: The memory_resident_bytes of this V1VirtualMachineMetrics.  # noqa: E501
        :rtype: float
        """
        return self._memory_resident_bytes

    @memory_resident_bytes.setter
    def memory_resident_bytes(self, memory_resident_bytes: 'float'):
        """Sets the memory_resident_bytes of this V1VirtualMachineMetrics.


        :param memory_resident_bytes: The memory_resident_bytes of this V1VirtualMachineMetrics.  # noqa: E501
        :type: float
        """

        self._memory_resident_bytes = memory_resident_bytes

    @property
    def network_rx_bytes_per_sec(self) -> 'float':
        """Gets the network_rx_bytes_per_sec of this V1VirtualMachineMetrics.  # noqa: E501


        :return: The network_rx_bytes_per_sec of this V1VirtualMachineMetrics.  # noqa: E501
        :rtype: float
        """
        return self._network_rx_bytes_per_sec

    @network_rx_bytes_per_sec.setter
    def network_rx_bytes_per_sec(self, network_rx_bytes_per_sec: 'float'):
        """Sets the network_rx_bytes_per_sec of this V1VirtualMachineMetrics.


        :param network_rx_bytes_per_sec: The network_rx_bytes_per_sec of this V1VirtualMachineMetrics.  # noqa: E501
        :type: float
        """

        self._network_rx_bytes_per_sec = network_rx_bytes_per_sec

    @property
    def network_tx_bytes_per_sec(self) -> 'float':
        """Gets the network_tx_bytes_per_sec of this V1VirtualMachineMetrics.  # noqa: E501


        :return: The network_tx_bytes_per_sec of this V1VirtualMachineMetrics.  # noqa: E501
        :rtype: float
        """
        return self._network_tx_bytes_per_sec

    @network_tx_bytes_per_sec.setter
    def network_tx_bytes_per_sec(self, network_tx_bytes_per_sec: 'float'):
        """Sets the network_tx_bytes_per_sec of this V1VirtualMachineMetrics.


        :param network_tx_bytes_per_sec: The network_tx_bytes_per_sec of this V1VirtualMachineMetrics.  # noqa: E501
        :type: float
        """

        self._network_tx_bytes_per_sec = network_tx_bytes_per_sec

    @property
    def storage_iops_read(self) -> 'list[V1DriveIOPS]':
        """Gets the storage_iops_read of this V1VirtualMachineMetrics.  # noqa: E501


        :return: The storage_iops_read of this V1VirtualMachineMetrics.  # noqa: E501
        :rtype: list[V1DriveIOPS]
        """
        return self._storage_iops_read

    @storage_iops_read.setter
    def storage_iops_read(self, storage_iops_read: 'list[V1DriveIOPS]'):
        """Sets the storage_iops_read of this V1VirtualMachineMetrics.


        :param storage_iops_read: The storage_iops_read of this V1VirtualMachineMetrics.  # noqa: E501
        :type: list[V1DriveIOPS]
        """

        self._storage_iops_read = storage_iops_read

    @property
    def storage_iops_write(self) -> 'list[V1DriveIOPS]':
        """Gets the storage_iops_write of this V1VirtualMachineMetrics.  # noqa: E501


        :return: The storage_iops_write of this V1VirtualMachineMetrics.  # noqa: E501
        :rtype: list[V1DriveIOPS]
        """
        return self._storage_iops_write

    @storage_iops_write.setter
    def storage_iops_write(self, storage_iops_write: 'list[V1DriveIOPS]'):
        """Sets the storage_iops_write of this V1VirtualMachineMetrics.


        :param storage_iops_write: The storage_iops_write of this V1VirtualMachineMetrics.  # noqa: E501
        :type: list[V1DriveIOPS]
        """

        self._storage_iops_write = storage_iops_write

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1VirtualMachineMetrics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1VirtualMachineMetrics') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1VirtualMachineMetrics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1VirtualMachineMetrics') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
