"""Public API for querying an organization's (or teamspace's) billing/usage activity.

:class:`Billing` is the entry point: construct it with an organization and/or one or more
teamspaces to scope subsequent queries to, then use :meth:`Billing.get_activity` and friends
to fetch usage data. :class:`BillingActivityFilters` and :class:`BillingActivityCursor` narrow
down and paginate those queries, respectively.
"""

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Union

from lightning_sdk.api.billing_api import BillingActivity, BillingActivityFilterValues, BillingApi
from lightning_sdk.organization import Organization
from lightning_sdk.teamspace import Teamspace
from lightning_sdk.utils.resolve import _resolve_org, _resolve_teamspace


@dataclass
class BillingActivityFilters:
    """Filters for narrowing down a billing activity query.

    Attributes:
        resource_types: Only include activity for these resource types (e.g. "Studio", "Job").
        resource_ids: Only include activity for these specific resource IDs.
        user_ids: Only include activity generated by these users.
        start: Only include activity on or after this time.
        end: Only include activity on or before this time.
        limit: Maximum number of entries to return.
    """

    resource_types: Optional[List[str]] = None
    resource_ids: Optional[List[str]] = None
    user_ids: Optional[List[str]] = None
    start: Optional[datetime] = None
    end: Optional[datetime] = None
    limit: Optional[int] = None


@dataclass
class BillingActivityCursor:
    """Pagination cursor for continuing a billing activity query.

    Attributes:
        search_after: Only include entries strictly after this time.
        search_after_resource_id: Resource ID of the last entry from the previous page. Required
            alongside ``search_after`` to break ties between resources sharing the same time.
        search_after_resource_type: Resource type of the last entry from the previous page.
            Required alongside ``search_after`` to break ties between resources sharing the same
            time.
    """

    search_after: Optional[datetime] = None
    search_after_resource_id: Optional[str] = None
    search_after_resource_type: Optional[str] = None


class Billing:
    """Query billing activity for an organization, or one or more of its teamspaces.

    Args:
        org: The organization to query, or the owning organization of ``teamspace``/``teamspaces``.
            If omitted, it's inferred from the given teamspace(s), or from the environment.
        teamspace: A single teamspace to scope the query to.
        teamspaces: Multiple teamspaces to scope the query to.

    Note:
        Provide at most one of ``teamspace``/``teamspaces``. Provide ``org`` on its own to query
        billing activity across an entire organization, or alongside ``teamspace``/``teamspaces``
        to narrow it down to specific teamspaces within that organization.
    """

    def __init__(
        self,
        org: Optional[Union[str, "Organization"]] = None,
        teamspace: Optional[Union[str, "Teamspace"]] = None,
        teamspaces: Optional[List[Union[str, "Teamspace"]]] = None,
    ) -> None:
        if teamspace is not None and teamspaces is not None:
            raise ValueError("Provide at most one of 'teamspace' or 'teamspaces'.")

        self._billing_api = BillingApi()

        resolved_org = _resolve_org(org)
        self._teamspaces: List["Teamspace"] = []

        raw_teamspaces: List[Union[str, "Teamspace"]] = []
        if teamspace is not None:
            raw_teamspaces = [teamspace]
        elif teamspaces is not None:
            raw_teamspaces = list(teamspaces)

        for raw_teamspace in raw_teamspaces:
            resolved_teamspace = _resolve_teamspace(raw_teamspace, org=resolved_org, user=None)
            if resolved_teamspace is None:
                raise ValueError(f"Could not resolve teamspace {raw_teamspace!r}.")
            if (
                resolved_org is not None
                and isinstance(resolved_teamspace.owner, Organization)
                and resolved_teamspace.owner.id != resolved_org.id
            ):
                raise ValueError(
                    f"Teamspace '{resolved_teamspace.name}' belongs to organization "
                    f"'{resolved_teamspace.owner.name}', not '{resolved_org.name}'."
                )
            self._teamspaces.append(resolved_teamspace)

        if resolved_org is None:
            for resolved_teamspace in self._teamspaces:
                if not isinstance(resolved_teamspace.owner, Organization):
                    continue
                if resolved_org is None:
                    resolved_org = resolved_teamspace.owner
                elif resolved_teamspace.owner.id != resolved_org.id:
                    raise ValueError(
                        "All teamspaces must belong to the same organization, but got "
                        f"'{resolved_org.name}' and '{resolved_teamspace.owner.name}'."
                    )

        if resolved_org is None:
            raise ValueError(
                "Could not resolve an organization to query billing activity for. Provide 'org', "
                "or an org-owned 'teamspace'/'teamspaces', or set 'LIGHTNING_ORG'."
            )

        self._org: "Organization" = resolved_org

    def _project_ids(self) -> Optional[List[str]]:
        """IDs of the configured teamspace(s), or ``None`` to scope to the whole organization."""
        if not self._teamspaces:
            return None
        return [teamspace.id for teamspace in self._teamspaces]

    def get_activity(
        self,
        filters: Optional[BillingActivityFilters] = None,
        cursor: Optional[BillingActivityCursor] = None,
    ) -> BillingActivity:
        """Get billing activity for the configured org/teamspace scope.

        Args:
            filters: Optional filters to narrow down the query.
            cursor: Optional pagination cursor to continue a previous query.

        Returns:
            BillingActivity: The usage report response.
        """
        filters = filters or BillingActivityFilters()
        cursor = cursor or BillingActivityCursor()

        return self._billing_api.get_activity(
            org_id=self._org.id,
            project_ids=self._project_ids(),
            resource_types=filters.resource_types,
            resource_ids=filters.resource_ids,
            user_ids=filters.user_ids,
            start=filters.start,
            end=filters.end,
            limit=filters.limit,
            search_after=cursor.search_after,
            search_after_resource_id=cursor.search_after_resource_id,
            search_after_resource_type=cursor.search_after_resource_type,
        )

    def get_activity_filter_values(self) -> BillingActivityFilterValues:
        """Get the set of values a billing activity query can be filtered by, for this scope.

        Returns:
            BillingActivityFilterValues: The available filter values.

        Raises:
            ValueError: If configured with more than one teamspace, since the underlying
                endpoint only supports a single teamspace scope (or the whole organization).
        """
        if len(self._teamspaces) > 1:
            raise ValueError(
                "get_activity_filter_values() only supports a single teamspace scope (or the "
                "whole organization), not multiple teamspaces."
            )

        project_id = self._teamspaces[0].id if self._teamspaces else None

        return self._billing_api.get_activity_filter_values(org_id=self._org.id, project_id=project_id)

    def download_detailed_activity_csv(
        self,
        target_path: Union[str, Path],
        filters: Optional[BillingActivityFilters] = None,
        cursor: Optional[BillingActivityCursor] = None,
    ) -> None:
        """Download the detailed billing activity report for the configured scope as a CSV file.

        Args:
            target_path: Local filesystem path to write the downloaded CSV to.
            filters: Optional filters to narrow down the report.
            cursor: Optional pagination cursor to continue a previous query.
        """
        filters = filters or BillingActivityFilters()
        cursor = cursor or BillingActivityCursor()

        self._billing_api.download_detailed_activity_csv(
            target_path=target_path,
            org_id=self._org.id,
            project_ids=self._project_ids(),
            resource_types=filters.resource_types,
            resource_ids=filters.resource_ids,
            user_ids=filters.user_ids,
            start=filters.start,
            end=filters.end,
            limit=filters.limit,
            search_after=cursor.search_after,
            search_after_resource_id=cursor.search_after_resource_id,
            search_after_resource_type=cursor.search_after_resource_type,
        )

    def download_summary_activity_csv(
        self,
        target_path: Union[str, Path],
        filters: Optional[BillingActivityFilters] = None,
        cursor: Optional[BillingActivityCursor] = None,
    ) -> None:
        """Download the summarized billing activity report for the configured scope as a CSV file.

        Args:
            target_path: Local filesystem path to write the downloaded CSV to.
            filters: Optional filters to narrow down the report.
            cursor: Optional pagination cursor to continue a previous query.
        """
        filters = filters or BillingActivityFilters()
        cursor = cursor or BillingActivityCursor()

        self._billing_api.download_summary_activity_csv(
            target_path=target_path,
            org_id=self._org.id,
            project_ids=self._project_ids(),
            resource_types=filters.resource_types,
            resource_ids=filters.resource_ids,
            user_ids=filters.user_ids,
            start=filters.start,
            end=filters.end,
            limit=filters.limit,
            search_after=cursor.search_after,
            search_after_resource_id=cursor.search_after_resource_id,
            search_after_resource_type=cursor.search_after_resource_type,
        )

    def get_detailed_activity_json(
        self,
        target_path: Optional[Union[str, Path]] = None,
        filters: Optional[BillingActivityFilters] = None,
        cursor: Optional[BillingActivityCursor] = None,
    ) -> str:
        """Get the detailed billing activity report for the configured scope as a JSON string.

        Args:
            target_path: If given, also write the JSON string to this local filesystem path.
                Otherwise, nothing is written to disk.
            filters: Optional filters to narrow down the report.
            cursor: Optional pagination cursor to continue a previous query.

        Returns:
            str: The JSON string representation of the detailed activity report.
        """
        filters = filters or BillingActivityFilters()
        cursor = cursor or BillingActivityCursor()

        return self._billing_api.get_detailed_activity_json(
            org_id=self._org.id,
            target_path=target_path,
            project_ids=self._project_ids(),
            resource_types=filters.resource_types,
            resource_ids=filters.resource_ids,
            user_ids=filters.user_ids,
            start=filters.start,
            end=filters.end,
            limit=filters.limit,
            search_after=cursor.search_after,
            search_after_resource_id=cursor.search_after_resource_id,
            search_after_resource_type=cursor.search_after_resource_type,
        )

    def get_summary_activity_json(
        self,
        target_path: Optional[Union[str, Path]] = None,
        filters: Optional[BillingActivityFilters] = None,
        cursor: Optional[BillingActivityCursor] = None,
    ) -> str:
        """Get the summarized billing activity report for the configured scope as a JSON string.

        Args:
            target_path: If given, also write the JSON string to this local filesystem path.
                Otherwise, nothing is written to disk.
            filters: Optional filters to narrow down the report.
            cursor: Optional pagination cursor to continue a previous query.

        Returns:
            str: The JSON string representation of the summary activity report.
        """
        filters = filters or BillingActivityFilters()
        cursor = cursor or BillingActivityCursor()

        return self._billing_api.get_summary_activity_json(
            org_id=self._org.id,
            target_path=target_path,
            project_ids=self._project_ids(),
            resource_types=filters.resource_types,
            resource_ids=filters.resource_ids,
            user_ids=filters.user_ids,
            start=filters.start,
            end=filters.end,
            limit=filters.limit,
            search_after=cursor.search_after,
            search_after_resource_id=cursor.search_after_resource_id,
            search_after_resource_type=cursor.search_after_resource_type,
        )
