name: "Build (& deploy) Docs"
on:
  workflow_dispatch:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

jobs:
  build:
    uses: Lightning-AI/utilities/.github/workflows/check-docs.yml@main
    with:
      requirements-file: "docs/requirements.txt"
      install-tex: true
      make-target: "['html', 'doctest', 'linkcheck', 'latexpdf']"

  # https://github.com/marketplace/actions/deploy-to-github-pages
  # build-docs-deploy:
  #   needs: build-docs
  #   if: github.event_name != 'pull_request'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout 🛎️
  #       uses: actions/checkout@v4
  #       # If you're using actions/checkout v3+ you must set persist-credentials to false in most cases for the deployment to work correctly.
  #       with:
  #         persist-credentials: false
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: docs-${{ github.sha }}
  #         path: docs/build/html
  #         merge-multiple: true

  #     - name: Deploy 🚀
  #       uses: JamesIves/github-pages-deploy-action@v4.4.3
  #       if: ${{ github.event_name == 'push' }}
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         branch: gh-pages # The branch the action should deploy to.
  #         folder: docs/build/html # The folder the action should deploy.
  #         clean: true # Automatically remove deleted files from the deploy branch
  #         target-folder: docs # If you'd like to push the contents of the deployment folder into a specific directory
  #         single-commit: true # you'd prefer to have a single commit on the deployment branch instead of full history

  guardian-docs:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
    - run: echo "${{ needs.build.result }}"
    - name: failing...
      if: needs.build.result == 'failure'
      run: exit 1
    - name: cancelled or skipped...
      if: contains(fromJSON('["cancelled", "skipped"]'), needs.build.result)
      timeout-minutes: 1
      run: sleep 90
