name: Docs

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  docs-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        root: [sdk, cli]
    if: github.event.pull_request.draft == false
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Install uv and setup python
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        activate-environment: true
        python-version: "3.12"
        enable-cache: true

    - name: Install package & doc dependencies
      working-directory: python
      run: |
        uv sync --group docs
        uv pip install -e .
        uv pip list

    - name: Build docs
      working-directory: python/docs/${{ matrix.root }}
      run: |
        export PATH="$PWD/../../.venv/bin:$PATH"
        make html SPHINXOPTS="-W --keep-going"

    - name: Upload docs artifact
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: docs-${{ matrix.root }}
        path: python/docs/${{ matrix.root }}/build/html/
        retention-days: 7

  docs-linkcheck:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        root: [sdk, cli]
    if: github.event.pull_request.draft == false
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Install uv and setup python
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        activate-environment: true
        python-version: "3.12"
        enable-cache: true

    - name: Install package & doc dependencies
      working-directory: python
      run: |
        uv sync --group docs
        uv pip install -e .

    - name: Check links
      working-directory: python/docs/${{ matrix.root }}
      run: |
        export PATH="$PWD/../../.venv/bin:$PATH"
        make linkcheck

  guardian-docs:
    runs-on: ubuntu-latest
    needs: [docs-build, docs-linkcheck]
    if: always() && (github.event_name != 'pull_request' || github.event.pull_request.draft == false)
    steps:
    - run: |
        echo "build: ${{ needs.docs-build.result }}"
        echo "linkcheck: ${{ needs.docs-linkcheck.result }}"
    - name: failing...
      if: |
        needs.docs-build.result == 'failure' ||
        needs.docs-linkcheck.result == 'failure'
      run: exit 1
    - name: cancelled or skipped...
      if: |
        contains(fromJSON('["cancelled", "skipped"]'), needs.docs-build.result) ||
        contains(fromJSON('["cancelled", "skipped"]'), needs.docs-linkcheck.result)
      timeout-minutes: 1
      run: sleep 90
