name: Mypy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  contents: read

jobs:
  mypy:
    name: Mypy
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Install uv and set up Python
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        activate-environment: true
        python-version: "3.11"
        enable-cache: true

    - name: Run mypy
      working-directory: python
      run: uv run --group typing --extra serve mypy
