# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class AssistantsIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'endpoint_id': 'str',
        'name': 'str',
        'prompt_template': 'str',
        'user_id': 'str'
    }

    attribute_map = {
        'endpoint_id': 'endpointId',
        'name': 'name',
        'prompt_template': 'promptTemplate',
        'user_id': 'userId'
    }

    def __init__(self, endpoint_id: 'str' =None, name: 'str' =None, prompt_template: 'str' =None, user_id: 'str' =None):  # noqa: E501
        """AssistantsIdBody - a model defined in Swagger"""  # noqa: E501
        self._endpoint_id = None
        self._name = None
        self._prompt_template = None
        self._user_id = None
        self.discriminator = None
        if endpoint_id is not None:
            self.endpoint_id = endpoint_id
        if name is not None:
            self.name = name
        if prompt_template is not None:
            self.prompt_template = prompt_template
        if user_id is not None:
            self.user_id = user_id

    @property
    def endpoint_id(self) -> 'str':
        """Gets the endpoint_id of this AssistantsIdBody.  # noqa: E501


        :return: The endpoint_id of this AssistantsIdBody.  # noqa: E501
        :rtype: str
        """
        return self._endpoint_id

    @endpoint_id.setter
    def endpoint_id(self, endpoint_id: 'str'):
        """Sets the endpoint_id of this AssistantsIdBody.


        :param endpoint_id: The endpoint_id of this AssistantsIdBody.  # noqa: E501
        :type: str
        """

        self._endpoint_id = endpoint_id

    @property
    def name(self) -> 'str':
        """Gets the name of this AssistantsIdBody.  # noqa: E501


        :return: The name of this AssistantsIdBody.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: 'str'):
        """Sets the name of this AssistantsIdBody.


        :param name: The name of this AssistantsIdBody.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def prompt_template(self) -> 'str':
        """Gets the prompt_template of this AssistantsIdBody.  # noqa: E501


        :return: The prompt_template of this AssistantsIdBody.  # noqa: E501
        :rtype: str
        """
        return self._prompt_template

    @prompt_template.setter
    def prompt_template(self, prompt_template: 'str'):
        """Sets the prompt_template of this AssistantsIdBody.


        :param prompt_template: The prompt_template of this AssistantsIdBody.  # noqa: E501
        :type: str
        """

        self._prompt_template = prompt_template

    @property
    def user_id(self) -> 'str':
        """Gets the user_id of this AssistantsIdBody.  # noqa: E501


        :return: The user_id of this AssistantsIdBody.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: 'str'):
        """Sets the user_id of this AssistantsIdBody.


        :param user_id: The user_id of this AssistantsIdBody.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssistantsIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'AssistantsIdBody') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, AssistantsIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'AssistantsIdBody') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
