# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class GitCredentialsServiceUpdateGitProviderBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hostname': 'str',
        'oauth_client_id': 'str',
        'oauth_client_secret': 'str',
        'oauth_hostname': 'str',
        'type': 'V1GitProviderType'
    }

    attribute_map = {
        'hostname': 'hostname',
        'oauth_client_id': 'oauthClientId',
        'oauth_client_secret': 'oauthClientSecret',
        'oauth_hostname': 'oauthHostname',
        'type': 'type'
    }

    def __init__(self, hostname: 'str' =None, oauth_client_id: 'str' =None, oauth_client_secret: 'str' =None, oauth_hostname: 'str' =None, type: 'V1GitProviderType' =None):  # noqa: E501
        """GitCredentialsServiceUpdateGitProviderBody - a model defined in Swagger"""  # noqa: E501
        self._hostname = None
        self._oauth_client_id = None
        self._oauth_client_secret = None
        self._oauth_hostname = None
        self._type = None
        self.discriminator = None
        if hostname is not None:
            self.hostname = hostname
        if oauth_client_id is not None:
            self.oauth_client_id = oauth_client_id
        if oauth_client_secret is not None:
            self.oauth_client_secret = oauth_client_secret
        if oauth_hostname is not None:
            self.oauth_hostname = oauth_hostname
        if type is not None:
            self.type = type

    @property
    def hostname(self) -> 'str':
        """Gets the hostname of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501


        :return: The hostname of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname: 'str'):
        """Sets the hostname of this GitCredentialsServiceUpdateGitProviderBody.


        :param hostname: The hostname of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501
        :type: str
        """

        self._hostname = hostname

    @property
    def oauth_client_id(self) -> 'str':
        """Gets the oauth_client_id of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501


        :return: The oauth_client_id of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501
        :rtype: str
        """
        return self._oauth_client_id

    @oauth_client_id.setter
    def oauth_client_id(self, oauth_client_id: 'str'):
        """Sets the oauth_client_id of this GitCredentialsServiceUpdateGitProviderBody.


        :param oauth_client_id: The oauth_client_id of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501
        :type: str
        """

        self._oauth_client_id = oauth_client_id

    @property
    def oauth_client_secret(self) -> 'str':
        """Gets the oauth_client_secret of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501


        :return: The oauth_client_secret of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501
        :rtype: str
        """
        return self._oauth_client_secret

    @oauth_client_secret.setter
    def oauth_client_secret(self, oauth_client_secret: 'str'):
        """Sets the oauth_client_secret of this GitCredentialsServiceUpdateGitProviderBody.


        :param oauth_client_secret: The oauth_client_secret of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501
        :type: str
        """

        self._oauth_client_secret = oauth_client_secret

    @property
    def oauth_hostname(self) -> 'str':
        """Gets the oauth_hostname of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501


        :return: The oauth_hostname of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501
        :rtype: str
        """
        return self._oauth_hostname

    @oauth_hostname.setter
    def oauth_hostname(self, oauth_hostname: 'str'):
        """Sets the oauth_hostname of this GitCredentialsServiceUpdateGitProviderBody.


        :param oauth_hostname: The oauth_hostname of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501
        :type: str
        """

        self._oauth_hostname = oauth_hostname

    @property
    def type(self) -> 'V1GitProviderType':
        """Gets the type of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501


        :return: The type of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501
        :rtype: V1GitProviderType
        """
        return self._type

    @type.setter
    def type(self, type: 'V1GitProviderType'):
        """Sets the type of this GitCredentialsServiceUpdateGitProviderBody.


        :param type: The type of this GitCredentialsServiceUpdateGitProviderBody.  # noqa: E501
        :type: V1GitProviderType
        """

        self._type = type

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GitCredentialsServiceUpdateGitProviderBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'GitCredentialsServiceUpdateGitProviderBody') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, GitCredentialsServiceUpdateGitProviderBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'GitCredentialsServiceUpdateGitProviderBody') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
