# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1BulkUploadOrgMembersResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_count': 'int',
        'errors': 'list[V1BulkUploadOrgMembersRowError]',
        'processed_rows': 'int',
        'skipped_count': 'int',
        'total_rows': 'int'
    }

    attribute_map = {
        'created_count': 'createdCount',
        'errors': 'errors',
        'processed_rows': 'processedRows',
        'skipped_count': 'skippedCount',
        'total_rows': 'totalRows'
    }

    def __init__(self, created_count: 'int' =None, errors: 'list[V1BulkUploadOrgMembersRowError]' =None, processed_rows: 'int' =None, skipped_count: 'int' =None, total_rows: 'int' =None):  # noqa: E501
        """V1BulkUploadOrgMembersResponse - a model defined in Swagger"""  # noqa: E501
        self._created_count = None
        self._errors = None
        self._processed_rows = None
        self._skipped_count = None
        self._total_rows = None
        self.discriminator = None
        if created_count is not None:
            self.created_count = created_count
        if errors is not None:
            self.errors = errors
        if processed_rows is not None:
            self.processed_rows = processed_rows
        if skipped_count is not None:
            self.skipped_count = skipped_count
        if total_rows is not None:
            self.total_rows = total_rows

    @property
    def created_count(self) -> 'int':
        """Gets the created_count of this V1BulkUploadOrgMembersResponse.  # noqa: E501


        :return: The created_count of this V1BulkUploadOrgMembersResponse.  # noqa: E501
        :rtype: int
        """
        return self._created_count

    @created_count.setter
    def created_count(self, created_count: 'int'):
        """Sets the created_count of this V1BulkUploadOrgMembersResponse.


        :param created_count: The created_count of this V1BulkUploadOrgMembersResponse.  # noqa: E501
        :type: int
        """

        self._created_count = created_count

    @property
    def errors(self) -> 'list[V1BulkUploadOrgMembersRowError]':
        """Gets the errors of this V1BulkUploadOrgMembersResponse.  # noqa: E501


        :return: The errors of this V1BulkUploadOrgMembersResponse.  # noqa: E501
        :rtype: list[V1BulkUploadOrgMembersRowError]
        """
        return self._errors

    @errors.setter
    def errors(self, errors: 'list[V1BulkUploadOrgMembersRowError]'):
        """Sets the errors of this V1BulkUploadOrgMembersResponse.


        :param errors: The errors of this V1BulkUploadOrgMembersResponse.  # noqa: E501
        :type: list[V1BulkUploadOrgMembersRowError]
        """

        self._errors = errors

    @property
    def processed_rows(self) -> 'int':
        """Gets the processed_rows of this V1BulkUploadOrgMembersResponse.  # noqa: E501


        :return: The processed_rows of this V1BulkUploadOrgMembersResponse.  # noqa: E501
        :rtype: int
        """
        return self._processed_rows

    @processed_rows.setter
    def processed_rows(self, processed_rows: 'int'):
        """Sets the processed_rows of this V1BulkUploadOrgMembersResponse.


        :param processed_rows: The processed_rows of this V1BulkUploadOrgMembersResponse.  # noqa: E501
        :type: int
        """

        self._processed_rows = processed_rows

    @property
    def skipped_count(self) -> 'int':
        """Gets the skipped_count of this V1BulkUploadOrgMembersResponse.  # noqa: E501


        :return: The skipped_count of this V1BulkUploadOrgMembersResponse.  # noqa: E501
        :rtype: int
        """
        return self._skipped_count

    @skipped_count.setter
    def skipped_count(self, skipped_count: 'int'):
        """Sets the skipped_count of this V1BulkUploadOrgMembersResponse.


        :param skipped_count: The skipped_count of this V1BulkUploadOrgMembersResponse.  # noqa: E501
        :type: int
        """

        self._skipped_count = skipped_count

    @property
    def total_rows(self) -> 'int':
        """Gets the total_rows of this V1BulkUploadOrgMembersResponse.  # noqa: E501


        :return: The total_rows of this V1BulkUploadOrgMembersResponse.  # noqa: E501
        :rtype: int
        """
        return self._total_rows

    @total_rows.setter
    def total_rows(self, total_rows: 'int'):
        """Sets the total_rows of this V1BulkUploadOrgMembersResponse.


        :param total_rows: The total_rows of this V1BulkUploadOrgMembersResponse.  # noqa: E501
        :type: int
        """

        self._total_rows = total_rows

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1BulkUploadOrgMembersResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1BulkUploadOrgMembersResponse') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1BulkUploadOrgMembersResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1BulkUploadOrgMembersResponse') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
