# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1CapacityReservationUsedBy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cloudspace_id': 'str',
        'job_id': 'str',
        'project_id': 'str',
        'server_id': 'str',
        'user_id': 'str'
    }

    attribute_map = {
        'cloudspace_id': 'cloudspaceId',
        'job_id': 'jobId',
        'project_id': 'projectId',
        'server_id': 'serverId',
        'user_id': 'userId'
    }

    def __init__(self, cloudspace_id: 'str' =None, job_id: 'str' =None, project_id: 'str' =None, server_id: 'str' =None, user_id: 'str' =None):  # noqa: E501
        """V1CapacityReservationUsedBy - a model defined in Swagger"""  # noqa: E501
        self._cloudspace_id = None
        self._job_id = None
        self._project_id = None
        self._server_id = None
        self._user_id = None
        self.discriminator = None
        if cloudspace_id is not None:
            self.cloudspace_id = cloudspace_id
        if job_id is not None:
            self.job_id = job_id
        if project_id is not None:
            self.project_id = project_id
        if server_id is not None:
            self.server_id = server_id
        if user_id is not None:
            self.user_id = user_id

    @property
    def cloudspace_id(self) -> 'str':
        """Gets the cloudspace_id of this V1CapacityReservationUsedBy.  # noqa: E501


        :return: The cloudspace_id of this V1CapacityReservationUsedBy.  # noqa: E501
        :rtype: str
        """
        return self._cloudspace_id

    @cloudspace_id.setter
    def cloudspace_id(self, cloudspace_id: 'str'):
        """Sets the cloudspace_id of this V1CapacityReservationUsedBy.


        :param cloudspace_id: The cloudspace_id of this V1CapacityReservationUsedBy.  # noqa: E501
        :type: str
        """

        self._cloudspace_id = cloudspace_id

    @property
    def job_id(self) -> 'str':
        """Gets the job_id of this V1CapacityReservationUsedBy.  # noqa: E501


        :return: The job_id of this V1CapacityReservationUsedBy.  # noqa: E501
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id: 'str'):
        """Sets the job_id of this V1CapacityReservationUsedBy.


        :param job_id: The job_id of this V1CapacityReservationUsedBy.  # noqa: E501
        :type: str
        """

        self._job_id = job_id

    @property
    def project_id(self) -> 'str':
        """Gets the project_id of this V1CapacityReservationUsedBy.  # noqa: E501


        :return: The project_id of this V1CapacityReservationUsedBy.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id: 'str'):
        """Sets the project_id of this V1CapacityReservationUsedBy.


        :param project_id: The project_id of this V1CapacityReservationUsedBy.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def server_id(self) -> 'str':
        """Gets the server_id of this V1CapacityReservationUsedBy.  # noqa: E501


        :return: The server_id of this V1CapacityReservationUsedBy.  # noqa: E501
        :rtype: str
        """
        return self._server_id

    @server_id.setter
    def server_id(self, server_id: 'str'):
        """Sets the server_id of this V1CapacityReservationUsedBy.


        :param server_id: The server_id of this V1CapacityReservationUsedBy.  # noqa: E501
        :type: str
        """

        self._server_id = server_id

    @property
    def user_id(self) -> 'str':
        """Gets the user_id of this V1CapacityReservationUsedBy.  # noqa: E501


        :return: The user_id of this V1CapacityReservationUsedBy.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: 'str'):
        """Sets the user_id of this V1CapacityReservationUsedBy.


        :param user_id: The user_id of this V1CapacityReservationUsedBy.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1CapacityReservationUsedBy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1CapacityReservationUsedBy') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1CapacityReservationUsedBy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1CapacityReservationUsedBy') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
