# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1ListAPIKeysResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'api_keys': 'list[V1APIKey]'
    }

    attribute_map = {
        'api_keys': 'apiKeys'
    }

    def __init__(self, api_keys: 'list[V1APIKey]' =None):  # noqa: E501
        """V1ListAPIKeysResponse - a model defined in Swagger"""  # noqa: E501
        self._api_keys = None
        self.discriminator = None
        if api_keys is not None:
            self.api_keys = api_keys

    @property
    def api_keys(self) -> 'list[V1APIKey]':
        """Gets the api_keys of this V1ListAPIKeysResponse.  # noqa: E501


        :return: The api_keys of this V1ListAPIKeysResponse.  # noqa: E501
        :rtype: list[V1APIKey]
        """
        return self._api_keys

    @api_keys.setter
    def api_keys(self, api_keys: 'list[V1APIKey]'):
        """Sets the api_keys of this V1ListAPIKeysResponse.


        :param api_keys: The api_keys of this V1ListAPIKeysResponse.  # noqa: E501
        :type: list[V1APIKey]
        """

        self._api_keys = api_keys

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1ListAPIKeysResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1ListAPIKeysResponse') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1ListAPIKeysResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1ListAPIKeysResponse') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
