# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1Message(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'author': 'V1MessageAuthor',
        'content': 'V1MessageContent',
        'id': 'str'
    }

    attribute_map = {
        'author': 'author',
        'content': 'content',
        'id': 'id'
    }

    def __init__(self, author: 'V1MessageAuthor' =None, content: 'V1MessageContent' =None, id: 'str' =None):  # noqa: E501
        """V1Message - a model defined in Swagger"""  # noqa: E501
        self._author = None
        self._content = None
        self._id = None
        self.discriminator = None
        if author is not None:
            self.author = author
        if content is not None:
            self.content = content
        if id is not None:
            self.id = id

    @property
    def author(self) -> 'V1MessageAuthor':
        """Gets the author of this V1Message.  # noqa: E501


        :return: The author of this V1Message.  # noqa: E501
        :rtype: V1MessageAuthor
        """
        return self._author

    @author.setter
    def author(self, author: 'V1MessageAuthor'):
        """Sets the author of this V1Message.


        :param author: The author of this V1Message.  # noqa: E501
        :type: V1MessageAuthor
        """

        self._author = author

    @property
    def content(self) -> 'V1MessageContent':
        """Gets the content of this V1Message.  # noqa: E501


        :return: The content of this V1Message.  # noqa: E501
        :rtype: V1MessageContent
        """
        return self._content

    @content.setter
    def content(self, content: 'V1MessageContent'):
        """Sets the content of this V1Message.


        :param content: The content of this V1Message.  # noqa: E501
        :type: V1MessageContent
        """

        self._content = content

    @property
    def id(self) -> 'str':
        """Gets the id of this V1Message.  # noqa: E501


        :return: The id of this V1Message.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: 'str'):
        """Sets the id of this V1Message.


        :param id: The id of this V1Message.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1Message, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1Message') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1Message):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1Message') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
