# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1MountableDataConnection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mount_opts': 'str',
        'nfs_version': 'str',
        'password': 'str',
        'port': 'int',
        'protocol': 'str',
        'read_only': 'bool',
        'remote_path': 'str',
        'server_ip': 'str',
        'source': 'str',
        'type': 'V1StorageType',
        'username': 'str'
    }

    attribute_map = {
        'mount_opts': 'mountOpts',
        'nfs_version': 'nfsVersion',
        'password': 'password',
        'port': 'port',
        'protocol': 'protocol',
        'read_only': 'readOnly',
        'remote_path': 'remotePath',
        'server_ip': 'serverIp',
        'source': 'source',
        'type': 'type',
        'username': 'username'
    }

    def __init__(self, mount_opts: 'str' =None, nfs_version: 'str' =None, password: 'str' =None, port: 'int' =None, protocol: 'str' =None, read_only: 'bool' =None, remote_path: 'str' =None, server_ip: 'str' =None, source: 'str' =None, type: 'V1StorageType' =None, username: 'str' =None):  # noqa: E501
        """V1MountableDataConnection - a model defined in Swagger"""  # noqa: E501
        self._mount_opts = None
        self._nfs_version = None
        self._password = None
        self._port = None
        self._protocol = None
        self._read_only = None
        self._remote_path = None
        self._server_ip = None
        self._source = None
        self._type = None
        self._username = None
        self.discriminator = None
        if mount_opts is not None:
            self.mount_opts = mount_opts
        if nfs_version is not None:
            self.nfs_version = nfs_version
        if password is not None:
            self.password = password
        if port is not None:
            self.port = port
        if protocol is not None:
            self.protocol = protocol
        if read_only is not None:
            self.read_only = read_only
        if remote_path is not None:
            self.remote_path = remote_path
        if server_ip is not None:
            self.server_ip = server_ip
        if source is not None:
            self.source = source
        if type is not None:
            self.type = type
        if username is not None:
            self.username = username

    @property
    def mount_opts(self) -> 'str':
        """Gets the mount_opts of this V1MountableDataConnection.  # noqa: E501


        :return: The mount_opts of this V1MountableDataConnection.  # noqa: E501
        :rtype: str
        """
        return self._mount_opts

    @mount_opts.setter
    def mount_opts(self, mount_opts: 'str'):
        """Sets the mount_opts of this V1MountableDataConnection.


        :param mount_opts: The mount_opts of this V1MountableDataConnection.  # noqa: E501
        :type: str
        """

        self._mount_opts = mount_opts

    @property
    def nfs_version(self) -> 'str':
        """Gets the nfs_version of this V1MountableDataConnection.  # noqa: E501


        :return: The nfs_version of this V1MountableDataConnection.  # noqa: E501
        :rtype: str
        """
        return self._nfs_version

    @nfs_version.setter
    def nfs_version(self, nfs_version: 'str'):
        """Sets the nfs_version of this V1MountableDataConnection.


        :param nfs_version: The nfs_version of this V1MountableDataConnection.  # noqa: E501
        :type: str
        """

        self._nfs_version = nfs_version

    @property
    def password(self) -> 'str':
        """Gets the password of this V1MountableDataConnection.  # noqa: E501


        :return: The password of this V1MountableDataConnection.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: 'str'):
        """Sets the password of this V1MountableDataConnection.


        :param password: The password of this V1MountableDataConnection.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def port(self) -> 'int':
        """Gets the port of this V1MountableDataConnection.  # noqa: E501


        :return: The port of this V1MountableDataConnection.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port: 'int'):
        """Sets the port of this V1MountableDataConnection.


        :param port: The port of this V1MountableDataConnection.  # noqa: E501
        :type: int
        """

        self._port = port

    @property
    def protocol(self) -> 'str':
        """Gets the protocol of this V1MountableDataConnection.  # noqa: E501

        \"nfs\", \"smb\", \"s3\", etc.  # noqa: E501

        :return: The protocol of this V1MountableDataConnection.  # noqa: E501
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol: 'str'):
        """Sets the protocol of this V1MountableDataConnection.

        \"nfs\", \"smb\", \"s3\", etc.  # noqa: E501

        :param protocol: The protocol of this V1MountableDataConnection.  # noqa: E501
        :type: str
        """

        self._protocol = protocol

    @property
    def read_only(self) -> 'bool':
        """Gets the read_only of this V1MountableDataConnection.  # noqa: E501


        :return: The read_only of this V1MountableDataConnection.  # noqa: E501
        :rtype: bool
        """
        return self._read_only

    @read_only.setter
    def read_only(self, read_only: 'bool'):
        """Sets the read_only of this V1MountableDataConnection.


        :param read_only: The read_only of this V1MountableDataConnection.  # noqa: E501
        :type: bool
        """

        self._read_only = read_only

    @property
    def remote_path(self) -> 'str':
        """Gets the remote_path of this V1MountableDataConnection.  # noqa: E501


        :return: The remote_path of this V1MountableDataConnection.  # noqa: E501
        :rtype: str
        """
        return self._remote_path

    @remote_path.setter
    def remote_path(self, remote_path: 'str'):
        """Sets the remote_path of this V1MountableDataConnection.


        :param remote_path: The remote_path of this V1MountableDataConnection.  # noqa: E501
        :type: str
        """

        self._remote_path = remote_path

    @property
    def server_ip(self) -> 'str':
        """Gets the server_ip of this V1MountableDataConnection.  # noqa: E501


        :return: The server_ip of this V1MountableDataConnection.  # noqa: E501
        :rtype: str
        """
        return self._server_ip

    @server_ip.setter
    def server_ip(self, server_ip: 'str'):
        """Sets the server_ip of this V1MountableDataConnection.


        :param server_ip: The server_ip of this V1MountableDataConnection.  # noqa: E501
        :type: str
        """

        self._server_ip = server_ip

    @property
    def source(self) -> 'str':
        """Gets the source of this V1MountableDataConnection.  # noqa: E501


        :return: The source of this V1MountableDataConnection.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: 'str'):
        """Sets the source of this V1MountableDataConnection.


        :param source: The source of this V1MountableDataConnection.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def type(self) -> 'V1StorageType':
        """Gets the type of this V1MountableDataConnection.  # noqa: E501


        :return: The type of this V1MountableDataConnection.  # noqa: E501
        :rtype: V1StorageType
        """
        return self._type

    @type.setter
    def type(self, type: 'V1StorageType'):
        """Sets the type of this V1MountableDataConnection.


        :param type: The type of this V1MountableDataConnection.  # noqa: E501
        :type: V1StorageType
        """

        self._type = type

    @property
    def username(self) -> 'str':
        """Gets the username of this V1MountableDataConnection.  # noqa: E501


        :return: The username of this V1MountableDataConnection.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: 'str'):
        """Sets the username of this V1MountableDataConnection.


        :param username: The username of this V1MountableDataConnection.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1MountableDataConnection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1MountableDataConnection') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1MountableDataConnection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1MountableDataConnection') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
