# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1SeriesConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'color': 'str',
        'field': 'str',
        'id': 'str',
        'name': 'str',
        'order': 'int',
        'series_type': 'V1SeriesType',
        'stack_group': 'str',
        'unit': 'str'
    }

    attribute_map = {
        'color': 'color',
        'field': 'field',
        'id': 'id',
        'name': 'name',
        'order': 'order',
        'series_type': 'seriesType',
        'stack_group': 'stackGroup',
        'unit': 'unit'
    }

    def __init__(self, color: 'str' =None, field: 'str' =None, id: 'str' =None, name: 'str' =None, order: 'int' =None, series_type: 'V1SeriesType' =None, stack_group: 'str' =None, unit: 'str' =None):  # noqa: E501
        """V1SeriesConfig - a model defined in Swagger"""  # noqa: E501
        self._color = None
        self._field = None
        self._id = None
        self._name = None
        self._order = None
        self._series_type = None
        self._stack_group = None
        self._unit = None
        self.discriminator = None
        if color is not None:
            self.color = color
        if field is not None:
            self.field = field
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if order is not None:
            self.order = order
        if series_type is not None:
            self.series_type = series_type
        if stack_group is not None:
            self.stack_group = stack_group
        if unit is not None:
            self.unit = unit

    @property
    def color(self) -> 'str':
        """Gets the color of this V1SeriesConfig.  # noqa: E501


        :return: The color of this V1SeriesConfig.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color: 'str'):
        """Sets the color of this V1SeriesConfig.


        :param color: The color of this V1SeriesConfig.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def field(self) -> 'str':
        """Gets the field of this V1SeriesConfig.  # noqa: E501


        :return: The field of this V1SeriesConfig.  # noqa: E501
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field: 'str'):
        """Sets the field of this V1SeriesConfig.


        :param field: The field of this V1SeriesConfig.  # noqa: E501
        :type: str
        """

        self._field = field

    @property
    def id(self) -> 'str':
        """Gets the id of this V1SeriesConfig.  # noqa: E501


        :return: The id of this V1SeriesConfig.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: 'str'):
        """Sets the id of this V1SeriesConfig.


        :param id: The id of this V1SeriesConfig.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self) -> 'str':
        """Gets the name of this V1SeriesConfig.  # noqa: E501


        :return: The name of this V1SeriesConfig.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: 'str'):
        """Sets the name of this V1SeriesConfig.


        :param name: The name of this V1SeriesConfig.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def order(self) -> 'int':
        """Gets the order of this V1SeriesConfig.  # noqa: E501


        :return: The order of this V1SeriesConfig.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order: 'int'):
        """Sets the order of this V1SeriesConfig.


        :param order: The order of this V1SeriesConfig.  # noqa: E501
        :type: int
        """

        self._order = order

    @property
    def series_type(self) -> 'V1SeriesType':
        """Gets the series_type of this V1SeriesConfig.  # noqa: E501


        :return: The series_type of this V1SeriesConfig.  # noqa: E501
        :rtype: V1SeriesType
        """
        return self._series_type

    @series_type.setter
    def series_type(self, series_type: 'V1SeriesType'):
        """Sets the series_type of this V1SeriesConfig.


        :param series_type: The series_type of this V1SeriesConfig.  # noqa: E501
        :type: V1SeriesType
        """

        self._series_type = series_type

    @property
    def stack_group(self) -> 'str':
        """Gets the stack_group of this V1SeriesConfig.  # noqa: E501


        :return: The stack_group of this V1SeriesConfig.  # noqa: E501
        :rtype: str
        """
        return self._stack_group

    @stack_group.setter
    def stack_group(self, stack_group: 'str'):
        """Sets the stack_group of this V1SeriesConfig.


        :param stack_group: The stack_group of this V1SeriesConfig.  # noqa: E501
        :type: str
        """

        self._stack_group = stack_group

    @property
    def unit(self) -> 'str':
        """Gets the unit of this V1SeriesConfig.  # noqa: E501


        :return: The unit of this V1SeriesConfig.  # noqa: E501
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: 'str'):
        """Sets the unit of this V1SeriesConfig.


        :param unit: The unit of this V1SeriesConfig.  # noqa: E501
        :type: str
        """

        self._unit = unit

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1SeriesConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1SeriesConfig') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1SeriesConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1SeriesConfig') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
