# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1TenantCredentials(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'credentials_encoded_json': 'str',
        'project_id': 'str',
        'region': 'str',
        'vpc_subnet_id': 'str'
    }

    attribute_map = {
        'credentials_encoded_json': 'credentialsEncodedJson',
        'project_id': 'projectId',
        'region': 'region',
        'vpc_subnet_id': 'vpcSubnetId'
    }

    def __init__(self, credentials_encoded_json: 'str' =None, project_id: 'str' =None, region: 'str' =None, vpc_subnet_id: 'str' =None):  # noqa: E501
        """V1TenantCredentials - a model defined in Swagger"""  # noqa: E501
        self._credentials_encoded_json = None
        self._project_id = None
        self._region = None
        self._vpc_subnet_id = None
        self.discriminator = None
        if credentials_encoded_json is not None:
            self.credentials_encoded_json = credentials_encoded_json
        if project_id is not None:
            self.project_id = project_id
        if region is not None:
            self.region = region
        if vpc_subnet_id is not None:
            self.vpc_subnet_id = vpc_subnet_id

    @property
    def credentials_encoded_json(self) -> 'str':
        """Gets the credentials_encoded_json of this V1TenantCredentials.  # noqa: E501


        :return: The credentials_encoded_json of this V1TenantCredentials.  # noqa: E501
        :rtype: str
        """
        return self._credentials_encoded_json

    @credentials_encoded_json.setter
    def credentials_encoded_json(self, credentials_encoded_json: 'str'):
        """Sets the credentials_encoded_json of this V1TenantCredentials.


        :param credentials_encoded_json: The credentials_encoded_json of this V1TenantCredentials.  # noqa: E501
        :type: str
        """

        self._credentials_encoded_json = credentials_encoded_json

    @property
    def project_id(self) -> 'str':
        """Gets the project_id of this V1TenantCredentials.  # noqa: E501


        :return: The project_id of this V1TenantCredentials.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id: 'str'):
        """Sets the project_id of this V1TenantCredentials.


        :param project_id: The project_id of this V1TenantCredentials.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def region(self) -> 'str':
        """Gets the region of this V1TenantCredentials.  # noqa: E501


        :return: The region of this V1TenantCredentials.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region: 'str'):
        """Sets the region of this V1TenantCredentials.


        :param region: The region of this V1TenantCredentials.  # noqa: E501
        :type: str
        """

        self._region = region

    @property
    def vpc_subnet_id(self) -> 'str':
        """Gets the vpc_subnet_id of this V1TenantCredentials.  # noqa: E501


        :return: The vpc_subnet_id of this V1TenantCredentials.  # noqa: E501
        :rtype: str
        """
        return self._vpc_subnet_id

    @vpc_subnet_id.setter
    def vpc_subnet_id(self, vpc_subnet_id: 'str'):
        """Sets the vpc_subnet_id of this V1TenantCredentials.


        :param vpc_subnet_id: The vpc_subnet_id of this V1TenantCredentials.  # noqa: E501
        :type: str
        """

        self._vpc_subnet_id = vpc_subnet_id

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1TenantCredentials, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1TenantCredentials') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1TenantCredentials):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1TenantCredentials') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
